#ifndef SYSMENU_H_
#define SYSMENU_H_

#include <QtCore/QObject>
#include "basemenu.h"

typedef enum _tagDeviceType_
{
  DEV_TYPE_KEYBOARD = 1,
  DEV_TYPE_RPG,
  DEV_TYPE_TOUCH_SCREEN
} DeviceType;



typedef enum _tagKeyValue_
{
  KEY_R1C1 = 0xC0, KEY_R1C2 = 0xC1, KEY_R1C3 = 0xC2, KEY_R1C4 = 0xC3, KEY_R1C5 = 0xC4, KEY_R1C6 = 0xC5,KEY_R1C7 = 0xC6,KEY_R1C8 = 0xC7,
  KEY_R2C1 = 0xC8, KEY_R2C2 = 0xC9, KEY_R2C3 = 0xCA, KEY_R2C4 = 0xCB, KEY_R2C5 = 0xCC, KEY_R2C6 = 0xCD,KEY_R2C7 = 0xCE,KEY_R2C8 = 0xCF,
  KEY_R3C1 = 0xD0, KEY_R3C2 = 0xD1, KEY_R3C3 = 0xD2, KEY_R3C4 = 0xD3, KEY_R3C5 = 0xD4, KEY_R3C6 = 0xD5,KEY_R3C7 = 0xD6,KEY_R3C8 = 0xD7,
  KEY_R4C1 = 0xD8, KEY_R4C2 = 0xD9, KEY_R4C3 = 0xDA, KEY_R4C4 = 0xDB, KEY_R4C5 = 0xDC, KEY_R4C6 = 0xDD,KEY_R4C7 = 0xDE,KEY_R4C8 = 0xDF,
  KEY_R5C1 = 0xE0, KEY_R5C2 = 0xE1, KEY_R5C3 = 0xE2, KEY_R5C4 = 0xE3, KEY_R5C5 = 0xE4, KEY_R5C6 = 0xE5,KEY_R5C7 = 0xE6,KEY_R5C8 = 0xE7,
  KEY_R6C1 = 0xE8, KEY_R6C2 = 0xE9, KEY_R6C3 = 0xEA, KEY_R6C4 = 0xEB, KEY_R6C5 = 0xEC, KEY_R6C6 = 0xED,KEY_R6C7 = 0xEE,KEY_R6C8 = 0xEF,
  KEY_R7C1 = 0xF0, KEY_R7C2 = 0xF1, KEY_R7C3 = 0xF2, KEY_R7C4 = 0xF3, KEY_R7C5 = 0xF4, KEY_R7C6 = 0xF5,KEY_R7C7 = 0xF6,KEY_R7C8 = 0xF7,

} KeyValue;

typedef enum _tagRPG_Rotate_Direction_
{
  RPG_RIGHT_ROTATION = 1,
  RPG_LEFT_ROTATION
}RPG_Rotate_Direction;

//****************************************
//* 系统按键定义
//****************************************
#define KEY_SUB_MENU1         KEY_R1C1 //S1
#define KEY_SUB_MENU2         KEY_R2C1 //S9
#define KEY_SUB_MENU3         KEY_R3C1 //S17
#define KEY_SUB_MENU4         KEY_R4C1 //S25
#define KEY_SUB_MENU5         KEY_R5C1 //S32
#define KEY_SUB_MENU6         KEY_R6C1 //S39
#define KEY_SUB_MENU7         KEY_R7C1 //S46

#define KEY_MAIN_FREQ         KEY_R1C2 //S2
#define KEY_MAIN_SPAN         KEY_R2C2 //S10
#define KEY_MAIN_AMPT         KEY_R3C2 //S18
#define KEY_MAIN_TUNE         KEY_R4C2 //S26

#define KEY_MAIN_BW           KEY_R1C3 //S3
#define KEY_MAIN_SWEEP        KEY_R2C3 //S11
#define KEY_MAIN_TRIG         KEY_R3C3 //S19
#define KEY_MAIN_MEAS         KEY_R4C3 //S27

#define KEY_MAIN_TRACE        KEY_R1C4 //S4
#define KEY_MAIN_DETECTOR     KEY_R2C4 //S12
#define KEY_MAIN_DISPLAY      KEY_R3C4 //S20
#define KEY_MAIN_MEASSETUP    KEY_R4C4 //S28

#define KEY_MAIN_MARKER       KEY_R1C5 //S5
#define KEY_MAIN_MARKERFCTN   KEY_R2C5 //S13
#define KEY_MAIN_MARKERTO     KEY_R3C5 //S21
#define KEY_MAIN_PEAK         KEY_R4C5 //S29

#define KEY_MAIN_SYSTEM       KEY_R1C6 //S6
#define KEY_MAIN_FILE         KEY_R2C6 //S14
#define KEY_MAIN_SAVE         KEY_R3C6 //S22
#define KEY_MAIN_SOURCE       KEY_R4C6 //S30

#define KEY_MAIN_PRESET       KEY_R1C7 //S7
#define KEY_MAIN_PRINT        KEY_R2C7 //S15
#define KEY_MAIN_HELP         KEY_R3C7 //S23
#define KEY_MAIN_DEMOD        KEY_R4C7 //S31

//数字键
#define KEY_NUM_0             KEY_R5C6  //S37
#define KEY_NUM_1             KEY_R7C4  //S49
#define KEY_NUM_2             KEY_R7C5  //S50
#define KEY_NUM_3             KEY_R7C6  //S51
#define KEY_NUM_4             KEY_R6C2  //S40
#define KEY_NUM_5             KEY_R6C3  //S41
#define KEY_NUM_6             KEY_R6C4  //S42
#define KEY_NUM_7             KEY_R5C2  //S33
#define KEY_NUM_8             KEY_R5C3  //S34
#define KEY_NUM_9             KEY_R5C4  //S35
#define KEY_NUM_DOT           KEY_R5C7  //S38
#define KEY_NUM_NEG           KEY_R6C6  //S44
#define KEY_NUM_ESC           KEY_R1C8  //S8
//#define KEY_NUM_BKSPACE       KEY_R3C8  //S24 old
//#define KEY_NUM_ENTER         KEY_R2C8  //S16 old
#define KEY_NUM_ENTER         KEY_R3C8  //S24 new
#define KEY_NUM_BKSPACE       KEY_R2C8  //S16 new


//方向键
#define KEY_ARROW_UP          KEY_R7C3 //S48
#define KEY_ARROW_DOWN        KEY_R7C2 //S47


//单位键
#define KEY_UNIT_GHZ          KEY_R5C5 //S36
#define KEY_UNIT_MHZ          KEY_R6C5 //S43
#define KEY_UNIT_KHZ          KEY_R7C7 //S52
#define KEY_UNIT_HZ           KEY_R6C7 //S45

#define KEY_ARROW_RPG         0xDFFF
#define KEY_MAIN_AUX          0xEFFF

//****************************************
//* 功能码定义
//****************************************
#define KEY_FUNC_FREQ_CENTER                    0x00000100
#define KEY_FUNC_FREQ_CENTER_GHZ                0x00000101
#define KEY_FUNC_FREQ_CENTER_MHZ                0x00000102
#define KEY_FUNC_FREQ_CENTER_KHZ                0x00000103
#define KEY_FUNC_FREQ_CENTER_HZ                 0x00000104
#define KEY_FUNC_FREQ_START                     0x00000105
#define KEY_FUNC_FREQ_START_GHZ                 0x00000106
#define KEY_FUNC_FREQ_START_MHZ                 0x00000107
#define KEY_FUNC_FREQ_START_KHZ                 0x00000108
#define KEY_FUNC_FREQ_START_HZ                  0x00000109
#define KEY_FUNC_FREQ_STOP                      0x0000010A
#define KEY_FUNC_FREQ_STOP_GHZ                  0x0000010B
#define KEY_FUNC_FREQ_STOP_MHZ                  0x0000010C
#define KEY_FUNC_FREQ_STOP_KHZ                  0x0000010D
#define KEY_FUNC_FREQ_STOP_HZ                   0x0000010E
#define KEY_FUNC_FREQ_CFSTEP                    0x0000010F
#define KEY_FUNC_FREQ_CFSTEP_GHZ                0x00000110
#define KEY_FUNC_FREQ_CFSTEP_MHZ                0x00000111
#define KEY_FUNC_FREQ_CFSTEP_KHZ                0x00000112
#define KEY_FUNC_FREQ_CFSTEP_HZ                 0x00000113
#define KEY_FUNC_FREQ_OFFSET                    0x00000114
#define KEY_FUNC_FREQ_OFFSET_GHZ                0x00000115
#define KEY_FUNC_FREQ_OFFSET_MHZ                0x00000116
#define KEY_FUNC_FREQ_OFFSET_KHZ                0x00000117
#define KEY_FUNC_FREQ_OFFSET_HZ                 0x00000118
#define KEY_FUNC_FREQ_REFERENCE                 0x00000119
#define KEY_FUNC_FREQ_TYPE                      0x0000011A
#define KEY_FUNC_FREQ_LOW                       0x0000011B
#define KEY_FUNC_FREQ_NEXTPAGE									0x0000011C
#define KEY_FUNC_FREQ_SCALETYPE									0x0000011D
#define KEY_FUNC_FREQ_NEXTPAGE_RETURN						0x0000011E

#define KEY_FUNC_SPAN_SPAN                      0x00000200
#define KEY_FUNC_SPAN_SPAN_GHZ                  0x00000201
#define KEY_FUNC_SPAN_SPAN_MHZ                  0x00000202
#define KEY_FUNC_SPAN_SPAN_KHZ                  0x00000203
#define KEY_FUNC_SPAN_SPAN_HZ                   0x00000204
#define KEY_FUNC_SPAN_FULL                      0x00000205
#define KEY_FUNC_SPAN_ZERO                      0x00000206
#define KEY_FUNC_SPAN_LAST                      0x00000207

#define KEY_FUNC_AMPT_REFLEVEL                  0x00000300
#define KEY_FUNC_AMPT_REFLEVEL_DBM              0x00000301
#define KEY_FUNC_AMPT_ATT                       0x00000302
#define KEY_FUNC_AMPT_ATT_DB                    0x00000303
#define KEY_FUNC_AMPT_SCALEDIV                  0x00000304
#define KEY_FUNC_AMPT_SCALEDIV_DB               0x00000305
#define KEY_FUNC_AMPT_SCALETYPE                 0x00000306
#define KEY_FUNC_AMPT_REFOFFSET                 0x00000307
#define KEY_FUNC_AMPT_REFOFFSET_DB              0x00000308
#define KEY_FUNC_AMPT_REFUNIT                   0x00000309
#define KEY_FUNC_AMPT_REFUNIT_DBM               0x0000030A
#define KEY_FUNC_AMPT_REFUNIT_DBuW       		0x0000030B
#define KEY_FUNC_AMPT_REFUNIT_DBPW              0x0000030C
#define KEY_FUNC_AMPT_REFUNIT_DBMV              0x0000030D
#define KEY_FUNC_AMPT_REFUNIT_DBUV              0x0000030F
#define KEY_FUNC_AMPT_REFUNIT_W                 0x00000354
#define KEY_FUNC_AMPT_REFUNIT_V                 0x00000355
#define KEY_FUNC_AMPT_PREAMPT                   0x00000356

#define KEY_FUNC_AMPT_PASSFAIL                                          0x00000310
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW                                   0x00000311
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_WINDOW                            0x00000312
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_LIMITLINEON                       0x00000313
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQLINEON                        0x00000314
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_LIMITUPLOW                        0x00000315
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_LIMITUPLOW_DBM                    0x00000316
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP                     0x00000317
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_GHZ                 0x00000318
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_MHZ                 0x00000319
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_KHZ                 0x0000031A
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_HZ                  0x0000031B
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_WINDOWSWEEP                       0x0000031C
#define KEY_FUNC_AMPT_PASSFAIL_WINDOW_RETURN                            0x0000031D
#define KEY_FUNC_AMPT_PASSFAIL_LINE                                     0x0000031E
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE                                0x0000031F
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1ON                             0x00000320
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2ON                             0x00000321
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT                           0x00000322
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_FIRSTPAGE                 0x00000323
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_PREVPAGE                  0x00000324
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_NEXTPAGE                  0x00000325
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_LASTPAGE                  0x00000326
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION                 0x00000327
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_ADD             0x00000328
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_INSERT          0x00000329
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_DELETE          0x0000032A
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_CLEAR           0x00000330
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ        0x00000331
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_GHZ    0x00000332
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_MHZ    0x00000333
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_KHZ    0x00000334
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_HZ     0x00000335
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITLIMIT       0x00000336
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITLIMIT_DBM   0x00000337
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_RETURN          0x00000338
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_RETURN                    0x00000339
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT                           0x0000033A
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_FIRSTPAGE                 0x0000033B
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_PREVPAGE                  0x0000033C
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_NEXTPAGE                  0x0000033D
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_LASTPAGE                  0x0000033E
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION                 0x0000033F
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_ADD             0x00000340
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_INSERT          0x00000341
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_DELETE          0x00000342
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_CLEAR           0x00000343
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ        0x00000344
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_GHZ    0x00000345
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_MHZ    0x00000346
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_KHZ    0x00000347
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_HZ     0x00000348
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITLIMIT       0x00000349
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITLIMIT_DBM   0x0000034A
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_RETURN          0x0000034B
#define KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_RETURN                    0x0000034C
#define KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY                             0x0000034D
#define KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_GHZ                         0x0000034E
#define KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_MHZ                         0x0000034F
#define KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_KHZ                         0x00000350
#define KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_HZ                          0x00000351
#define KEY_FUNC_AMPT_PASSFAIL_LINE_RETURN                              0x00000352
#define KEY_FUNC_AMPT_PASSFAIL_RETURN                                   0x00000353

#define KEY_FUNC_AUTO_AUTO                      0x00000400

#define KEY_FUNC_BW_RBW                         0x00000500
#define KEY_FUNC_BW_RBW_GHZ                     0x00000501
#define KEY_FUNC_BW_RBW_MHZ                     0x00000502
#define KEY_FUNC_BW_RBW_KHZ                     0x00000503
#define KEY_FUNC_BW_RBW_HZ                      0x00000504
#define KEY_FUNC_BW_RBWMODE                     0x00000505
#define KEY_FUNC_BW_VBW                         0x00000506
#define KEY_FUNC_BW_VBW_GHZ                     0x00000507
#define KEY_FUNC_BW_VBW_MHZ                     0x00000508
#define KEY_FUNC_BW_VBW_KHZ                     0x00000509
#define KEY_FUNC_BW_VBW_HZ                      0x0000050A
#define KEY_FUNC_BW_VBWMODE                     0x0000050B
#define KEY_FUNC_BW_AVERAGE                     0x0000050C
#define KEY_FUNC_BW_AVERAGE_ENTER               0x0000050D
#define KEY_FUNC_BW_EMC                         0x0000050E
#define KEY_FUNC_BW_EMC_EMC                     0x0000050F
#define KEY_FUNC_BW_EMC_VALUE       	        0x00000510
#define KEY_FUNC_BW_EMC_1MHZ       		        0x00000511
#define KEY_FUNC_BW_EMC_120KHZ      	        0x00000512
#define KEY_FUNC_BW_EMC_30KHZ        	        0x00000513
#define KEY_FUNC_BW_EMC_9KHZ      		        0x00000514
#define KEY_FUNC_BW_EMC_200HZ      		        0x00000515
#define KEY_FUNC_BW_EMC_RETURN     		        0x00000516
#define KEY_FUNC_BW_EMC_BLANK1      	        0x00000517
#define KEY_FUNC_BW_EMC_BLANK2      	        0x00000518
#define KEY_FUNC_BW_EMC_BLANK3      	        0x00000519
#define KEY_FUNC_BW_PREV        	            0x0000051A

#define KEY_FUNC_SWEEP_SWEEPTIME                0x00000600
#define KEY_FUNC_SWEEP_SWEEPTIME_S              0x00000601
#define KEY_FUNC_SWEEP_SWEEPTIME_MS             0x00000602
#define KEY_FUNC_SWEEP_SWEEPTIME_US             0x00000603
#define KEY_FUNC_SWEEP_SWEEPTIME_NS             0x00000604
#define KEY_FUNC_SWEEP_SWEEPMODE_SINGLE         0x00000605
#define KEY_FUNC_SWEEP_SWEEPMODE_CONTINUOUS     0x00000606
#define KEY_FUNC_SWEEP_SWEEPPOINTS              0x00000607
#define KEY_FUNC_SWEEP_SWEEPPOINTS_ENTER        0x00000608

#define KEY_FUNC_TRIG_AUTORUN                   0x00000700
#define KEY_FUNC_TRIG_VIDEO                     0x00000701
#define KEY_FUNC_TRIG_VIDEO_DBM                 0x00000702
#define KEY_FUNC_TRIG_EXTERNAL                  0x00000703
#define KEY_FUNC_TRIG_EXTERNAL_RISE             0x00000704
#define KEY_FUNC_TRIG_EXTERNAL_FALL             0x00000705
#define KEY_FUNC_TRIG_EXTERNAL_RETURN           0x00000706

#define KEY_FUNC_MEAS_MEASUREOFF                                        0x00000800
#define KEY_FUNC_MEAS_TIMESPEC                                          0x00000801
#define KEY_FUNC_MEAS_ACPR                                              0x00000802
#define KEY_FUNC_MEAS_CHANNELPOWER                                      0x00000803
#define KEY_FUNC_MEAS_OBW                                               0x00000804
#define KEY_FUNC_MEAS_DISCRIMINATOR                                     0x00000805
#define KEY_FUNC_MEAS_DISCRIMINATOR_DISCRIMINATOR                       0x00000806
#define KEY_FUNC_MEAS_DISCRIMINATOR_NORMALIZE                           0x00000807
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE                           0x00000808
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OUTPUTPOWER               0x00000809
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OUTPUTPOWER_ENTER         0x0000080A
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN                 0x0000080B
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X1              0x0000080C
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X2              0x0000080D
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X4              0x0000080E
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X05             0x0000080F
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X025            0x00000810
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_RETURN          0x00000811
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_SCALEDIV                  0x00000812
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_SCALEDIV_ENTER            0x00000813
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OFFSET                    0x00000814
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OFFSET_ENTER              0x00000815
#define KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_RETURN                    0x00000816
#define KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME                           0x00000817
#define KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_S                         0x00000818
#define KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_MS                        0x00000819
#define KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_US                        0x0000081A
#define KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_NS                        0x0000081B
#define KEY_FUNC_MEAS_DISCRIMINATOR_RETURN                              0x0000081C
#define KEY_FUNC_MEAS_EMC                                               0x00000820

#define KEY_FUNC_MEASSETUP_CHANNELWIDTH         						0x00000C00
#define KEY_FUNC_MEASSETUP_CHANNELWIDTH_GHZ     						0x00000C01
#define KEY_FUNC_MEASSETUP_CHANNELWIDTH_MHZ     						0x00000C02
#define KEY_FUNC_MEASSETUP_CHANNELWIDTH_KHZ     						0x00000C03
#define KEY_FUNC_MEASSETUP_CHANNELWIDTH_HZ      						0x00000C04
#define KEY_FUNC_MEASSETUP_CHANNELINTERVAL      						0x00000C05
#define KEY_FUNC_MEASSETUP_CHANNELINTERVAL_GHZ  						0x00000C06
#define KEY_FUNC_MEASSETUP_CHANNELINTERVAL_MHZ  						0x00000C07
#define KEY_FUNC_MEASSETUP_CHANNELINTERVAL_KHZ  						0x00000C08
#define KEY_FUNC_MEASSETUP_CHANNELINTERVAL_HZ   						0x00000C09
#define KEY_FUNC_MEASSETUP_CHANNELNUMS          						0x00000C0A
#define KEY_FUNC_MEASSETUP_CHANNELNUMS_ENTER    						0x00000C0B
#define KEY_FUNC_MEASSETUP_POWERBWPERCENT       						0x00000C0C
#define KEY_FUNC_MEASSETUP_POWERBWPERCENT_ENTER 						0x00000C0D

#define KEY_FUNC_TRACE_TRACE                    0x00000900
#define KEY_FUNC_TRACE_CLEARWRITE               0x00000901
#define KEY_FUNC_TRACE_MAXHOLD                  0x00000902
#define KEY_FUNC_TRACE_MINHOLD                  0x00000903
#define KEY_FUNC_TRACE_VIEW                     0x00000904
#define KEY_FUNC_TRACE_BLANK                    0x00000905
#define KEY_FUNC_TRACE_OPERATIONS               0x00000906
#define KEY_FUNC_TRACE_OPERATIONS_12            0x00000907
#define KEY_FUNC_TRACE_OPERATIONS_2DLTO2        0x00000908
#define KEY_FUNC_TRACE_OPERATIONS_23            0x00000909
#define KEY_FUNC_TRACE_OPERATIONS_1TO3          0x0000090A
#define KEY_FUNC_TRACE_OPERATIONS_2TO3          0x0000090B
#define KEY_FUNC_TRACE_OPERATIONS_RETURN        0x0000090C

#define KEY_FUNC_DETECTOR_AUTO                  0x00000A00
#define KEY_FUNC_DETECTOR_NORMAL                0x00000A01
#define KEY_FUNC_DETECTOR_POSPEAK               0x00000A02
#define KEY_FUNC_DETECTOR_NEGPEAK               0x00000A03
#define KEY_FUNC_DETECTOR_SAMPLE                0x00000A04
#define KEY_FUNC_DETECTOR_TRANSIENT             0x00000A05

#define KEY_FUNC_DISPLAY_FULLSCREEN             0x00000B00
#define KEY_FUNC_DISPLAY_ZOOM                   0x00000B01
#define KEY_FUNC_DISPLAY_DISPLAYLINE            0x00000B02
#define KEY_FUNC_DISPLAY_DISPLAYLINE_DBM        0x00000B03
#define KEY_FUNC_DISPLAY_REFSCALE               0x00000B04
#define KEY_FUNC_DISPLAY_GRID                   0x00000B05
#define KEY_FUNC_DISPLAY_LABEL                  0x00000B06
#define KEY_FUNC_DISPLAY_STYLE                  0x00000B07
#define KEY_FUNC_DISPLAY_STYLE_DEFAULT          0x00000B08
#define KEY_FUNC_DISPLAY_STYLE_STYLE1           0x00000B09
#define KEY_FUNC_DISPLAY_STYLE_STYLE2           0x00000B0A
#define KEY_FUNC_DISPLAY_STYLE_STYLE3           0x00000B0B
#define KEY_FUNC_DISPLAY_STYLE_STYLE4           0x00000B0C
#define KEY_FUNC_DISPLAY_STYLE_STYLE5           0x00000B0D
#define KEY_FUNC_DISPLAY_STYLE_RETURN           0x00000B0E

#define KEY_FUNC_MARKER_MARKER                             0x00000D00
#define KEY_FUNC_MARKER_TRACE                              0x00000D01
#define KEY_FUNC_MARKER_NORMAL                             0x00000D02
#define KEY_FUNC_MARKER_NORMAL_GHZ                         0x00000D03
#define KEY_FUNC_MARKER_NORMAL_MHZ                         0x00000D04
#define KEY_FUNC_MARKER_NORMAL_KHZ                         0x00000D05
#define KEY_FUNC_MARKER_NORMAL_HZ                          0x00000D06
#define KEY_FUNC_MARKER_DELTA                              0x00000D07
#define KEY_FUNC_MARKER_DELTA_GHZ                          0x00000D08
#define KEY_FUNC_MARKER_DELTA_MHZ                          0x00000D09
#define KEY_FUNC_MARKER_DELTA_KHZ                          0x00000D0A
#define KEY_FUNC_MARKER_DELTA_HZ                           0x00000D0B
#define KEY_FUNC_MARKER_OFF                                0x00000D0C
#define KEY_FUNC_MARKER_ALLOFF                             0x00000D0D
#define KEY_FUNC_MARKER_LIST                               0x00000D0E

#define KEY_FUNC_MARKERFCTN                                0x00000D10
#define KEY_FUNC_MARKERFCTN_OFF                            0x00000E00
#define KEY_FUNC_MARKERFCTN_NDB                            0x00000E01
#define KEY_FUNC_MARKERFCTN_NDB_ENTER                      0x00000E02
#define KEY_FUNC_MARKERFCTN_NOISE                          0x00000E03
#define KEY_FUNC_MARKERFCTN_FREQCOUNT                      0x00000E04
#define KEY_FUNC_MARKERFCTN_FREQCOUNT_FREQCOUNT            0x00000E05
#define KEY_FUNC_MARKERFCTN_FREQCOUNT_BW                   0x00000E06
#define KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_GHZ               0x00000E07
#define KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_MHZ               0x00000E08
#define KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_KHZ               0x00000E09
#define KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_HZ                0x00000E0A
#define KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_RETURN            0x00000E0B
#define KEY_FUNC_MARKERFCTN_FREQCOUNT_RETURN               0x00000E12

#define KEY_FUNC_MARKERTO_CENTER                           0x00000F00
#define KEY_FUNC_MARKERTO_CFSTEP                           0x00000F01
#define KEY_FUNC_MARKERTO_START                            0x00000F02
#define KEY_FUNC_MARKERTO_STOP                             0x00000F03
#define KEY_FUNC_MARKERTO_REFLEVEL                         0x00000F04
#define KEY_FUNC_MARKERTO_DELTATOSPAN                      0x00000F05
#define KEY_FUNC_MARKERTO_DELTATOCF                        0x00000F06

#define KEY_FUNC_PEAK_MAXSEARCH                            0x00001000
#define KEY_FUNC_PEAK_NEXTPEAK                             0x00001001
#define KEY_FUNC_PEAK_LEFTPEAK                             0x00001002
#define KEY_FUNC_PEAK_RIGHTPEAK                            0x00001003
#define KEY_FUNC_PEAK_MINSEARCH                            0x00001004
#define KEY_FUNC_PEAK_MKRTOCF                              0x00001005
#define KEY_FUNC_PEAK_AUTOMAXSEARCH                        0x00001006

#define KEY_FUNC_SYSTEM_SYSTEM                             0x00001100
#define KEY_FUNC_SYSTEM_SYSTEM_INFO                        0x00001101
#define KEY_FUNC_SYSTEM_SYSTEM_LOG                         0x00001102
#define KEY_FUNC_SYSTEM_SYSTEM_RETURN                      0x00001103
#define KEY_FUNC_SYSTEM_CONFIGIO                           0x00001104
#define KEY_FUNC_SYSTEM_CONFIGIO_LAN                       0x00001105
#define KEY_FUNC_SYSTEM_CONFIGIO_LAN_IP                    0x00001106
#define KEY_FUNC_SYSTEM_CONFIGIO_LAN_IP_ENTER              0x00001107
#define KEY_FUNC_SYSTEM_CONFIGIO_LAN_MASK                  0x00001108
#define KEY_FUNC_SYSTEM_CONFIGIO_LAN_MASK_ENTER            0x00001109
#define KEY_FUNC_SYSTEM_CONFIGIO_LAN_GATE                  0x0000110A
#define KEY_FUNC_SYSTEM_CONFIGIO_LAN_GATE_ENTER            0x0000110B
#define KEY_FUNC_SYSTEM_CONFIGIO_LAN_RETURN                0x0000110C
#define KEY_FUNC_SYSTEM_CONFIGIO_LAN_RESET                 0x0000110D
#define KEY_FUNC_SYSTEM_CONFIGIO_GPIB                      0x0000110E
#define KEY_FUNC_SYSTEM_CONFIGIO_GPIB_ADDR                 0x0000110F
#define KEY_FUNC_SYSTEM_CONFIGIO_GPIB_ADDR_ENTER           0x00001110
#define KEY_FUNC_SYSTEM_CONFIGIO_GPIB_RETURN               0x00001111
#define KEY_FUNC_SYSTEM_CONFIGIO_COM                       0x00001112
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE              0x00001113
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_1200         0x00001114
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_2400         0x00001115
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_4800         0x00001116
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_9600         0x00001117
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_19200        0x00001118
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_38400        0x00001119
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_57600        0x0000111A
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_115200       0x0000111B
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_RETURN       0x0000111C
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS              0x0000111D
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_5            0x0000111E
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_6            0x0000111F
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_7            0x00001120
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_8            0x00001121
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_RETURN       0x00001122
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS              0x00001123
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS_1            0x00001124
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS_2            0x00001125
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS_RETURN       0x00001126
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK                 0x00001127
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_EVEN            0x00001128
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_ODD             0x00001129
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_NONE            0x0000112A
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_SPACE           0x0000112B
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_RETURN          0x0000112C
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL           0x0000112D
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_XONXOFF   0x0000112E
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_HARDWARE  0x0000112F
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_NONE      0x00001130
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_RETURN    0x00001131
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_RESET                 0x00001132
#define KEY_FUNC_SYSTEM_CONFIGIO_COM_RETURN                0x00001133
#define KEY_FUNC_SYSTEM_CONFIGIO_RETURN                    0x00001134
#define KEY_FUNC_SYSTEM_POWERONPRESET                      0x00001135
#define KEY_FUNC_SYSTEM_POWERONPRESET_POWERON              0x00001136
#define KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_FACTORY      0x00001137
#define KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_USER         0x00001138
#define KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_POWEROFF     0x00001139
#define KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_RETURN       0x0000113A
#define KEY_FUNC_SYSTEM_POWERONPRESET_PRESET               0x0000113B
#define KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_FACTORY       0x0000113C
#define KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_USER          0x0000113D
#define KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_POWEROFF      0x0000113E
#define KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_RETURN        0x0000113F
#define KEY_FUNC_SYSTEM_POWERONPRESET_RETURN               0x00001140
#define KEY_FUNC_SYSTEM_LANGUAGE                           0x00001141
#define KEY_FUNC_SYSTEM_LANGUAGE_CHINESE                   0x00001142
#define KEY_FUNC_SYSTEM_LANGUAGE_ENGLISH                   0x00001143
#define KEY_FUNC_SYSTEM_LANGUAGE_RETURN                    0x00001144
#define KEY_FUNC_SYSTEM_DATETIME                           0x00001145
#define KEY_FUNC_SYSTEM_DATETIME_DATETIME                  0x00001146
#define KEY_FUNC_SYSTEM_DATETIME_FORMAT                    0x00001147
#define KEY_FUNC_SYSTEM_DATETIME_FORMAT_YMDHMS             0x00001148
#define KEY_FUNC_SYSTEM_DATETIME_FORMAT_HMSYMD             0x00001149
#define KEY_FUNC_SYSTEM_DATETIME_FORMAT_RETURN             0x0000114A
#define KEY_FUNC_SYSTEM_DATETIME_DATE                      0x0000114B
#define KEY_FUNC_SYSTEM_DATETIME_DATE_ENTER                0x0000114C
#define KEY_FUNC_SYSTEM_DATETIME_TIME                      0x0000114D
#define KEY_FUNC_SYSTEM_DATETIME_TIME_ENTER                0x0000114E
#define KEY_FUNC_SYSTEM_DATETIME_RETURN                    0x0000114F
#define KEY_FUNC_SYSTEM_BACKLIGHT                          0x00001150
#define KEY_FUNC_SYSTEM_BACKLIGHT_ENTER                    0x00001151
#define KEY_FUNC_SYSTEM_NEXTPAGE                           0x00001152
#define KEY_FUNC_SYSTEM_CHANNELSELECT                      0x00001153
#define KEY_FUNC_SYSTEM_CALIBRATION                        0x00001154
#define KEY_FUNC_SYSTEM_CALIBRATION_CALIBRATION            0x00001155
#define KEY_FUNC_SYSTEM_CALIBRATION_FACTORY                0x00001156
#define KEY_FUNC_SYSTEM_CALIBRATION_RETURN                 0x00001157
#define KEY_FUNC_SYSTEM_SERVICE                            0x00001158
#define KEY_FUNC_SYSTEM_SERVICE_SERIALNO                   0x00001159
#define KEY_FUNC_SYSTEM_SERVICE_LANMACADDR                 0x0000115A
#define KEY_FUNC_SYSTEM_SERVICE_SERIALNO_ENTER             0x0000115B
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION                0x0000115C
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_DELETE         0x0000115D
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT           0x0000115E
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_9K        0x0000115F
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_9K_ENTER  0x00001160
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_9K_RESET  0x00001161
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_20K       0x00001162
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_20K_ENTER 0x00001163
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_20K_RESET 0x00001164
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_RETURN    0x00001165
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_CALIBRATION    0x00001166
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_PRECALIBRATION 0x00001167
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_RETURN         0x00001168
#define KEY_FUNC_SYSTEM_SERVICE_CLEAR_LOGDATA              0x00001169
#define KEY_FUNC_SYSTEM_SERVICE_TRACK_SELECT               0x0000116A
#define KEY_FUNC_SYSTEM_SERVICE_OPTION                     0x0000116B
#define KEY_FUNC_SYSTEM_SERVICE_OPTION_FFT                 0x0000116C
#define KEY_FUNC_SYSTEM_SERVICE_OPTION_AMFM                0x0000116D
#define KEY_FUNC_SYSTEM_SERVICE_OPTION_DIRECTCHANNEL       0x0000116E
#define KEY_FUNC_SYSTEM_SERVICE_OPTION_RETURN              0x0000116F
#define KEY_FUNC_SYSTEM_SERVICE_DEVICE                     0x00001170
#define KEY_FUNC_SYSTEM_SERVICE_DEVICE_TIMESELECT          0x00001171
#define KEY_FUNC_SYSTEM_SERVICE_DEVICE_RETURN              0x00001172
#define KEY_FUNC_SYSTEM_SERVICE_DEVICE_LOGDISPLAY          0x00001173
#define KEY_FUNC_SYSTEM_SERVICE_DEVICE_GPIB                0x00001174
#define KEY_FUNC_SYSTEM_SERVICE_EVALUATE                   0x00001175
#define KEY_FUNC_SYSTEM_SERVICE_RETURN                     0x00001176
#define KEY_FUNC_SYSTEM_SCPI_SCREENREFRESH                 0x00001177
#define KEY_FUNC_SYSTEM_NEXTPAGE_RETURN                    0x00001178
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_MODE           0x00001179
#define KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_LFCALIBRATION  0x0000117A

//file
#define KEY_FUNC_FILE_REFRESH                              0x00001200
#define KEY_FUNC_FILE_SHOW                                 0x00001201
#define KEY_FUNC_FILE_SHOW_SCREENS                         0x00001202
#define KEY_FUNC_FILE_SHOW_TRACEDATAS                      0x00001203
#define KEY_FUNC_FILE_SHOW_ALL                             0x00001204
#define KEY_FUNC_FILE_SHOW_RETURN                          0x00001205
#define KEY_FUNC_FILE_CATALOG                              0x00001221
#define KEY_FUNC_FILE_FIRSTPAGE                            0x00001206
#define KEY_FUNC_FILE_PREVPAGE                             0x00001207
#define KEY_FUNC_FILE_NEXTPAGE                             0x00001208
#define KEY_FUNC_FILE_LASTPAGE                             0x00001209
#define KEY_FUNC_FILE_OPERATIONS                           0x0000120A
#define KEY_FUNC_FILE_OPERATIONS_SORT                      0x0000120B
#define KEY_FUNC_FILE_OPERATIONS_SORT_NAME                 0x0000120C
#define KEY_FUNC_FILE_OPERATIONS_SORT_DATETIME             0x0000120D
#define KEY_FUNC_FILE_OPERATIONS_SORT_SIZE                 0x0000120E
#define KEY_FUNC_FILE_OPERATIONS_SORT_RETURN               0x0000120F
#define KEY_FUNC_FILE_OPERATIONS_DELETE                    0x00001210
#define KEY_FUNC_FILE_OPERATIONS_DELETE_SELECT             0x00001211
#define KEY_FUNC_FILE_OPERATIONS_DELETE_PAGE               0x00001212
#define KEY_FUNC_FILE_OPERATIONS_DELETE_ALL                0x00001213
#define KEY_FUNC_FILE_OPERATIONS_DELETE_RETURN             0x00001214
#define KEY_FUNC_FILE_OPERATIONS_COPY                      0x00001215
#define KEY_FUNC_FILE_OPERATIONS_COPY_SELECT_TOUSB         0x00001216
#define KEY_FUNC_FILE_OPERATIONS_COPY_PAGE_TOUSB           0x00001217
#define KEY_FUNC_FILE_OPERATIONS_COPY_ALL_TOUSB            0x00001218
#define KEY_FUNC_FILE_OPERATIONS_COPY_RETURN               0x00001219
#define KEY_FUNC_FILE_OPERATIONS_LOAD                      0x0000121A
#define KEY_FUNC_FILE_OPERATIONS_RETURN                    0x0000121B

//save
#define KEY_FUNC_SAVE_SCEEEN                               0x00001300
#define KEY_FUNC_SAVE_SCEEEN_TOLOCAL                       0x00001301
#define KEY_FUNC_SAVE_SCEEEN_TOUSB                         0x00001302
#define KEY_FUNC_SAVE_SCEEEN_RETURN                        0x00001303
#define KEY_FUNC_SAVE_TRACE                                0x00001304
#define KEY_FUNC_SAVE_TRACE_TOLOCAL                        0x00001305
#define KEY_FUNC_SAVE_TRACE_TOUSB                          0x00001306
#define KEY_FUNC_SAVE_TRACE_RETURN                         0x00001307
#define KEY_FUNC_SAVE_USER                                 0x00001308
#define KEY_FUNC_SAVE_LOAD                                 0x00001309
#define KEY_FUNC_SAVE_LOAD_USER1                           0x0000130A
#define KEY_FUNC_SAVE_LOAD_USER2                           0x0000130B
#define KEY_FUNC_SAVE_LOAD_USER3                           0x0000130C
#define KEY_FUNC_SAVE_LOAD_USER4                           0x0000130D
#define KEY_FUNC_SAVE_LOAD_USER5                           0x0000130E
#define KEY_FUNC_SAVE_LOAD_USER6                           0x0000130F
#define KEY_FUNC_SAVE_LOAD_NEXTPAGE                        0x00001310
#define KEY_FUNC_SAVE_LOAD_USER7                           0x00001311
#define KEY_FUNC_SAVE_LOAD_USER8                           0x00001312
#define KEY_FUNC_SAVE_LOAD_USER9                           0x00001313
#define KEY_FUNC_SAVE_LOAD_USER10                          0x00001314
#define KEY_FUNC_SAVE_LOAD_RETURN                          0x00001315
#define KEY_FUNC_SAVE_SAVE                                 0x00001316
#define KEY_FUNC_SAVE_SAVE_USER1                           0x00001317
#define KEY_FUNC_SAVE_SAVE_USER2                           0x00001318
#define KEY_FUNC_SAVE_SAVE_USER3                           0x00001319
#define KEY_FUNC_SAVE_SAVE_USER4                           0x0000131A
#define KEY_FUNC_SAVE_SAVE_USER5                           0x0000131B
#define KEY_FUNC_SAVE_SAVE_USER6                           0x0000131C
#define KEY_FUNC_SAVE_SAVE_NEXTPAGE                        0x0000131D
#define KEY_FUNC_SAVE_SAVE_USER7                           0x0000131E
#define KEY_FUNC_SAVE_SAVE_USER8                           0x0000131F
#define KEY_FUNC_SAVE_SAVE_USER9                           0x00001320
#define KEY_FUNC_SAVE_SAVE_USER10                          0x00001321
#define KEY_FUNC_SAVE_SAVE_RETURN                          0x00001322
#define KEY_FUNC_SAVE_CLEAR                                0x00001323
#define KEY_FUNC_SAVE_CLEAR_USER1                          0x00001324
#define KEY_FUNC_SAVE_CLEAR_USER2                          0x00001325
#define KEY_FUNC_SAVE_CLEAR_USER3                          0x00001326
#define KEY_FUNC_SAVE_CLEAR_USER4                          0x00001327
#define KEY_FUNC_SAVE_CLEAR_USER5                          0x00001328
#define KEY_FUNC_SAVE_CLEAR_USER6                          0x00001329
#define KEY_FUNC_SAVE_CLEAR_NEXTPAGE                       0x0000132A
#define KEY_FUNC_SAVE_CLEAR_USER7                          0x0000132B
#define KEY_FUNC_SAVE_CLEAR_USER8                          0x0000132C
#define KEY_FUNC_SAVE_CLEAR_USER9                          0x0000132D
#define KEY_FUNC_SAVE_CLEAR_USER10                         0x0000132E
#define KEY_FUNC_SAVE_CLEAR_RETURN                         0x0000132F
#define KEY_FUNC_SAVE_CLEAR_ALL                            0x00001330

//Source
#define KEY_FUNC_SOURCE_TRACKGEN                           0x00001400
#define KEY_FUNC_SOURCE_TRACKGEN_TRACKGEN                  0x00001401
#define KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE                  0x00001402
#define KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE_S21              0x00001403
#define KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE_S11              0x00001404
#define KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE_RETURN           0x00001409
#define KEY_FUNC_SOURCE_TRACKGEN_POWER                     0x0000140A
#define KEY_FUNC_SOURCE_TRACKGEN_POWER_ENTER               0x0000140B
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK                   0x0000140C
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_NETWORK           0x0000140D
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_NORMALIZE         0x0000140E
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_REFLEVEL          0x0000140F
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_REFLEVEL_ENTER    0x00001410
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_POWER             0x00001411
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_POWER_ENTER       0x00001412
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPPOINT        0x00001413
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPPOINT_ENTER  0x00001414
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME         0x00001415
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_S       0x00001416
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_MS      0x00001417
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_US      0x00001418
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_NS      0x00001419
#define KEY_FUNC_SOURCE_TRACKGEN_NETWORK_RETURN            0x0000141A
#define KEY_FUNC_SOURCE_TRACKGEN_VSWR                      0x0000141B
#define KEY_FUNC_SOURCE_TRACKGEN_VSWR_VSWR                 0x0000141C
#define KEY_FUNC_SOURCE_TRACKGEN_VSWR_NORMALIZE            0x0000141D
#define KEY_FUNC_SOURCE_TRACKGEN_VSWR_REFERENCE            0x0000141E
#define KEY_FUNC_SOURCE_TRACKGEN_VSWR_REFERENCE_ENTER      0x0000141F
#define KEY_FUNC_SOURCE_TRACKGEN_VSWR_RETURN               0x00001420
#define KEY_FUNC_SOURCE_TRACKGEN_RETURN                    0x00001421
#define KEY_FUNC_SOURCE_SIGNALGEN                          0x00001422
#define KEY_FUNC_SOURCE_SIGNALGEN_SIGNALGEN                0x00001423
#define KEY_FUNC_SOURCE_SIGNALGEN_FREQ                     0x00001424
#define KEY_FUNC_SOURCE_SIGNALGEN_FREQ_GHZ                 0x00001425
#define KEY_FUNC_SOURCE_SIGNALGEN_FREQ_MHZ                 0x00001426
#define KEY_FUNC_SOURCE_SIGNALGEN_FREQ_KHZ                 0x00001427
#define KEY_FUNC_SOURCE_SIGNALGEN_FREQ_HZ                  0x00001428
#define KEY_FUNC_SOURCE_SIGNALGEN_POWER                    0x00001429
#define KEY_FUNC_SOURCE_SIGNALGEN_POWER_ENTER              0x0000142A
#define KEY_FUNC_SOURCE_SIGNALGEN_RETURN                   0x0000142B

#define KEY_FUNC_PRINTSETUP_PAPER                          0x00001600
#define KEY_FUNC_PRINTSETUP_PAPER_A4                       0x00001601
#define KEY_FUNC_PRINTSETUP_PAPER_A3                       0x00001602
#define KEY_FUNC_PRINTSETUP_PAPER_B5                       0x00001603
#define KEY_FUNC_PRINTSETUP_PAPER_C5                       0x00001604
#define KEY_FUNC_PRINTSETUP_PAPER_LETTER                   0x00001605
#define KEY_FUNC_PRINTSETUP_PAPER_RETURN                   0x00001606
#define KEY_FUNC_PRINTSETUP_LANGUAGE                       0x00001607
#define KEY_FUNC_PRINTSETUP_COLOR                          0x00001608
#define KEY_FUNC_PRINTSETUP_ORIENTATION                    0x00001609
#define KEY_FUNC_PRINTSETUP_NUMS                           0x0000160A
#define KEY_FUNC_PRINTSETUP_NUMS_ENTER                     0x0000160B
#define KEY_FUNC_PRINTSETUP_PRINTTRACE                     0x0000160C
#define KEY_FUNC_PRINTSETUP_PRINTSCREEN                    0x0000160D

#define KEY_FUNC_DEMOD_DEMOD                                0x00001701
#define KEY_FUNC_DEMOD_SOUND                                0x00001702
#define KEY_FUNC_DEMOD_SOUND_ENTER                          0x00001703
#define KEY_FUNC_DEMOD_RADIOSET                             0x00001704
#define KEY_FUNC_DEMOD_RADIOSET_1                           0x00001705
#define KEY_FUNC_DEMOD_RADIOSET_1_GHZ                       0x00001706
#define KEY_FUNC_DEMOD_RADIOSET_1_MHZ                       0x00001707
#define KEY_FUNC_DEMOD_RADIOSET_1_KHZ                       0x00001708
#define KEY_FUNC_DEMOD_RADIOSET_1_HZ                        0x0000170A
#define KEY_FUNC_DEMOD_RADIOSET_MUSIC                       0x0000170B
#define KEY_FUNC_DEMOD_RADIOSET_MUSIC_GHZ                   0x0000170C
#define KEY_FUNC_DEMOD_RADIOSET_MUSIC_MHZ                   0x0000170D
#define KEY_FUNC_DEMOD_RADIOSET_MUSIC_KHZ                   0x0000170E
#define KEY_FUNC_DEMOD_RADIOSET_MUSIC_HZ                    0x0000170F
#define KEY_FUNC_DEMOD_RADIOSET_TRAFFIC                     0x00001710
#define KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_GHZ                 0x00001711
#define KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_MHZ                 0x00001712
#define KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_KHZ                 0x00001713
#define KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_HZ                  0x00001714
#define KEY_FUNC_DEMOD_RADIOSET_2                           0x00001715
#define KEY_FUNC_DEMOD_RADIOSET_2_GHZ                       0x00001716
#define KEY_FUNC_DEMOD_RADIOSET_2_MHZ                       0x00001717
#define KEY_FUNC_DEMOD_RADIOSET_2_KHZ                       0x00001718
#define KEY_FUNC_DEMOD_RADIOSET_2_HZ                        0x00001719
#define KEY_FUNC_DEMOD_RADIOSET_3                           0x0000171A
#define KEY_FUNC_DEMOD_RADIOSET_3_GHZ                       0x0000171B
#define KEY_FUNC_DEMOD_RADIOSET_3_MHZ                       0x0000171C
#define KEY_FUNC_DEMOD_RADIOSET_3_KHZ                       0x0000171D
#define KEY_FUNC_DEMOD_RADIOSET_3_HZ                        0x0000171E
#define KEY_FUNC_DEMOD_RADIOSET_4                           0x0000171F
#define KEY_FUNC_DEMOD_RADIOSET_4_GHZ                       0x00001720
#define KEY_FUNC_DEMOD_RADIOSET_4_MHZ                       0x00001721
#define KEY_FUNC_DEMOD_RADIOSET_4_KHZ                       0x00001722
#define KEY_FUNC_DEMOD_RADIOSET_4_HZ                        0x00001723
#define KEY_FUNC_DEMOD_RADIOSET_RETURN                      0x00001724
#define KEY_FUNC_DEMOD_RETURN                               0x00001725

//AM FM
#define KEY_FUNC_MODE_OPTIONS_DEMOD                        0x00001800
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AUDIO                  0x00001801
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM                     0x00001802
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_AM                  0x00001803
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ         0x00001804
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_GHZ     0x00001805
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_MHZ     0x00001806
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_KHZ     0x00001807
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_HZ      0x00001808
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW                0x00001809
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_GHZ            0x0000180A
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_MHZ            0x0000180B
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_KHZ            0x0000180C
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_HZ             0x0000180D
#define KEY_FUNC_MODE_OPTIONS_DEMOD_AM_RETURN              0x0000180E
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM                     0x0000180F
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_FM                  0x00001810
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ         0x00001811
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_GHZ     0x00001812
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_MHZ     0x00001813
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_KHZ     0x00001814
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_HZ      0x00001815
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW                0x00001816
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_GHZ            0x00001817
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_MHZ            0x00001818
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_KHZ            0x00001819
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_HZ             0x0000181A
#define KEY_FUNC_MODE_OPTIONS_DEMOD_FM_RETURN              0x0000181B
#define KEY_FUNC_MODE_OPTIONS_DEMOD_RETRURN                0x0000181C

#define KEY_FUNC_AUX_IMPEDANCE_CONVERSION                  0x00001750
#define KEY_FUNC_AUX_SELF_CHECK                            0x00001751
#define KEY_FUNC_AUX_SELF_CHECK_POWER                      0x00001752
#define KEY_FUNC_AUX_SELF_CHECK_CONTROL                    0x00001753
#define KEY_FUNC_AUX_SELF_CHECK_IF                         0x00001754
#define KEY_FUNC_AUX_SELF_CHECK_RF                         0x00001755
#define KEY_FUNC_AUX_SELF_CHECK_RETURN                     0x00001756
#define KEY_FUNC_AUX_IMPEDANCE_CONVERSION_ENTER            0x00001757
#define KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE              0x0000181D
#define KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_FMW          0x0000181E
#define KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_FM           0x0000181F
#define KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_AM           0x00001820
#define KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_USB          0x00001821
#define KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_LSB          0x00001822
#define KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_RETURN       0x00001823
#define KEY_FUNC_MODE_OPTIONS_DIGITAL_DEMOD                0x00001824
#define KEY_FUNC_MODE_OPTIONS_DIGITAL_DEMOD_RETURN         0x00001825


//impedance conversion

//****************************************
//* 系统对应关系定义
//****************************************
struct valueListDef
{
  char* name;
  int value;
};

static struct valueListDef valueList[] =
{
  {"KEY_SUB_MENU1", KEY_SUB_MENU1},
  {"KEY_SUB_MENU2", KEY_SUB_MENU2},
  {"KEY_SUB_MENU3", KEY_SUB_MENU3},
  {"KEY_SUB_MENU4", KEY_SUB_MENU4},
  {"KEY_SUB_MENU5", KEY_SUB_MENU5},
  {"KEY_SUB_MENU6", KEY_SUB_MENU6},
  {"KEY_SUB_MENU7", KEY_SUB_MENU7},

  {"KEY_MAIN_FREQ", KEY_MAIN_FREQ},
  {"KEY_MAIN_SPAN", KEY_MAIN_SPAN},
  {"KEY_MAIN_AMPT", KEY_MAIN_AMPT},
  {"KEY_MAIN_TUNE", KEY_MAIN_TUNE},

  {"KEY_MAIN_BW",    KEY_MAIN_BW},
  {"KEY_MAIN_TRACE", KEY_MAIN_TRACE},
  {"KEY_MAIN_TRIG",  KEY_MAIN_TRIG},
  {"KEY_MAIN_MEAS",  KEY_MAIN_MEAS},

  {"KEY_MAIN_SWEEP",     KEY_MAIN_SWEEP},
  {"KEY_MAIN_DETECTOR",  KEY_MAIN_DETECTOR},
  {"KEY_MAIN_DISPLAY",   KEY_MAIN_DISPLAY},
  {"KEY_MAIN_MEASSETUP", KEY_MAIN_MEASSETUP},

  {"KEY_MAIN_MARKER",     KEY_MAIN_MARKER},
  {"KEY_MAIN_MARKERFCTN", KEY_MAIN_MARKERFCTN},
  {"KEY_MAIN_MARKERTO",   KEY_MAIN_MARKERTO},
  {"KEY_MAIN_PEAK",       KEY_MAIN_PEAK},

  {"KEY_MAIN_SYSTEM", KEY_MAIN_SYSTEM},
  {"KEY_MAIN_FILE",   KEY_MAIN_FILE},
  {"KEY_MAIN_SAVE",   KEY_MAIN_SAVE},
  {"KEY_MAIN_SOURCE", KEY_MAIN_SOURCE},

  {"KEY_MAIN_PRESET", KEY_MAIN_PRESET},
  {"KEY_MAIN_PRINT",  KEY_MAIN_PRINT},
  {"KEY_MAIN_HELP",   KEY_MAIN_HELP},
  {"KEY_MAIN_DEMOD",  KEY_MAIN_DEMOD},
  {"KEY_MAIN_AUX",    KEY_MAIN_AUX},
};

//方向键集合
static int ARROWKEYLIST[] =
{
  KEY_ARROW_UP, KEY_ARROW_DOWN,\
};

//RPG键集合
static int RPGKEYLIST[] =
{
  KEY_ARROW_RPG,\
};

//主键集合
static int MAINKEYLIST[] =
{
  KEY_MAIN_FREQ, KEY_MAIN_SPAN, KEY_MAIN_AMPT,KEY_MAIN_TUNE, \
  KEY_MAIN_BW,KEY_MAIN_SWEEP, KEY_MAIN_TRIG,KEY_MAIN_MEAS,\
  KEY_MAIN_TRACE,KEY_MAIN_DETECTOR,KEY_MAIN_DISPLAY, KEY_MAIN_MEASSETUP, \
  KEY_MAIN_MARKER,KEY_MAIN_MARKERFCTN, KEY_MAIN_MARKERTO, KEY_MAIN_PEAK,\
  KEY_MAIN_SYSTEM, KEY_MAIN_FILE, KEY_MAIN_SAVE, KEY_MAIN_SOURCE,\
  KEY_MAIN_PRESET, KEY_MAIN_PRINT,KEY_MAIN_HELP,KEY_MAIN_DEMOD \
};

//通用键集合
static int COMMONKEYLIST[] =
{
  KEY_SUB_MENU1, KEY_SUB_MENU2, KEY_SUB_MENU3, KEY_SUB_MENU4,\
  KEY_SUB_MENU5, KEY_SUB_MENU6, KEY_SUB_MENU7,\
};

//数字键集合
static int NUMBERKEYLIST[] =
{
  KEY_NUM_0, KEY_NUM_1, KEY_NUM_2, KEY_NUM_3, KEY_NUM_4, \
  KEY_NUM_5, KEY_NUM_6, KEY_NUM_7, KEY_NUM_8, KEY_NUM_9, \
  KEY_NUM_DOT, KEY_NUM_NEG, \
};

//单位键集合
static int UNITKEYLIST[] =
{
  KEY_UNIT_GHZ, KEY_UNIT_MHZ, KEY_UNIT_KHZ, KEY_UNIT_HZ,\
};

//方向键集合

//功能码集合
static struct valueListDef codeList[] =
{
  {"KEY_FUNC_FREQ_CENTER", KEY_FUNC_FREQ_CENTER},
  {"KEY_FUNC_FREQ_CENTER_GHZ", KEY_FUNC_FREQ_CENTER_GHZ},
  {"KEY_FUNC_FREQ_CENTER_MHZ", KEY_FUNC_FREQ_CENTER_MHZ},
  {"KEY_FUNC_FREQ_CENTER_KHZ", KEY_FUNC_FREQ_CENTER_KHZ},
  {"KEY_FUNC_FREQ_CENTER_HZ", KEY_FUNC_FREQ_CENTER_HZ},
  {"KEY_FUNC_FREQ_START", KEY_FUNC_FREQ_START},
  {"KEY_FUNC_FREQ_START_GHZ", KEY_FUNC_FREQ_START_GHZ},
  {"KEY_FUNC_FREQ_START_MHZ", KEY_FUNC_FREQ_START_MHZ},
  {"KEY_FUNC_FREQ_START_KHZ", KEY_FUNC_FREQ_START_KHZ},
  {"KEY_FUNC_FREQ_START_HZ", KEY_FUNC_FREQ_START_HZ},
  {"KEY_FUNC_FREQ_STOP", KEY_FUNC_FREQ_STOP},
  {"KEY_FUNC_FREQ_STOP_GHZ", KEY_FUNC_FREQ_STOP_GHZ},
  {"KEY_FUNC_FREQ_STOP_MHZ", KEY_FUNC_FREQ_STOP_MHZ},
  {"KEY_FUNC_FREQ_STOP_KHZ", KEY_FUNC_FREQ_STOP_KHZ},
  {"KEY_FUNC_FREQ_STOP_HZ", KEY_FUNC_FREQ_STOP_HZ},
  {"KEY_FUNC_FREQ_CFSTEP", KEY_FUNC_FREQ_CFSTEP},
  {"KEY_FUNC_FREQ_CFSTEP_GHZ", KEY_FUNC_FREQ_CFSTEP_GHZ},
  {"KEY_FUNC_FREQ_CFSTEP_MHZ", KEY_FUNC_FREQ_CFSTEP_MHZ},
  {"KEY_FUNC_FREQ_CFSTEP_KHZ", KEY_FUNC_FREQ_CFSTEP_KHZ},
  {"KEY_FUNC_FREQ_CFSTEP_HZ", KEY_FUNC_FREQ_CFSTEP_HZ},
  {"KEY_FUNC_FREQ_OFFSET", KEY_FUNC_FREQ_OFFSET},
  {"KEY_FUNC_FREQ_OFFSET_GHZ", KEY_FUNC_FREQ_OFFSET_GHZ},
  {"KEY_FUNC_FREQ_OFFSET_MHZ", KEY_FUNC_FREQ_OFFSET_MHZ},
  {"KEY_FUNC_FREQ_OFFSET_KHZ", KEY_FUNC_FREQ_OFFSET_KHZ},
  {"KEY_FUNC_FREQ_OFFSET_HZ", KEY_FUNC_FREQ_OFFSET_HZ},
  {"KEY_FUNC_FREQ_REFERENCE", KEY_FUNC_FREQ_REFERENCE},
  {"KEY_FUNC_FREQ_LOW", KEY_FUNC_FREQ_LOW},
  {"KEY_FUNC_FREQ_NEXTPAGE", KEY_FUNC_FREQ_NEXTPAGE},
  {"KEY_FUNC_FREQ_SCALETYPE",KEY_FUNC_FREQ_SCALETYPE},
  {"KEY_FUNC_FREQ_NEXTPAGE_RETURN",KEY_FUNC_FREQ_NEXTPAGE_RETURN},

  {"KEY_FUNC_SPAN_SPAN", KEY_FUNC_SPAN_SPAN},
  {"KEY_FUNC_SPAN_SPAN_GHZ", KEY_FUNC_SPAN_SPAN_GHZ},
  {"KEY_FUNC_SPAN_SPAN_MHZ", KEY_FUNC_SPAN_SPAN_MHZ},
  {"KEY_FUNC_SPAN_SPAN_KHZ", KEY_FUNC_SPAN_SPAN_KHZ},
  {"KEY_FUNC_SPAN_SPAN_HZ", KEY_FUNC_SPAN_SPAN_HZ},
  {"KEY_FUNC_SPAN_FULL", KEY_FUNC_SPAN_FULL},
  {"KEY_FUNC_SPAN_ZERO", KEY_FUNC_SPAN_ZERO},
  {"KEY_FUNC_SPAN_LAST", KEY_FUNC_SPAN_LAST},

  {"KEY_FUNC_AMPT_REFLEVEL", KEY_FUNC_AMPT_REFLEVEL},
  {"KEY_FUNC_AMPT_REFLEVEL_DBM", KEY_FUNC_AMPT_REFLEVEL_DBM},
  {"KEY_FUNC_AMPT_ATT", KEY_FUNC_AMPT_ATT},
  {"KEY_FUNC_AMPT_ATT_DB", KEY_FUNC_AMPT_ATT_DB},
  {"KEY_FUNC_AMPT_SCALEDIV", KEY_FUNC_AMPT_SCALEDIV},
  {"KEY_FUNC_AMPT_SCALEDIV_DB", KEY_FUNC_AMPT_SCALEDIV_DB},
  {"KEY_FUNC_AMPT_SCALETYPE", KEY_FUNC_AMPT_SCALETYPE},
  {"KEY_FUNC_AMPT_REFOFFSET", KEY_FUNC_AMPT_REFOFFSET},
  {"KEY_FUNC_AMPT_REFOFFSET_DB", KEY_FUNC_AMPT_REFOFFSET_DB},
  {"KEY_FUNC_AMPT_REFUNIT", KEY_FUNC_AMPT_REFUNIT},
  {"KEY_FUNC_AMPT_REFUNIT_DBM", KEY_FUNC_AMPT_REFUNIT_DBM},
  {"KEY_FUNC_AMPT_REFUNIT_DBuW", KEY_FUNC_AMPT_REFUNIT_DBuW},
  {"KEY_FUNC_AMPT_REFUNIT_DBPW", KEY_FUNC_AMPT_REFUNIT_DBPW},
  {"KEY_FUNC_AMPT_REFUNIT_DBMV", KEY_FUNC_AMPT_REFUNIT_DBMV},
  {"KEY_FUNC_AMPT_REFUNIT_DBUV", KEY_FUNC_AMPT_REFUNIT_DBUV},
  {"KEY_FUNC_AMPT_REFUNIT_W", KEY_FUNC_AMPT_REFUNIT_W},
  {"KEY_FUNC_AMPT_REFUNIT_V", KEY_FUNC_AMPT_REFUNIT_V},
  {"KEY_FUNC_AMPT_PREAMPT", KEY_FUNC_AMPT_PREAMPT},

  {"KEY_FUNC_AMPT_PASSFAIL", KEY_FUNC_AMPT_PASSFAIL},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW", KEY_FUNC_AMPT_PASSFAIL_WINDOW},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_WINDOW", KEY_FUNC_AMPT_PASSFAIL_WINDOW_WINDOW},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_LIMITLINEON", KEY_FUNC_AMPT_PASSFAIL_WINDOW_LIMITLINEON},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQLINEON", KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQLINEON},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_LIMITUPLOW", KEY_FUNC_AMPT_PASSFAIL_WINDOW_LIMITUPLOW},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_LIMITUPLOW_DBM", KEY_FUNC_AMPT_PASSFAIL_WINDOW_LIMITUPLOW_DBM},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP", KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_GHZ", KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_GHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_MHZ", KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_MHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_KHZ", KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_KHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_HZ", KEY_FUNC_AMPT_PASSFAIL_WINDOW_FREQSTARTSTOP_HZ},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_WINDOWSWEEP", KEY_FUNC_AMPT_PASSFAIL_WINDOW_WINDOWSWEEP},
  {"KEY_FUNC_AMPT_PASSFAIL_WINDOW_RETURN", KEY_FUNC_AMPT_PASSFAIL_WINDOW_RETURN},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE", KEY_FUNC_AMPT_PASSFAIL_LINE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1ON", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1ON},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2ON", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2ON},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_FIRSTPAGE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_FIRSTPAGE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_PREVPAGE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_PREVPAGE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_NEXTPAGE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_NEXTPAGE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_LASTPAGE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_LASTPAGE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_ADD", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_ADD},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_INSERT", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_INSERT},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_DELETE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_DELETE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_CLEAR", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_CLEAR},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_GHZ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_GHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_MHZ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_MHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_KHZ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_KHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_HZ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITFREQ_HZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITLIMIT", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITLIMIT},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITLIMIT_DBM", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_EDITLIMIT_DBM},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_RETURN", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_OPERATION_RETURN},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_RETURN", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE1EDIT_RETURN},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_FIRSTPAGE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_FIRSTPAGE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_PREVPAGE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_PREVPAGE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_NEXTPAGE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_NEXTPAGE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_LASTPAGE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_LASTPAGE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_ADD", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_ADD},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_INSERT", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_INSERT},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_DELETE", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_DELETE},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_CLEAR", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_CLEAR},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_GHZ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_GHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_MHZ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_MHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_KHZ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_KHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_HZ", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITFREQ_HZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITLIMIT", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITLIMIT},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITLIMIT_DBM", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_EDITLIMIT_DBM},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_RETURN", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_OPERATION_RETURN},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_RETURN", KEY_FUNC_AMPT_PASSFAIL_LINE_LINE2EDIT_RETURN},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY", KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_GHZ", KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_GHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_MHZ", KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_MHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_KHZ", KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_KHZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_HZ", KEY_FUNC_AMPT_PASSFAIL_LINE_SHIFTXY_HZ},
  {"KEY_FUNC_AMPT_PASSFAIL_LINE_RETURN", KEY_FUNC_AMPT_PASSFAIL_LINE_RETURN},
  {"KEY_FUNC_AMPT_PASSFAIL_RETURN", KEY_FUNC_AMPT_PASSFAIL_RETURN},

  {"KEY_FUNC_BW_RBW", KEY_FUNC_BW_RBW},
  {"KEY_FUNC_BW_RBW_GHZ", KEY_FUNC_BW_RBW_GHZ},
  {"KEY_FUNC_BW_RBW_MHZ", KEY_FUNC_BW_RBW_MHZ},
  {"KEY_FUNC_BW_RBW_KHZ", KEY_FUNC_BW_RBW_KHZ},
  {"KEY_FUNC_BW_RBW_HZ", KEY_FUNC_BW_RBW_HZ},
  {"KEY_FUNC_BW_RBWMODE", KEY_FUNC_BW_RBWMODE},
  {"KEY_FUNC_BW_VBW", KEY_FUNC_BW_VBW},
  {"KEY_FUNC_BW_VBW_GHZ", KEY_FUNC_BW_VBW_GHZ},
  {"KEY_FUNC_BW_VBW_MHZ", KEY_FUNC_BW_VBW_MHZ},
  {"KEY_FUNC_BW_VBW_KHZ", KEY_FUNC_BW_VBW_KHZ},
  {"KEY_FUNC_BW_VBW_HZ", KEY_FUNC_BW_VBW_HZ},
  {"KEY_FUNC_BW_VBWMODE", KEY_FUNC_BW_VBWMODE},
  {"KEY_FUNC_BW_AVERAGE", KEY_FUNC_BW_AVERAGE},
  {"KEY_FUNC_BW_AVERAGE_ENTER", KEY_FUNC_BW_AVERAGE_ENTER},
  {"KEY_FUNC_BW_EMC", KEY_FUNC_BW_EMC},
  {"KEY_FUNC_BW_EMC_EMC", KEY_FUNC_BW_EMC_EMC},
  {"KEY_FUNC_BW_EMC_VALUE", KEY_FUNC_BW_EMC_VALUE},
  {"KEY_FUNC_BW_EMC_1MHZ", KEY_FUNC_BW_EMC_1MHZ},
  {"KEY_FUNC_BW_EMC_120KHZ", KEY_FUNC_BW_EMC_120KHZ},
  {"KEY_FUNC_BW_EMC_30KHZ", KEY_FUNC_BW_EMC_30KHZ},
  {"KEY_FUNC_BW_EMC_9KHZ", KEY_FUNC_BW_EMC_9KHZ},
  {"KEY_FUNC_BW_EMC_200HZ", KEY_FUNC_BW_EMC_200HZ},
  {"KEY_FUNC_BW_EMC_RETURN", KEY_FUNC_BW_EMC_RETURN},
  {"KEY_FUNC_BW_PREV", KEY_FUNC_BW_PREV},

  {"KEY_FUNC_SWEEP_SWEEPTIME", KEY_FUNC_SWEEP_SWEEPTIME},
  {"KEY_FUNC_SWEEP_SWEEPTIME_S", KEY_FUNC_SWEEP_SWEEPTIME_S},
  {"KEY_FUNC_SWEEP_SWEEPTIME_MS", KEY_FUNC_SWEEP_SWEEPTIME_MS},
  {"KEY_FUNC_SWEEP_SWEEPTIME_US", KEY_FUNC_SWEEP_SWEEPTIME_US},
  {"KEY_FUNC_SWEEP_SWEEPTIME_NS", KEY_FUNC_SWEEP_SWEEPTIME_NS},
  {"KEY_FUNC_SWEEP_SWEEPMODE_SINGLE", KEY_FUNC_SWEEP_SWEEPMODE_SINGLE},
  {"KEY_FUNC_SWEEP_SWEEPMODE_CONTINUOUS", KEY_FUNC_SWEEP_SWEEPMODE_CONTINUOUS},
  {"KEY_FUNC_SWEEP_SWEEPPOINTS", KEY_FUNC_SWEEP_SWEEPPOINTS},
  {"KEY_FUNC_SWEEP_SWEEPPOINTS_ENTER", KEY_FUNC_SWEEP_SWEEPPOINTS_ENTER},

  {"KEY_FUNC_TRIG_AUTORUN", KEY_FUNC_TRIG_AUTORUN},
  {"KEY_FUNC_TRIG_VIDEO", KEY_FUNC_TRIG_VIDEO},
  {"KEY_FUNC_TRIG_VIDEO_DBM", KEY_FUNC_TRIG_VIDEO_DBM},
  {"KEY_FUNC_TRIG_EXTERNAL", KEY_FUNC_TRIG_EXTERNAL},
  {"KEY_FUNC_TRIG_EXTERNAL_FALL", KEY_FUNC_TRIG_EXTERNAL_FALL},
  {"KEY_FUNC_TRIG_EXTERNAL_RISE", KEY_FUNC_TRIG_EXTERNAL_RISE},
  {"KEY_FUNC_TRIG_EXTERNAL_RETURN", KEY_FUNC_TRIG_EXTERNAL_RETURN},

  {"KEY_FUNC_MEAS_MEASUREOFF", KEY_FUNC_MEAS_MEASUREOFF},
  {"KEY_FUNC_MEAS_TIMESPEC", KEY_FUNC_MEAS_TIMESPEC},
  {"KEY_FUNC_MEAS_ACPR", KEY_FUNC_MEAS_ACPR},
  {"KEY_FUNC_MEAS_CHANNELPOWER", KEY_FUNC_MEAS_CHANNELPOWER},
  {"KEY_FUNC_MEAS_OBW", KEY_FUNC_MEAS_OBW},
  {"KEY_FUNC_MEAS_DISCRIMINATOR", KEY_FUNC_MEAS_DISCRIMINATOR},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_DISCRIMINATOR", KEY_FUNC_MEAS_DISCRIMINATOR_DISCRIMINATOR},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_NORMALIZE", KEY_FUNC_MEAS_DISCRIMINATOR_NORMALIZE},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OUTPUTPOWER", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OUTPUTPOWER},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OUTPUTPOWER_ENTER", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OUTPUTPOWER_ENTER},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X1", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X1},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X2", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X2},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X4", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X4},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X05", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X05},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X025", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_X025},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_RETURN", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_INPUTGAIN_RETURN},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_SCALEDIV", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_SCALEDIV},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_SCALEDIV_ENTER", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_SCALEDIV_ENTER},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OFFSET", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OFFSET},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OFFSET_ENTER", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_OFFSET_ENTER},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_RETURN", KEY_FUNC_MEAS_DISCRIMINATOR_AMPLITUDE_RETURN},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME", KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_S", KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_S},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_MS", KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_MS},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_US", KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_US},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_NS", KEY_FUNC_MEAS_DISCRIMINATOR_SWEEPTIME_NS},
  {"KEY_FUNC_MEAS_DISCRIMINATOR_RETURN", KEY_FUNC_MEAS_DISCRIMINATOR_RETURN},
  {"KEY_FUNC_MEAS_EMC", KEY_FUNC_MEAS_EMC},

  {"KEY_FUNC_MEASSETUP_CHANNELWIDTH", KEY_FUNC_MEASSETUP_CHANNELWIDTH},
  {"KEY_FUNC_MEASSETUP_CHANNELWIDTH_GHZ", KEY_FUNC_MEASSETUP_CHANNELWIDTH_GHZ},
  {"KEY_FUNC_MEASSETUP_CHANNELWIDTH_MHZ", KEY_FUNC_MEASSETUP_CHANNELWIDTH_MHZ},
  {"KEY_FUNC_MEASSETUP_CHANNELWIDTH_KHZ", KEY_FUNC_MEASSETUP_CHANNELWIDTH_KHZ},
  {"KEY_FUNC_MEASSETUP_CHANNELWIDTH_HZ", KEY_FUNC_MEASSETUP_CHANNELWIDTH_HZ},
  {"KEY_FUNC_MEASSETUP_CHANNELINTERVAL", KEY_FUNC_MEASSETUP_CHANNELINTERVAL},
  {"KEY_FUNC_MEASSETUP_CHANNELINTERVAL_GHZ", KEY_FUNC_MEASSETUP_CHANNELINTERVAL_GHZ},
  {"KEY_FUNC_MEASSETUP_CHANNELINTERVAL_MHZ", KEY_FUNC_MEASSETUP_CHANNELINTERVAL_MHZ},
  {"KEY_FUNC_MEASSETUP_CHANNELINTERVAL_KHZ", KEY_FUNC_MEASSETUP_CHANNELINTERVAL_KHZ},
  {"KEY_FUNC_MEASSETUP_CHANNELINTERVAL_HZ", KEY_FUNC_MEASSETUP_CHANNELINTERVAL_HZ},
  {"KEY_FUNC_MEASSETUP_CHANNELNUMS", KEY_FUNC_MEASSETUP_CHANNELNUMS},
  {"KEY_FUNC_MEASSETUP_CHANNELNUMS_ENTER", KEY_FUNC_MEASSETUP_CHANNELNUMS_ENTER},
  {"KEY_FUNC_MEASSETUP_POWERBWPERCENT", KEY_FUNC_MEASSETUP_POWERBWPERCENT},
  {"KEY_FUNC_MEASSETUP_POWERBWPERCENT_ENTER", KEY_FUNC_MEASSETUP_POWERBWPERCENT_ENTER},

  {"KEY_FUNC_TRACE_TRACE", KEY_FUNC_TRACE_TRACE},
  {"KEY_FUNC_TRACE_CLEARWRITE", KEY_FUNC_TRACE_CLEARWRITE},
  {"KEY_FUNC_TRACE_MAXHOLD", KEY_FUNC_TRACE_MAXHOLD},
  {"KEY_FUNC_TRACE_MINHOLD", KEY_FUNC_TRACE_MINHOLD},
  {"KEY_FUNC_TRACE_VIEW", KEY_FUNC_TRACE_VIEW},
  {"KEY_FUNC_TRACE_BLANK", KEY_FUNC_TRACE_BLANK},

  {"KEY_FUNC_TRACE_OPERATIONS", KEY_FUNC_TRACE_OPERATIONS},
  {"KEY_FUNC_TRACE_OPERATIONS_12", KEY_FUNC_TRACE_OPERATIONS_12},
  {"KEY_FUNC_TRACE_OPERATIONS_2DLTO2", KEY_FUNC_TRACE_OPERATIONS_2DLTO2},
  {"KEY_FUNC_TRACE_OPERATIONS_23", KEY_FUNC_TRACE_OPERATIONS_23},
  {"KEY_FUNC_TRACE_OPERATIONS_1TO3", KEY_FUNC_TRACE_OPERATIONS_1TO3},
  {"KEY_FUNC_TRACE_OPERATIONS_2TO3", KEY_FUNC_TRACE_OPERATIONS_2TO3},
  {"KEY_FUNC_TRACE_OPERATIONS_RETURN", KEY_FUNC_TRACE_OPERATIONS_RETURN},

  {"KEY_FUNC_DETECTOR_AUTO", KEY_FUNC_DETECTOR_AUTO},
  {"KEY_FUNC_DETECTOR_NORMAL", KEY_FUNC_DETECTOR_NORMAL},
  {"KEY_FUNC_DETECTOR_POSPEAK", KEY_FUNC_DETECTOR_POSPEAK},
  {"KEY_FUNC_DETECTOR_NEGPEAK", KEY_FUNC_DETECTOR_NEGPEAK},
  {"KEY_FUNC_DETECTOR_SAMPLE", KEY_FUNC_DETECTOR_SAMPLE},
  {"KEY_FUNC_DETECTOR_TRANSIENT", KEY_FUNC_DETECTOR_TRANSIENT},

  {"KEY_FUNC_MARKER_MARKER", KEY_FUNC_MARKER_MARKER},
  {"KEY_FUNC_MARKER_TRACE", KEY_FUNC_MARKER_TRACE},
  {"KEY_FUNC_MARKER_NORMAL", KEY_FUNC_MARKER_NORMAL},
  {"KEY_FUNC_MARKER_NORMAL_GHZ", KEY_FUNC_MARKER_NORMAL_GHZ},
  {"KEY_FUNC_MARKER_NORMAL_MHZ", KEY_FUNC_MARKER_NORMAL_MHZ},
  {"KEY_FUNC_MARKER_NORMAL_KHZ", KEY_FUNC_MARKER_NORMAL_KHZ},
  {"KEY_FUNC_MARKER_NORMAL_HZ", KEY_FUNC_MARKER_NORMAL_HZ},
  {"KEY_FUNC_MARKER_DELTA", KEY_FUNC_MARKER_DELTA},
  {"KEY_FUNC_MARKER_DELTA_GHZ", KEY_FUNC_MARKER_DELTA_GHZ},
  {"KEY_FUNC_MARKER_DELTA_MHZ", KEY_FUNC_MARKER_DELTA_MHZ},
  {"KEY_FUNC_MARKER_DELTA_KHZ", KEY_FUNC_MARKER_DELTA_KHZ},
  {"KEY_FUNC_MARKER_DELTA_HZ", KEY_FUNC_MARKER_DELTA_HZ},
  {"KEY_FUNC_MARKER_OFF", KEY_FUNC_MARKER_OFF},
  {"KEY_FUNC_MARKER_ALLOFF", KEY_FUNC_MARKER_ALLOFF},
  {"KEY_FUNC_MARKER_LIST", KEY_FUNC_MARKER_LIST},

  {"KEY_FUNC_MARKERFCTN_OFF", KEY_FUNC_MARKERFCTN_OFF},
  {"KEY_FUNC_MARKERFCTN_NDB", KEY_FUNC_MARKERFCTN_NDB},
  {"KEY_FUNC_MARKERFCTN_NDB_ENTER", KEY_FUNC_MARKERFCTN_NDB_ENTER},
  {"KEY_FUNC_MARKERFCTN_NOISE", KEY_FUNC_MARKERFCTN_NOISE},
  {"KEY_FUNC_MARKERFCTN_FREQCOUNT", KEY_FUNC_MARKERFCTN_FREQCOUNT},
  {"KEY_FUNC_MARKERFCTN_FREQCOUNT_FREQCOUNT", KEY_FUNC_MARKERFCTN_FREQCOUNT_FREQCOUNT},
  {"KEY_FUNC_MARKERFCTN_FREQCOUNT_BW", KEY_FUNC_MARKERFCTN_FREQCOUNT_BW},
  {"KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_GHZ", KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_GHZ},
  {"KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_MHZ", KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_MHZ},
  {"KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_KHZ", KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_KHZ},
  {"KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_HZ", KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_HZ},
  {"KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_RETURN", KEY_FUNC_MARKERFCTN_FREQCOUNT_BW_RETURN},
  {"KEY_FUNC_MARKERFCTN_FREQCOUNT_RETURN", KEY_FUNC_MARKERFCTN_FREQCOUNT_RETURN},

  {"KEY_FUNC_MARKERTO_CENTER", KEY_FUNC_MARKERTO_CENTER},
  {"KEY_FUNC_MARKERTO_CFSTEP", KEY_FUNC_MARKERTO_CFSTEP},
  {"KEY_FUNC_MARKERTO_START", KEY_FUNC_MARKERTO_START},
  {"KEY_FUNC_MARKERTO_STOP", KEY_FUNC_MARKERTO_STOP},
  {"KEY_FUNC_MARKERTO_REFLEVEL", KEY_FUNC_MARKERTO_REFLEVEL},
  {"KEY_FUNC_MARKERTO_DELTATOSPAN", KEY_FUNC_MARKERTO_DELTATOSPAN},
  {"KEY_FUNC_MARKERTO_DELTATOCF", KEY_FUNC_MARKERTO_DELTATOCF},

  {"KEY_FUNC_PEAK_MAXSEARCH", KEY_FUNC_PEAK_MAXSEARCH},
  {"KEY_FUNC_PEAK_NEXTPEAK", KEY_FUNC_PEAK_NEXTPEAK},
  {"KEY_FUNC_PEAK_LEFTPEAK", KEY_FUNC_PEAK_LEFTPEAK},
  {"KEY_FUNC_PEAK_RIGHTPEAK", KEY_FUNC_PEAK_RIGHTPEAK},
  {"KEY_FUNC_PEAK_MINSEARCH", KEY_FUNC_PEAK_MINSEARCH},
  {"KEY_FUNC_PEAK_MKRTOCF", KEY_FUNC_PEAK_MKRTOCF},
  {"KEY_FUNC_PEAK_AUTOMAXSEARCH", KEY_FUNC_PEAK_AUTOMAXSEARCH},

  {"KEY_FUNC_SYSTEM_SYSTEM", KEY_FUNC_SYSTEM_SYSTEM},
  {"KEY_FUNC_SYSTEM_SYSTEM_INFO", KEY_FUNC_SYSTEM_SYSTEM_INFO},
  {"KEY_FUNC_SYSTEM_SYSTEM_LOG", KEY_FUNC_SYSTEM_SYSTEM_LOG},
  {"KEY_FUNC_SYSTEM_SYSTEM_RETURN", KEY_FUNC_SYSTEM_SYSTEM_RETURN},
  {"KEY_FUNC_SYSTEM_CONFIGIO", KEY_FUNC_SYSTEM_CONFIGIO},
  {"KEY_FUNC_SYSTEM_CONFIGIO_LAN", KEY_FUNC_SYSTEM_CONFIGIO_LAN},
  {"KEY_FUNC_SYSTEM_CONFIGIO_LAN_IP", KEY_FUNC_SYSTEM_CONFIGIO_LAN_IP},
  {"KEY_FUNC_SYSTEM_CONFIGIO_LAN_IP_ENTER", KEY_FUNC_SYSTEM_CONFIGIO_LAN_IP_ENTER},
  {"KEY_FUNC_SYSTEM_CONFIGIO_LAN_MASK", KEY_FUNC_SYSTEM_CONFIGIO_LAN_MASK},
  {"KEY_FUNC_SYSTEM_CONFIGIO_LAN_MASK_ENTER", KEY_FUNC_SYSTEM_CONFIGIO_LAN_MASK_ENTER},
  {"KEY_FUNC_SYSTEM_CONFIGIO_LAN_GATE", KEY_FUNC_SYSTEM_CONFIGIO_LAN_GATE},
  {"KEY_FUNC_SYSTEM_CONFIGIO_LAN_GATE_ENTER", KEY_FUNC_SYSTEM_CONFIGIO_LAN_GATE_ENTER},
  {"KEY_FUNC_SYSTEM_CONFIGIO_LAN_RESET", KEY_FUNC_SYSTEM_CONFIGIO_LAN_RESET},
  {"KEY_FUNC_SYSTEM_CONFIGIO_LAN_RETURN", KEY_FUNC_SYSTEM_CONFIGIO_LAN_RETURN},

  {"KEY_FUNC_SYSTEM_CONFIGIO_GPIB", KEY_FUNC_SYSTEM_CONFIGIO_GPIB},
  {"KEY_FUNC_SYSTEM_CONFIGIO_GPIB_ADDR", KEY_FUNC_SYSTEM_CONFIGIO_GPIB_ADDR},
  {"KEY_FUNC_SYSTEM_CONFIGIO_GPIB_ADDR_ENTER", KEY_FUNC_SYSTEM_CONFIGIO_GPIB_ADDR_ENTER},
  {"KEY_FUNC_SYSTEM_CONFIGIO_GPIB_RETURN", KEY_FUNC_SYSTEM_CONFIGIO_GPIB_RETURN},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM", KEY_FUNC_SYSTEM_CONFIGIO_COM},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_1200", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_1200},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_2400", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_2400},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_4800", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_4800},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_9600", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_9600},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_19200", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_19200},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_38400", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_38400},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_57600", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_57600},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_115200", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_115200},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_RETURN", KEY_FUNC_SYSTEM_CONFIGIO_COM_BAUDRATE_RETURN},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS", KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_5", KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_5},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_6", KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_6},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_7", KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_7},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_8", KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_8},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_RETURN", KEY_FUNC_SYSTEM_CONFIGIO_COM_DATABITS_RETURN},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS", KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS_1", KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS_1},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS_2", KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS_2},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS_RETURN", KEY_FUNC_SYSTEM_CONFIGIO_COM_STOPBITS_RETURN},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK", KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_EVEN", KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_EVEN},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_ODD", KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_ODD},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_NONE", KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_NONE},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_SPACE", KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_SPACE},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_RETURN", KEY_FUNC_SYSTEM_CONFIGIO_COM_CHECK_RETURN},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL", KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_XONXOFF", KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_XONXOFF},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_HARDWARE", KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_HARDWARE},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_NONE", KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_NONE},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_RETURN", KEY_FUNC_SYSTEM_CONFIGIO_COM_FLOWCONTROL_RETURN},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_RESET", KEY_FUNC_SYSTEM_CONFIGIO_COM_RESET},
  {"KEY_FUNC_SYSTEM_CONFIGIO_COM_RETURN", KEY_FUNC_SYSTEM_CONFIGIO_COM_RETURN},
  {"KEY_FUNC_SYSTEM_CONFIGIO_RETURN", KEY_FUNC_SYSTEM_CONFIGIO_RETURN},

  {"KEY_FUNC_SYSTEM_POWERONPRESET", KEY_FUNC_SYSTEM_POWERONPRESET},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_POWERON", KEY_FUNC_SYSTEM_POWERONPRESET_POWERON},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_FACTORY", KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_FACTORY},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_USER", KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_USER},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_POWEROFF", KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_POWEROFF},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_RETURN", KEY_FUNC_SYSTEM_POWERONPRESET_POWERON_RETURN},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_PRESET", KEY_FUNC_SYSTEM_POWERONPRESET_PRESET},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_FACTORY", KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_FACTORY},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_USER", KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_USER},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_POWEROFF", KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_POWEROFF},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_RETURN", KEY_FUNC_SYSTEM_POWERONPRESET_PRESET_RETURN},
  {"KEY_FUNC_SYSTEM_POWERONPRESET_RETURN", KEY_FUNC_SYSTEM_POWERONPRESET_RETURN},

  {"KEY_FUNC_SYSTEM_LANGUAGE", KEY_FUNC_SYSTEM_LANGUAGE},
  {"KEY_FUNC_SYSTEM_LANGUAGE_CHINESE", KEY_FUNC_SYSTEM_LANGUAGE_CHINESE},
  {"KEY_FUNC_SYSTEM_LANGUAGE_ENGLISH", KEY_FUNC_SYSTEM_LANGUAGE_ENGLISH},
  {"KEY_FUNC_SYSTEM_LANGUAGE_RETURN", KEY_FUNC_SYSTEM_LANGUAGE_RETURN},

  {"KEY_FUNC_SAVE_SCEEEN", KEY_FUNC_SAVE_SCEEEN},
  {"KEY_FUNC_SAVE_SCEEEN_TOLOCAL", KEY_FUNC_SAVE_SCEEEN_TOLOCAL},
  {"KEY_FUNC_SAVE_SCEEEN_TOUSB", KEY_FUNC_SAVE_SCEEEN_TOUSB},
  {"KEY_FUNC_SAVE_SCEEEN_RETURN", KEY_FUNC_SAVE_SCEEEN_RETURN},
  {"KEY_FUNC_SAVE_TRACE", KEY_FUNC_SAVE_TRACE},
  {"KEY_FUNC_SAVE_TRACE_TOLOCAL", KEY_FUNC_SAVE_TRACE_TOLOCAL},
  {"KEY_FUNC_SAVE_TRACE_TOUSB", KEY_FUNC_SAVE_TRACE_TOUSB},
  {"KEY_FUNC_SAVE_TRACE_RETURN", KEY_FUNC_SAVE_TRACE_RETURN},
  {"KEY_FUNC_SAVE_USER", KEY_FUNC_SAVE_USER},
  {"KEY_FUNC_SAVE_LOAD", KEY_FUNC_SAVE_LOAD},
  {"KEY_FUNC_SAVE_LOAD_USER1", KEY_FUNC_SAVE_LOAD_USER1},
  {"KEY_FUNC_SAVE_LOAD_USER2", KEY_FUNC_SAVE_LOAD_USER2},
  {"KEY_FUNC_SAVE_LOAD_USER3", KEY_FUNC_SAVE_LOAD_USER3},
  {"KEY_FUNC_SAVE_LOAD_USER4", KEY_FUNC_SAVE_LOAD_USER4},
  {"KEY_FUNC_SAVE_LOAD_USER5", KEY_FUNC_SAVE_LOAD_USER5},
  {"KEY_FUNC_SAVE_LOAD_USER6", KEY_FUNC_SAVE_LOAD_USER6},
  {"KEY_FUNC_SAVE_LOAD_NEXTPAGE", KEY_FUNC_SAVE_LOAD_NEXTPAGE},
  {"KEY_FUNC_SAVE_LOAD_USER7", KEY_FUNC_SAVE_LOAD_USER7},
  {"KEY_FUNC_SAVE_LOAD_USER8", KEY_FUNC_SAVE_LOAD_USER8},
  {"KEY_FUNC_SAVE_LOAD_USER9", KEY_FUNC_SAVE_LOAD_USER9},
  {"KEY_FUNC_SAVE_LOAD_USER10", KEY_FUNC_SAVE_LOAD_USER10},
  {"KEY_FUNC_SAVE_LOAD_RETURN", KEY_FUNC_SAVE_LOAD_RETURN},
  {"KEY_FUNC_SAVE_SAVE", KEY_FUNC_SAVE_SAVE},
  {"KEY_FUNC_SAVE_SAVE_USER1", KEY_FUNC_SAVE_SAVE_USER1},
  {"KEY_FUNC_SAVE_SAVE_USER2", KEY_FUNC_SAVE_SAVE_USER2},
  {"KEY_FUNC_SAVE_SAVE_USER3", KEY_FUNC_SAVE_SAVE_USER3},
  {"KEY_FUNC_SAVE_SAVE_USER4", KEY_FUNC_SAVE_SAVE_USER4},
  {"KEY_FUNC_SAVE_SAVE_USER5", KEY_FUNC_SAVE_SAVE_USER5},
  {"KEY_FUNC_SAVE_SAVE_USER6", KEY_FUNC_SAVE_SAVE_USER6},
  {"KEY_FUNC_SAVE_SAVE_NEXTPAGE", KEY_FUNC_SAVE_SAVE_NEXTPAGE},
  {"KEY_FUNC_SAVE_SAVE_USER7", KEY_FUNC_SAVE_SAVE_USER7},
  {"KEY_FUNC_SAVE_SAVE_USER8", KEY_FUNC_SAVE_SAVE_USER8},
  {"KEY_FUNC_SAVE_SAVE_USER9", KEY_FUNC_SAVE_SAVE_USER9},
  {"KEY_FUNC_SAVE_SAVE_USER10", KEY_FUNC_SAVE_SAVE_USER10},
  {"KEY_FUNC_SAVE_SAVE_RETURN", KEY_FUNC_SAVE_SAVE_RETURN},

  {"KEY_FUNC_SAVE_CLEAR", KEY_FUNC_SAVE_CLEAR},
  {"KEY_FUNC_SAVE_CLEAR_USER1", KEY_FUNC_SAVE_CLEAR_USER1},
  {"KEY_FUNC_SAVE_CLEAR_USER2", KEY_FUNC_SAVE_CLEAR_USER2},
  {"KEY_FUNC_SAVE_CLEAR_USER3", KEY_FUNC_SAVE_CLEAR_USER3},
  {"KEY_FUNC_SAVE_CLEAR_USER4", KEY_FUNC_SAVE_CLEAR_USER4},
  {"KEY_FUNC_SAVE_CLEAR_USER5", KEY_FUNC_SAVE_CLEAR_USER5},
  {"KEY_FUNC_SAVE_CLEAR_USER6", KEY_FUNC_SAVE_CLEAR_USER6},
  {"KEY_FUNC_SAVE_CLEAR_NEXTPAGE", KEY_FUNC_SAVE_CLEAR_NEXTPAGE},
  {"KEY_FUNC_SAVE_CLEAR_USER7", KEY_FUNC_SAVE_CLEAR_USER7},
  {"KEY_FUNC_SAVE_CLEAR_USER8", KEY_FUNC_SAVE_CLEAR_USER8},
  {"KEY_FUNC_SAVE_CLEAR_USER9", KEY_FUNC_SAVE_CLEAR_USER9},
  {"KEY_FUNC_SAVE_CLEAR_USER10", KEY_FUNC_SAVE_CLEAR_USER10},
  {"KEY_FUNC_SAVE_CLEAR_RETURN", KEY_FUNC_SAVE_CLEAR_RETURN},
  {"KEY_FUNC_SAVE_CLEAR_ALL", KEY_FUNC_SAVE_CLEAR_ALL},

  {"KEY_FUNC_SYSTEM_DATETIME", KEY_FUNC_SYSTEM_DATETIME},
  {"KEY_FUNC_SYSTEM_DATETIME_DATETIME", KEY_FUNC_SYSTEM_DATETIME_DATETIME},
  {"KEY_FUNC_SYSTEM_DATETIME_FORMAT", KEY_FUNC_SYSTEM_DATETIME_FORMAT},
  {"KEY_FUNC_SYSTEM_DATETIME_FORMAT_YMDHMS", KEY_FUNC_SYSTEM_DATETIME_FORMAT_YMDHMS},
  {"KEY_FUNC_SYSTEM_DATETIME_FORMAT_HMSYMD", KEY_FUNC_SYSTEM_DATETIME_FORMAT_HMSYMD},
  {"KEY_FUNC_SYSTEM_DATETIME_FORMAT_RETURN", KEY_FUNC_SYSTEM_DATETIME_FORMAT_RETURN},
  {"KEY_FUNC_SYSTEM_DATETIME_DATE", KEY_FUNC_SYSTEM_DATETIME_DATE},
  {"KEY_FUNC_SYSTEM_DATETIME_DATE_ENTER", KEY_FUNC_SYSTEM_DATETIME_DATE_ENTER},
  {"KEY_FUNC_SYSTEM_DATETIME_TIME", KEY_FUNC_SYSTEM_DATETIME_TIME},
  {"KEY_FUNC_SYSTEM_DATETIME_TIME_ENTER", KEY_FUNC_SYSTEM_DATETIME_TIME_ENTER},
  {"KEY_FUNC_SYSTEM_DATETIME_RETURN", KEY_FUNC_SYSTEM_DATETIME_RETURN},

  {"KEY_FUNC_SYSTEM_CHANNELSELECT", KEY_FUNC_SYSTEM_CHANNELSELECT},

  {"KEY_FUNC_SYSTEM_CALIBRATION", KEY_FUNC_SYSTEM_CALIBRATION},
  {"KEY_FUNC_SYSTEM_CALIBRATION_CALIBRATION", KEY_FUNC_SYSTEM_CALIBRATION_CALIBRATION},
  {"KEY_FUNC_SYSTEM_CALIBRATION_FACTORY", KEY_FUNC_SYSTEM_CALIBRATION_FACTORY},
  {"KEY_FUNC_SYSTEM_CALIBRATION_RETURN", KEY_FUNC_SYSTEM_CALIBRATION_RETURN},

  {"KEY_FUNC_SYSTEM_SERVICE", KEY_FUNC_SYSTEM_SERVICE},
  {"KEY_FUNC_SYSTEM_SERVICE_SERIALNO", KEY_FUNC_SYSTEM_SERVICE_SERIALNO},
  {"KEY_FUNC_SYSTEM_SERVICE_LANMACADDR", KEY_FUNC_SYSTEM_SERVICE_LANMACADDR},
  {"KEY_FUNC_SYSTEM_SERVICE_SERIALNO_ENTER", KEY_FUNC_SYSTEM_SERVICE_SERIALNO_ENTER},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_DELETE", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_DELETE},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_9K", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_9K},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_9K_ENTER", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_9K_ENTER},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_9K_RESET", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_9K_RESET},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_20K", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_20K},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_20K_ENTER", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_20K_ENTER},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_20K_RESET", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_20K_RESET},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_RETURN", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_EDIT_RETURN},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_CALIBRATION", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_CALIBRATION},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_LFCALIBRATION", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_LFCALIBRATION},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_PRECALIBRATION", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_PRECALIBRATION},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_MODE", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_MODE},
  {"KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_RETURN", KEY_FUNC_SYSTEM_SERVICE_CALIBRATION_RETURN},
  {"KEY_FUNC_SYSTEM_SERVICE_EVALUATE", KEY_FUNC_SYSTEM_SERVICE_EVALUATE},
  {"KEY_FUNC_SYSTEM_SERVICE_CLEAR_LOGDATA",KEY_FUNC_SYSTEM_SERVICE_CLEAR_LOGDATA},
  {"KEY_FUNC_SYSTEM_SERVICE_TRACK_SELECT",KEY_FUNC_SYSTEM_SERVICE_TRACK_SELECT},
  {"KEY_FUNC_SYSTEM_SERVICE_OPTION",KEY_FUNC_SYSTEM_SERVICE_OPTION},
  {"KEY_FUNC_SYSTEM_SERVICE_OPTION_FFT",KEY_FUNC_SYSTEM_SERVICE_OPTION_FFT},
  {"KEY_FUNC_SYSTEM_SERVICE_OPTION_AMFM", KEY_FUNC_SYSTEM_SERVICE_OPTION_AMFM},
  {"KEY_FUNC_SYSTEM_SERVICE_OPTION_DIRECTCHANNEL", KEY_FUNC_SYSTEM_SERVICE_OPTION_DIRECTCHANNEL},
  {"KEY_FUNC_SYSTEM_SERVICE_OPTION_RETURN",KEY_FUNC_SYSTEM_SERVICE_OPTION_RETURN},
  {"KEY_FUNC_SYSTEM_SERVICE_DEVICE",KEY_FUNC_SYSTEM_SERVICE_DEVICE},
  {"KEY_FUNC_SYSTEM_SERVICE_DEVICE_RETURN",KEY_FUNC_SYSTEM_SERVICE_DEVICE_RETURN},
  {"KEY_FUNC_SYSTEM_SERVICE_DEVICE_TIMESELECT",KEY_FUNC_SYSTEM_SERVICE_DEVICE_TIMESELECT},
  {"KEY_FUNC_SYSTEM_SERVICE_DEVICE_LOGDISPLAY",KEY_FUNC_SYSTEM_SERVICE_DEVICE_LOGDISPLAY},
  {"KEY_FUNC_SYSTEM_SERVICE_DEVICE_GPIB",KEY_FUNC_SYSTEM_SERVICE_DEVICE_GPIB},
  {"KEY_FUNC_SYSTEM_SERVICE_RETURN", KEY_FUNC_SYSTEM_SERVICE_RETURN},

  {"KEY_FUNC_SYSTEM_NEXTPAGE", KEY_FUNC_SYSTEM_NEXTPAGE},  

  {"KEY_FUNC_SYSTEM_BACKLIGHT", KEY_FUNC_SYSTEM_BACKLIGHT},
  {"KEY_FUNC_SYSTEM_BACKLIGHT_ENTER", KEY_FUNC_SYSTEM_BACKLIGHT_ENTER},

  {"KEY_FUNC_SYSTEM_SCPI_SCREENREFRESH", KEY_FUNC_SYSTEM_SCPI_SCREENREFRESH},

  {"KEY_FUNC_SYSTEM_NEXTPAGE_RETURN", KEY_FUNC_SYSTEM_NEXTPAGE_RETURN},

  {"KEY_FUNC_PRINTSETUP_PAPER", KEY_FUNC_PRINTSETUP_PAPER},
  {"KEY_FUNC_PRINTSETUP_PAPER_A4", KEY_FUNC_PRINTSETUP_PAPER_A4},
  {"KEY_FUNC_PRINTSETUP_PAPER_A3", KEY_FUNC_PRINTSETUP_PAPER_A3},
  {"KEY_FUNC_PRINTSETUP_PAPER_B5", KEY_FUNC_PRINTSETUP_PAPER_B5},
  {"KEY_FUNC_PRINTSETUP_PAPER_C5", KEY_FUNC_PRINTSETUP_PAPER_C5},
  {"KEY_FUNC_PRINTSETUP_PAPER_LETTER", KEY_FUNC_PRINTSETUP_PAPER_LETTER},
  {"KEY_FUNC_PRINTSETUP_PAPER_RETURN", KEY_FUNC_PRINTSETUP_PAPER_RETURN},
  {"KEY_FUNC_PRINTSETUP_LANGUAGE", KEY_FUNC_PRINTSETUP_LANGUAGE},
  {"KEY_FUNC_PRINTSETUP_COLOR", KEY_FUNC_PRINTSETUP_COLOR},
  {"KEY_FUNC_PRINTSETUP_ORIENTATION", KEY_FUNC_PRINTSETUP_ORIENTATION},
  {"KEY_FUNC_PRINTSETUP_NUMS", KEY_FUNC_PRINTSETUP_NUMS},
  {"KEY_FUNC_PRINTSETUP_NUMS_ENTER", KEY_FUNC_PRINTSETUP_NUMS_ENTER},
  {"KEY_FUNC_PRINTSETUP_PRINTTRACE", KEY_FUNC_PRINTSETUP_PRINTTRACE},
  {"KEY_FUNC_PRINTSETUP_PRINTSCREEN", KEY_FUNC_PRINTSETUP_PRINTSCREEN},

  {"KEY_FUNC_DISPLAY_FULLSCREEN", KEY_FUNC_DISPLAY_FULLSCREEN},
  {"KEY_FUNC_DISPLAY_ZOOM", KEY_FUNC_DISPLAY_ZOOM},
  {"KEY_FUNC_DISPLAY_DISPLAYLINE", KEY_FUNC_DISPLAY_DISPLAYLINE},
  {"KEY_FUNC_DISPLAY_DISPLAYLINE_DBM", KEY_FUNC_DISPLAY_DISPLAYLINE_DBM},
  {"KEY_FUNC_DISPLAY_REFSCALE", KEY_FUNC_DISPLAY_REFSCALE},
  {"KEY_FUNC_DISPLAY_GRID", KEY_FUNC_DISPLAY_GRID},
  {"KEY_FUNC_DISPLAY_LABEL", KEY_FUNC_DISPLAY_LABEL},
  {"KEY_FUNC_DISPLAY_STYLE", KEY_FUNC_DISPLAY_STYLE},
  {"KEY_FUNC_DISPLAY_STYLE_DEFAULT", KEY_FUNC_DISPLAY_STYLE_DEFAULT},
  {"KEY_FUNC_DISPLAY_STYLE_STYLE1", KEY_FUNC_DISPLAY_STYLE_STYLE1},
  {"KEY_FUNC_DISPLAY_STYLE_RETURN", KEY_FUNC_DISPLAY_STYLE_RETURN},

  {"KEY_FUNC_FILE_REFRESH", KEY_FUNC_FILE_REFRESH},
  {"KEY_FUNC_FILE_SHOW", KEY_FUNC_FILE_SHOW},
  {"KEY_FUNC_FILE_SHOW_SCREENS", KEY_FUNC_FILE_SHOW_SCREENS},
  {"KEY_FUNC_FILE_SHOW_TRACEDATAS", KEY_FUNC_FILE_SHOW_TRACEDATAS},
  {"KEY_FUNC_FILE_SHOW_ALL", KEY_FUNC_FILE_SHOW_ALL},
  {"KEY_FUNC_FILE_SHOW_RETURN", KEY_FUNC_FILE_SHOW_RETURN},
  {"KEY_FUNC_FILE_CATALOG", KEY_FUNC_FILE_CATALOG},
  {"KEY_FUNC_FILE_FIRSTPAGE", KEY_FUNC_FILE_FIRSTPAGE},
  {"KEY_FUNC_FILE_PREVPAGE", KEY_FUNC_FILE_PREVPAGE},
  {"KEY_FUNC_FILE_NEXTPAGE", KEY_FUNC_FILE_NEXTPAGE},
  {"KEY_FUNC_FILE_LASTPAGE", KEY_FUNC_FILE_LASTPAGE},
  {"KEY_FUNC_FILE_OPERATIONS", KEY_FUNC_FILE_OPERATIONS},
  {"KEY_FUNC_FILE_OPERATIONS_SORT", KEY_FUNC_FILE_OPERATIONS_SORT},
  {"KEY_FUNC_FILE_OPERATIONS_SORT_NAME", KEY_FUNC_FILE_OPERATIONS_SORT_NAME},
  {"KEY_FUNC_FILE_OPERATIONS_SORT_DATETIME", KEY_FUNC_FILE_OPERATIONS_SORT_DATETIME},
  {"KEY_FUNC_FILE_OPERATIONS_SORT_SIZE", KEY_FUNC_FILE_OPERATIONS_SORT_SIZE},
  {"KEY_FUNC_FILE_OPERATIONS_SORT_RETURN", KEY_FUNC_FILE_OPERATIONS_SORT_RETURN},
  {"KEY_FUNC_FILE_OPERATIONS_DELETE", KEY_FUNC_FILE_OPERATIONS_DELETE},
  {"KEY_FUNC_FILE_OPERATIONS_DELETE_SELECT", KEY_FUNC_FILE_OPERATIONS_DELETE_SELECT},
  {"KEY_FUNC_FILE_OPERATIONS_DELETE_PAGE", KEY_FUNC_FILE_OPERATIONS_DELETE_PAGE},
  {"KEY_FUNC_FILE_OPERATIONS_DELETE_ALL", KEY_FUNC_FILE_OPERATIONS_DELETE_ALL},
  {"KEY_FUNC_FILE_OPERATIONS_DELETE_RETURN", KEY_FUNC_FILE_OPERATIONS_DELETE_RETURN},
  {"KEY_FUNC_FILE_OPERATIONS_COPY", KEY_FUNC_FILE_OPERATIONS_COPY},
  {"KEY_FUNC_FILE_OPERATIONS_COPY_SELECT_TOUSB", KEY_FUNC_FILE_OPERATIONS_COPY_SELECT_TOUSB},
  {"KEY_FUNC_FILE_OPERATIONS_COPY_PAGE_TOUSB", KEY_FUNC_FILE_OPERATIONS_COPY_PAGE_TOUSB},
  {"KEY_FUNC_FILE_OPERATIONS_COPY_ALL_TOUSB", KEY_FUNC_FILE_OPERATIONS_COPY_ALL_TOUSB},
  {"KEY_FUNC_FILE_OPERATIONS_COPY_RETURN", KEY_FUNC_FILE_OPERATIONS_COPY_RETURN},
  {"KEY_FUNC_FILE_OPERATIONS_LOAD", KEY_FUNC_FILE_OPERATIONS_LOAD},
  {"KEY_FUNC_FILE_OPERATIONS_RETURN", KEY_FUNC_FILE_OPERATIONS_RETURN},

  {"KEY_FUNC_SOURCE_TRACKGEN", KEY_FUNC_SOURCE_TRACKGEN},
  {"KEY_FUNC_SOURCE_TRACKGEN_TRACKGEN", KEY_FUNC_SOURCE_TRACKGEN_TRACKGEN},
  {"KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE", KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE},
  {"KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE_S21", KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE_S21},
  {"KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE_S11", KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE_S11},
  {"KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE_RETURN", KEY_FUNC_SOURCE_TRACKGEN_MEASTYPE_RETURN},
  {"KEY_FUNC_SOURCE_TRACKGEN_POWER", KEY_FUNC_SOURCE_TRACKGEN_POWER},
  {"KEY_FUNC_SOURCE_TRACKGEN_POWER_ENTER", KEY_FUNC_SOURCE_TRACKGEN_POWER_ENTER},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK", KEY_FUNC_SOURCE_TRACKGEN_NETWORK},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_NETWORK", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_NETWORK},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_NORMALIZE", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_NORMALIZE},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_REFLEVEL", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_REFLEVEL},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_REFLEVEL_ENTER", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_REFLEVEL_ENTER},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_POWER", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_POWER},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_POWER_ENTER", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_POWER_ENTER},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPPOINT", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPPOINT},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPPOINT_ENTER", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPPOINT_ENTER},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_MS", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_MS},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_NS", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_NS},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_S", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_S},
  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_US", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_SWEEPTIME_US},

  {"KEY_FUNC_SOURCE_TRACKGEN_NETWORK_RETURN", KEY_FUNC_SOURCE_TRACKGEN_NETWORK_RETURN},
  {"KEY_FUNC_SOURCE_TRACKGEN_VSWR", KEY_FUNC_SOURCE_TRACKGEN_VSWR},
  {"KEY_FUNC_SOURCE_TRACKGEN_VSWR_VSWR", KEY_FUNC_SOURCE_TRACKGEN_VSWR_VSWR},
  {"KEY_FUNC_SOURCE_TRACKGEN_VSWR_NORMALIZE", KEY_FUNC_SOURCE_TRACKGEN_VSWR_NORMALIZE},
  {"KEY_FUNC_SOURCE_TRACKGEN_VSWR_REFERENCE", KEY_FUNC_SOURCE_TRACKGEN_VSWR_REFERENCE},
  {"KEY_FUNC_SOURCE_TRACKGEN_VSWR_REFERENCE_ENTER", KEY_FUNC_SOURCE_TRACKGEN_VSWR_REFERENCE_ENTER},
  {"KEY_FUNC_SOURCE_TRACKGEN_VSWR_RETURN", KEY_FUNC_SOURCE_TRACKGEN_VSWR_RETURN},
  {"KEY_FUNC_SOURCE_TRACKGEN_RETURN", KEY_FUNC_SOURCE_TRACKGEN_RETURN},
  {"KEY_FUNC_SOURCE_SIGNALGEN", KEY_FUNC_SOURCE_SIGNALGEN},
  {"KEY_FUNC_SOURCE_SIGNALGEN_SIGNALGEN", KEY_FUNC_SOURCE_SIGNALGEN_SIGNALGEN},
  {"KEY_FUNC_SOURCE_SIGNALGEN_FREQ", KEY_FUNC_SOURCE_SIGNALGEN_FREQ},
  {"KEY_FUNC_SOURCE_SIGNALGEN_FREQ_GHZ", KEY_FUNC_SOURCE_SIGNALGEN_FREQ_GHZ},
  {"KEY_FUNC_SOURCE_SIGNALGEN_FREQ_MHZ", KEY_FUNC_SOURCE_SIGNALGEN_FREQ_MHZ},
  {"KEY_FUNC_SOURCE_SIGNALGEN_FREQ_KHZ", KEY_FUNC_SOURCE_SIGNALGEN_FREQ_KHZ},
  {"KEY_FUNC_SOURCE_SIGNALGEN_FREQ_HZ", KEY_FUNC_SOURCE_SIGNALGEN_FREQ_HZ},
  {"KEY_FUNC_SOURCE_SIGNALGEN_POWER", KEY_FUNC_SOURCE_SIGNALGEN_POWER},
  {"KEY_FUNC_SOURCE_SIGNALGEN_POWER_ENTER", KEY_FUNC_SOURCE_SIGNALGEN_POWER_ENTER},
  {"KEY_FUNC_SOURCE_SIGNALGEN_RETURN", KEY_FUNC_SOURCE_SIGNALGEN_RETURN},

  {"KEY_FUNC_DEMOD_DEMOD", KEY_FUNC_DEMOD_DEMOD},
  {"KEY_FUNC_DEMOD_SOUND", KEY_FUNC_DEMOD_SOUND},
  {"KEY_FUNC_DEMOD_SOUND_ENTER", KEY_FUNC_DEMOD_SOUND_ENTER},
  {"KEY_FUNC_DEMOD_RADIOSET", KEY_FUNC_DEMOD_RADIOSET},
  {"KEY_FUNC_DEMOD_RADIOSET_MUSIC", KEY_FUNC_DEMOD_RADIOSET_MUSIC},
  {"KEY_FUNC_DEMOD_RADIOSET_TRAFFIC", KEY_FUNC_DEMOD_RADIOSET_TRAFFIC},
  {"KEY_FUNC_DEMOD_RADIOSET_RETURN", KEY_FUNC_DEMOD_RADIOSET_RETURN},
  {"KEY_FUNC_DEMOD_RETURN", KEY_FUNC_DEMOD_RETURN},
  {"KEY_FUNC_AUX_IMPEDANCE_CONVERSION", KEY_FUNC_AUX_IMPEDANCE_CONVERSION},
  {"KEY_FUNC_AUX_SELF_CHECK", KEY_FUNC_AUX_SELF_CHECK},
  {"KEY_FUNC_AUX_IMPEDANCE_CONVERSION_ENTER", KEY_FUNC_AUX_IMPEDANCE_CONVERSION_ENTER},

  {"KEY_FUNC_MODE_OPTIONS_DEMOD", KEY_FUNC_MODE_OPTIONS_DEMOD},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AUDIO", KEY_FUNC_MODE_OPTIONS_DEMOD_AUDIO},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM", KEY_FUNC_MODE_OPTIONS_DEMOD_AM},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_AM", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_AM},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_GHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_GHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_MHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_MHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_KHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_KHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_HZ", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_CARRIERFREQ_HZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_GHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_GHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_MHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_MHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_KHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_KHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_HZ", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_IFBW_HZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_AM_RETURN", KEY_FUNC_MODE_OPTIONS_DEMOD_AM_RETURN},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM", KEY_FUNC_MODE_OPTIONS_DEMOD_FM},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_FM", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_FM},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_GHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_GHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_MHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_MHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_KHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_KHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_HZ", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_CARRIERFREQ_HZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_GHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_GHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_MHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_MHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_KHZ", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_KHZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_HZ", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_IFBW_HZ},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_FM_RETURN", KEY_FUNC_MODE_OPTIONS_DEMOD_FM_RETURN},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_RETRURN", KEY_FUNC_MODE_OPTIONS_DEMOD_RETRURN},

  {"KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE", KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_FMW", KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_FMW},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_FM", KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_FM},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_AM", KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_AM},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_USB", KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_USB},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_LSB", KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_LSB},
  {"KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_RETURN", KEY_FUNC_MODE_OPTIONS_DEMOD_DEMODMODE_RETURN},
  {"KEY_FUNC_MODE_OPTIONS_DIGITAL_DEMOD", KEY_FUNC_MODE_OPTIONS_DIGITAL_DEMOD},
  {"KEY_FUNC_MODE_OPTIONS_DIGITAL_DEMOD_RETURN", KEY_FUNC_MODE_OPTIONS_DIGITAL_DEMOD_RETURN},

  {"KEY_FUNC_DEMOD_RADIOSET_1", KEY_FUNC_DEMOD_RADIOSET_1},
  {"KEY_FUNC_DEMOD_RADIOSET_1_GHZ", KEY_FUNC_DEMOD_RADIOSET_1_GHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_1_MHZ", KEY_FUNC_DEMOD_RADIOSET_1_MHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_1_KHZ", KEY_FUNC_DEMOD_RADIOSET_1_KHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_1_HZ", KEY_FUNC_DEMOD_RADIOSET_1_HZ},
  {"KEY_FUNC_DEMOD_RADIOSET_MUSIC", KEY_FUNC_DEMOD_RADIOSET_MUSIC},
  {"KEY_FUNC_DEMOD_RADIOSET_MUSIC_GHZ", KEY_FUNC_DEMOD_RADIOSET_MUSIC_GHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_MUSIC_MHZ", KEY_FUNC_DEMOD_RADIOSET_MUSIC_MHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_MUSIC_KHZ", KEY_FUNC_DEMOD_RADIOSET_MUSIC_KHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_MUSIC_HZ", KEY_FUNC_DEMOD_RADIOSET_MUSIC_HZ},
  {"KEY_FUNC_DEMOD_RADIOSET_TRAFFIC", KEY_FUNC_DEMOD_RADIOSET_TRAFFIC},
  {"KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_GHZ", KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_GHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_MHZ", KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_MHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_KHZ", KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_KHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_HZ", KEY_FUNC_DEMOD_RADIOSET_TRAFFIC_HZ},
  {"KEY_FUNC_DEMOD_RADIOSET_2", KEY_FUNC_DEMOD_RADIOSET_2},
  {"KEY_FUNC_DEMOD_RADIOSET_2_GHZ", KEY_FUNC_DEMOD_RADIOSET_2_GHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_2_MHZ", KEY_FUNC_DEMOD_RADIOSET_2_MHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_2_KHZ", KEY_FUNC_DEMOD_RADIOSET_2_KHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_2_HZ", KEY_FUNC_DEMOD_RADIOSET_2_HZ},
  {"KEY_FUNC_DEMOD_RADIOSET_3", KEY_FUNC_DEMOD_RADIOSET_3},
  {"KEY_FUNC_DEMOD_RADIOSET_3_GHZ", KEY_FUNC_DEMOD_RADIOSET_3_GHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_3_MHZ", KEY_FUNC_DEMOD_RADIOSET_3_MHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_3_KHZ", KEY_FUNC_DEMOD_RADIOSET_3_KHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_3_HZ", KEY_FUNC_DEMOD_RADIOSET_3_HZ},
  {"KEY_FUNC_DEMOD_RADIOSET_4", KEY_FUNC_DEMOD_RADIOSET_4},
  {"KEY_FUNC_DEMOD_RADIOSET_4_GHZ", KEY_FUNC_DEMOD_RADIOSET_4_GHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_4_MHZ", KEY_FUNC_DEMOD_RADIOSET_4_MHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_4_KHZ", KEY_FUNC_DEMOD_RADIOSET_4_KHZ},
  {"KEY_FUNC_DEMOD_RADIOSET_4_HZ", KEY_FUNC_DEMOD_RADIOSET_4_HZ},
};

//****************************************
//* 菜单类(继承自tBaseMenu)
//****************************************
class tSysMenu : public tBaseMenu
{
  Q_OBJECT
  public:
    tSysMenu(QString xmlFileName);                 //构造
    ~tSysMenu();                                   //析构

    mainKeyDef* mainKeyTemp;                       //主键临时变量指针
    subKeyDef* subKeyTemp;                         //子键临时变量指针

    bool isUpArrow(int value);                     //上方向键
    bool isRightRpg(int value);                    //右脉冲旋钮
    int getRpgPulse(int value, int value2);        //获取脉冲数
    bool pressedIsEnterKey(int value);             //按下的是确认键
    bool pressedIsArrowKey(int value);             //按下的是方向键
    bool pressedIsRpgKey(int value);               //按下的是脉冲旋钮键
    bool pressedIsMainKey(int value);              //按下的是主键
    bool pressedIsCommonKey(int value);            //按下的是通用键
    bool pressedIsNumberKey(int value);            //按下的是数字键
    bool pressedIsBkspaceKey(int value);           //按下的是回滚键
    bool pressedIsEscKey(int value);               //按下的是取消键
    bool pressedIsUnitKey(int value);              //按下的是单位键

    void getMainKeyPointer(int value);             //获取主键指针
    bool getSubKeyPointer(int value);              //获取子键指针

    void gotoUpLevel(void);                        //返回上级
    void gotoDownLevel(void);                      //进入下级

    int getButtonIndex(int value);                 //获取按键索引
  private:
    void getSystemKeyAndFuncValue(void);           //获取系统键码值
    void getSubSubKey(subKeyDef* key);             //递归获取子键

    int getKeyValue(QString keyValueString);       //获取键值
    int getFuncCode(QString funcCodeString);       //获取功能码
};

#endif
