#ifndef SYSMENU_H_
#define SYSMENU_H_

#include <QtCore/QObject>
#include "basemenu.h"

typedef enum _tagDeviceType_
{
        DEV_TYPE_KEYBOARD = 1,
        DEV_TYPE_RPG,
        DEV_TYPE_TOUCH_SCREEN
} DeviceType;


typedef enum _tagKeyValue_
{
        KEY_R1C1 = 0xC0, KEY_R1C2 = 0xC1, KEY_R1C3 = 0xC2, KEY_R1C4 = 0xC3, KEY_R1C5 = 0xC4, KEY_R1C6 = 0xC5,
        KEY_R2C1 = 0xC6, KEY_R2C2 = 0xC7, KEY_R2C3 = 0xC8, KEY_R2C4 = 0xC9, KEY_R2C5 = 0xCA, KEY_R2C6 = 0xCB,
        KEY_R3C1 = 0xCC, KEY_R3C2 = 0xCD, KEY_R3C3 = 0xCE, KEY_R3C4 = 0xCF, KEY_R3C5 = 0xD0, KEY_R3C6 = 0xD1,
        KEY_R4C1 = 0xD2, KEY_R4C2 = 0xD3, KEY_R4C3 = 0xD4, KEY_R4C4 = 0xD5, KEY_R4C5 = 0xD6, KEY_R4C6 = 0xD7,
        KEY_R5C1 = 0xD8, KEY_R5C2 = 0xD9, KEY_R5C3 = 0xDA, KEY_R5C4 = 0xDB, KEY_R5C5 = 0xDC, KEY_R5C6 = 0xDD,
        KEY_R6C1 = 0xDE, KEY_R6C2 = 0xDF, KEY_R6C3 = 0xE0, KEY_R6C4 = 0xE1, KEY_R6C5 = 0xE2, KEY_R6C6 = 0xE3,
        KEY_R7C1 = 0xE4, KEY_R7C2 = 0xE5, KEY_R7C3 = 0xE6, KEY_R7C4 = 0xE7, KEY_R7C5 = 0xE8, KEY_R7C6 = 0xE9
}KeyValue;

typedef enum _tagRPG_Rotate_Direction_
{
        RPG_RIGHT_ROTATION = 1,
        RPG_LEFT_ROTATION
}RPG_Rotate_Direction;
//****************************************
//* 系统按键定义
//****************************************
///////////////////////////////////////////////////////////////////////////
#define KEY_SUB_MENU1         	        		KEY_R1C1
#define KEY_SUB_MENU2         	        		KEY_R1C2
#define KEY_SUB_MENU3         	        		KEY_R1C3
#define KEY_SUB_MENU4         	       	 		KEY_R1C4
#define KEY_SUB_MENU5							KEY_R1C5
#define KEY_SUB_MENU6							KEY_R1C6

#define KEY_SUB_MENU7							0xff   //eg

#define KEY_MAIN_PRESET				   	        KEY_R2C1
#define KEY_MAIN_FREQ	 				        KEY_R2C5
#define KEY_MAIN_AMPL	 				        KEY_R4C4
#define KEY_MAIN_SWEEP					        KEY_R4C1
#define KEY_MAIN_FCTN					        KEY_R5C1
#define KEY_MAIN_AUX						    KEY_R5C2

#define KEY_MAIN_MOD						    KEY_R5C3
#define KEY_MAIN_LF						        KEY_R5C4
#define KEY_MAIN_RF						        KEY_R5C5

//数字键
#define KEY_NUM_1             	                KEY_R3C4	//0xCF
#define KEY_NUM_2             	                KEY_R3C5   	//0xD0
#define KEY_NUM_3             	                KEY_R3C6 	//0xD1
#define KEY_NUM_4             	                KEY_R2C6  	//0xCB
#define KEY_NUM_5             	                KEY_R3C1 	//0xCC
#define KEY_NUM_6             	                KEY_R3C2  	//0xCD
#define KEY_NUM_7             	                KEY_R2C2	//0xC7
#define KEY_NUM_8             	                KEY_R2C3	//0xC8
#define KEY_NUM_9             	                KEY_R2C4	//0xC9
#define KEY_NUM_0		               	        KEY_R4C6    //0xD7
#define KEY_NUM_DOT           	                KEY_R4C3  	//0xD4
#define KEY_NUM_NEG           	                KEY_R3C3	//0xCE
#define KEY_NUM_BKSPACE          		        KEY_R4C5	//0x

#define KEY_ARROW_UP		     	   	        KEY_R4C5	//0xD3
#define KEY_ARROW_DOWN		        	        KEY_R4C2	//0xD6
#define KEY_NUM_ESC                             KEY_MAIN_PRESET

#define KEY_ARROW_RPG         					0xDFFF
#define KEY_RPG_ENTER							KEY_R5C6	//0xDD

/****************************************************************************
 * 功能码分配：FREQ(频率)
 * KEY_FUNC_FREQ									0x0000 ~ 0x00FF
 ***************************************************************************/
#define KEY_FUNC_FREQ						   0x0000
#define KEY_FUNC_FREQ_GHZ					   0x0001
#define KEY_FUNC_FREQ_MHZ					   0x0002
#define KEY_FUNC_FREQ_KHZ					   0x0003
#define KEY_FUNC_FREQ_HZ					   0x0004
#define KEY_FUNC_FREQREFSET					   0x0005
#define KEY_FUNC_FREQREFSET_GHZ				   0x0006
#define KEY_FUNC_FREQREFSET_MHZ				   0x0007
#define KEY_FUNC_FREQREFSET_KHZ				   0x0008
#define KEY_FUNC_FREQREFSET_HZ				   0x0009
#define KEY_FUNC_FREQREFSTATE				   0x000A
#define KEY_FUNC_FREQREFSTATE_RETURN		   0x000B
#define KEY_FUNC_FREQREFSTATE_OFF			   0x000C
#define KEY_FUNC_FREQREFSTATE_ON			   0x000D
#define KEY_FUNC_FREQOFFSET					   0x000E
#define KEY_FUNC_FREQOFFSET_GHZ				   0x000F
#define KEY_FUNC_FREQOFFSET_MHZ				   0x0010
#define KEY_FUNC_FREQOFFSET_KHZ				   0x0011
#define KEY_FUNC_FREQOFFSET_HZ				   0x0012
#define KEY_FUNC_FREQMULTIPLIER				   0x0013
#define KEY_FUNC_FREQMULTIPLIER_ENTER		   0x0014
#define KEY_FUNC_FREQREF10M					   0x0015
#define KEY_FUNC_FREQREF10M_RETURN			   0x0016
#define KEY_FUNC_FREQREF10M_INTERRIOR		   0x0017
#define KEY_FUNC_FREQREF10M_EXTERNAL		   0x0018

/****************************************************************************
 * 功能码分配：AMPL(幅度)
 * KEY_FUNC_AMPL									0x0100 ~ 0x01FF
 ***************************************************************************/
#define KEY_FUNC_AMPL						   0x0100
#define KEY_FUNC_AMPL_DBM					   0x0101
#define KEY_FUNC_AMPL_DBUV					   0x0112
#define KEY_FUNC_AMPL_MV                       0x0113
#define KEY_FUNC_AMPLREFSET					   0x0102
#define KEY_FUNC_AMPLREFSET_DBM				   0x0103
#define KEY_FUNC_AMPLREFSTATE				   0x0104
#define KEY_FUNC_AMPLREFSTATE_RETURN		   0x0105
#define KEY_FUNC_AMPLREFSTATE_OFF			   0x0106
#define KEY_FUNC_AMPLREFSTATE_ON			   0x0107
#define KEY_FUNC_AMPLOFFSET					   0x0108
#define KEY_FUNC_AMPLOFFSET_DBM				   0x0109
#define KEY_FUNC_AMPLRESPONSE	  	           0x010A
#define KEY_FUNC_AMPLRESPONSE_RETURN   		   0x010B
#define KEY_FUNC_AMPLRESPONSE_FAST             0x010C
#define KEY_FUNC_AMPLRESPONSE_SLOW             0x010D
#define KEY_FUNC_AMPL_ALC_STAT                 0x010E
#define KEY_FUNC__AMPL_ALC_RETURN              0x010F
#define KEY_FUNC__AMPL_ALC_OFF                 0x0110
#define KEY_FUNC__AMPL_ALC_ON                  0x0111
#define KEY_FUNC_AMPL_CABLE					   0x0114
#define KEY_FUNC_AMPL_CABLE_DB				   0x0115

/****************************************************************************
 * 功能码分配：SWEEP(扫描)
 * KEY_FUNC_SWEEP									0x0200 ~ 0x02FF
 ***************************************************************************/
#define	KEY_FUNC_SWEEP_MODE					   0x0200
#define	KEY_FUNC_SWEEP_MODE_RETURN			   0x0201
#define	KEY_FUNC_SWEEP_MODE_OFF				   0x0202
#define KEY_FUNC_SWEEP_MODE_FREQ			   0x0203
//#define KEY_FUNC_SWEEP_MODE_FREQ_RETURN        0x0251  //zcp add
//#define KEY_FUNC_SWEEP_MODE_FREQ_OFF           0x0252  //zcp add
//#define KEY_FUNC_SWEEP_MODE_FREQ_ON            0x0253  //zcp add
#define	KEY_FUNC_SWEEP_MODE_AMPL			   0x0204
//#define KEY_FUNC_SWEEP_MODE_AMPL_RETURN        0x0254  //zcp add
//#define KEY_FUNC_SWEEP_MODE_AMPL_OFF           0x0255  //zcp add
//#define KEY_FUNC_SWEEP_MODE_AMPL_ON            0x0256  //zcp add
#define	KEY_FUNC_SWEEP_MODE_FREQAMPL		   0x0205
#define	KEY_FUNC_SWEEP_TYPE					   0x0206
#define KEY_FUNC_SWEEP_TYPE_RETURN			   0X0207
#define	KEY_FUNC_SWEEP_TYPE_LIST			   0x0208
#define	KEY_FUNC_SWEEP_TYPE_STEP			   0x0209
#define	KEY_FUNC_SWEEP_REPEAT				   0x020A
#define	KEY_FUNC_SWEEP_REPEAT_RETURN		   0x020B
#define	KEY_FUNC_SWEEP_REPEAT_SINGLE		   0x020C
#define	KEY_FUNC_SWEEP_REPEAT_CONT			   0x020D
#define	KEY_FUNC_SWEEP_SINGLETRIGGER		   0x020E
#define	KEY_FUNC_SWEEP_CONFIGSTEP			   0x020F
#define	KEY_FUNC_SWEEP_STEP_RETURN			   0x0210
#define	KEY_FUNC_SWEEP_STEP_FREQSTART		   0x0211
#define	KEY_FUNC_SWEEP_STEP_FREQSTART_GHZ	   0x0212
#define	KEY_FUNC_SWEEP_STEP_FREQSTART_MHZ	   0x0213
#define	KEY_FUNC_SWEEP_STEP_FREQSTART_KHZ	   0x0214
#define	KEY_FUNC_SWEEP_STEP_FREQSTART_HZ	   0x0215
#define	KEY_FUNC_SWEEP_STEP_FREQSTOP		   0x0216
#define	KEY_FUNC_SWEEP_STEP_FREQSTOP_GHZ	   0x0217
#define	KEY_FUNC_SWEEP_STEP_FREQSTOP_MHZ	   0x0218
#define	KEY_FUNC_SWEEP_STEP_FREQSTOP_KHZ	   0x0219
#define	KEY_FUNC_SWEEP_STEP_FREQSTOP_HZ		   0x021A
#define	KEY_FUNC_SWEEP_STEP_AMPLSTART		   0x021B
#define	KEY_FUNC_SWEEP_STEP_AMPLSTART_DBM	   0x021C
#define	KEY_FUNC_SWEEP_STEP_AMPLSTOP		   0x021D
#define	KEY_FUNC_SWEEP_STEP_AMPLSTOP_DBM	   0x021E
#define	KEY_FUNC_SWEEP_STEP_MORE			   0x021F
#define	KEY_FUNC_SWEEP_STEP_MORE_RETURN		   0x0220
#define	KEY_FUNC_SWEEP_STEP_MORE_POINTS		   0x0221
#define	KEY_FUNC_SWEEP_STEP_MORE_POINTS_ENTER  0x0222
#define	KEY_FUNC_SWEEP_STEP_MORE_STEPDWELL	   0x0223
#define	KEY_FUNC_SWEEP_STEP_MORE_STEPDWELL_S   0x0224
#define	KEY_FUNC_SWEEP_STEP_MORE_STEPDWELL_MS  0x0225
#define	KEY_FUNC_SWEEP_MORE					   0x0226
#define	KEY_FUNC_SWEEP_MORE_RETURN			   0x0227
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST		   0x0228
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_RETURN  0x0229
//#define KEY_FUNC_SWEEP_MORE_CONFIGLIST_SELECTITEM  0x022A
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM				0x022B
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_GHZS		0x022C
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_MHZMS		0x022D
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_KHZNS		0x022E
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_HZDBM		0x022F

#define KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DOWNLOAD		0x0230
#define KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DOWNLOAD_ENTER	0x0257
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_INSERTROW			0x0231
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_DELETEROW			0x0232
//#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_GOTOROW				0x0233
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE					0x0234
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_RETURN			0x0235
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_LOADSTORE		0x0236
//#define KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_GOTOROW			0x0237
#define KEY_FUNC_SWEEP_MORE_CONFIGLIST_GOTOROW			0x0237
//#define KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_GOTOROW_ENTER	0x0238
#define KEY_FUNC_SWEEP_MORE_CONFIGLIST_GOTOROW_ENTER	0x0238
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_PRESETLIST		0x0239
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_PRESETLIST_YES	0x023A
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_PRESETLIST_NO	0x023B
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_INSERTITEM		0x023C
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DELETEITEM		0x023D
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE		0x023E
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE_RETURN	0x023F
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE_LIST	    0x0240
#define	KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE_STEP	    0x0241


#define	KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION					0x0242
#define	KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION_RETURN			0x0243
#define	KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION_DOWN				0x0244
#define	KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION_UP				0x0245
#define	KEY_FUNC_SWEEP_MORE_SWEEPRETRACE					0x0246
#define	KEY_FUNC_SWEEP_MORE_SWEEPRETRACE_RETURN				0x0247
#define	KEY_FUNC_SWEEP_MORE_SWEEPRETRACE_OFF				0x0248
#define	KEY_FUNC_SWEEP_MORE_SWEEPRETRACE_ON					0x0249

#define KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER  	            	0x024A
#define KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_RETURN		    	0x024B
#define KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_FREERUN  			0x024C
#define KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_TRIGGERKEY			0x024D
#define KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_BUS		        0x024E
#define KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_EXT  			    0x024F
#define KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_TIMETRIGGER	    0x0250


/****************************************************************************
 * 功能码分配：ANALOG(调制-->模拟)
 * KEY_FUNC_FCTN_ANALOG									0x0300 ~ 0x03FF
 ***************************************************************************/
#define KEY_FUNC_FCTN_ANALOG 				        0x0300
#define KEY_FUNC_FCTN_ANALOG_AM				        0x0301
#define KEY_FUNC_FCTN_ANALOG_AM_STATE		        0x0302
#define KEY_FUNC_FCTN_ANALOG_AM_STATE_RETURN	    0x0303
#define KEY_FUNC_FCTN_ANALOG_AM_STATE_ON		    0x0304
#define KEY_FUNC_FCTN_ANALOG_AM_STATE_OFF	        0x0305
#define KEY_FUNC_FCTN_ANALOG_AM_DEPTH		        0x0306
#define KEY_FUNC_FCTN_ANALOG_AM_DEPTH_PERCENT       0x0307
#define KEY_FUNC_FCTN_ANALOG_AM_RATE			    0x0308
#define KEY_FUNC_FCTN_ANALOG_AM_RATE_KHZ 	        0x0309
#define KEY_FUNC_FCTN_ANALOG_AM_RATE_HZ		        0x030A
#define KEY_FUNC_FCTN_ANALOG_AM_RETURN		        0x030B
#define KEY_FUNC_FCTN_ANALOG_FM				        0x030C
#define KEY_FUNC_FCTN_ANALOG_FM_STATE		        0x030D
#define KEY_FUNC_FCTN_ANALOG_FM_STATE_RETURN	    0x030E
#define KEY_FUNC_FCTN_ANALOG_FM_STATE_ON		    0x030F
#define KEY_FUNC_FCTN_ANALOG_FM_STATE_OFF	        0x0310
#define KEY_FUNC_FCTN_ANALOG_FM_DEVIATION	        0x0311
#define KEY_FUNC_FCTN_ANALOG_FM_DEVIATION_MHZ       0x0312
#define KEY_FUNC_FCTN_ANALOG_FM_DEVIATION_KHZ       0x0313
#define KEY_FUNC_FCTN_ANALOG_FM_DEVIATION_HZ        0x0314
#define KEY_FUNC_FCTN_ANALOG_FM_RATE			    0x0315
#define KEY_FUNC_FCTN_ANALOG_FM_RATE_KHZ		    0x0316
#define KEY_FUNC_FCTN_ANALOG_FM_RATE_HZ		        0x0317
#define KEY_FUNC_FCTN_ANALOG_FM_RETURN		        0x0318
#define KEY_FUNC_FCTN_ANALOG_PM				        0x0319
#define KEY_FUNC_FCTN_ANALOG_PM_STATE		        0x031A
#define KEY_FUNC_FCTN_ANALOG_PM_STATE_RETURN	    0x031B
#define KEY_FUNC_FCTN_ANALOG_PM_STATE_ON		    0x031C
#define KEY_FUNC_FCTN_ANALOG_PM_STATE_OFF	        0x031D
#define KEY_FUNC_FCTN_ANALOG_PM_PHASE		        0x031E
#define KEY_FUNC_FCTN_ANALOG_PM_PHASE_ANGLE	        0x031F
#define KEY_FUNC_FCTN_ANALOG_PM_RATE			    0x0320
#define KEY_FUNC_FCTN_ANALOG_PM_RATE_KHZ		    0x0321
#define KEY_FUNC_FCTN_ANALOG_PM_RATE_HZ		        0x0322
#define KEY_FUNC_FCTN_ANALOG_PM_RETURN		        0x0323
#define KEY_FUNC_FCTN_ANALOG_RETURN			        0x0324
#define KEY_FUNC_FCTN_ANALOG_SOURCE					0x0325
#define KEY_FUNC_FCTN_ANALOG_SOURCE_RETURN			0x0326
#define KEY_FUNC_FCTN_ANALOG_SOURCE_INTERNAL		0x0327
#define KEY_FUNC_FCTN_ANALOG_SOURCE_EXTERNAL		0x0328



/****************************************************************************
 * 功能码分配：DIGITAL(调制-->数字)
 * KEY_FUNC_FCTN_DIGITAL							0x100A0000
 * KEY_FUNC_FCTN_DIGITAL_RETURN						0x100A0001
 * KEY_FUNC_FCTN_DIGITAL_TYPE						0x100A0002 ~ 0x100A0FFF
 * KEY_FUNC_FCTN_DIGITAL_PARAMETER					0x100A1000 ~ 0x100A1FFF
 * KEY_FUNC_FCTN_DIGITAL_DATASOURCE					0x100A2000 ~ 0x100A2FFF
 * KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE					0x100A3000 ~ 0x100A3FFF
 * KEY_FUNC_FCTN_DIGITAL_MORE						0x100A4000
 * KEY_FUNC_FCTN_DIGITAL_MORE_RETURN				0x100A4001
 * KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT			0x100A4002 ~ 0x100A4FFF
 * KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA			0x100A5000 ~ 0x100A5FFF
 ***************************************************************************/
#define KEY_FUNC_FCTN_DIGITAL						0x100A0000
#define KEY_FUNC_FCTN_DIGITAL_RETURN				0x100A0001
/***************************************************************************
 * KEY_FUNC_FCTN_DIGITAL_TYPE						0x100A0002 ~ 0x100A0FFF
 **************************************************************************/
#define KEY_FUNC_FCTN_DIGITAL_STATE						0x100A001B
#define KEY_FUNC_FCTN_DIGITAL_STATE_RETURN				0x100A001C
#define KEY_FUNC_FCTN_DIGITAL_STATE_ON					0x100A001D
#define KEY_FUNC_FCTN_DIGITAL_STATE_OFF					0x100A001E

#define KEY_FUNC_FCTN_DIGITAL_TYPE						0x100A0002
#define KEY_FUNC_FCTN_DIGITAL_TYPE_RETURN				0x100A0003
#define KEY_FUNC_FCTN_DIGITAL_TYPE_ASK					0x100A0004

#define KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_RETURN			0x100A001F
#define KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_2ASK				0x100A0020
#define KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_4ASK				0x100A0021
#define KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_8ASK				0x100A0022

#define KEY_FUNC_FCTN_DIGITAL_TYPE_FSK					0x100A0005
#define KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_RETURN			0x100A0006
#define KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_MSK				0x100A0007
#define KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_2FSK				0x100A0008
#define KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_4FSK				0x100A0009

#define KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_8FSK				0x100A0023

#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK					0x100A000A
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_RETURN			0x100A000B

#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_2PSK				0x100A0024
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_4PSK				0x100A0025
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_8PSK				0x100A0026

#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_BPSK				0x100A000C
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_QPSK				0x100A000D
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_OQPSK			0x100A000E
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_PI2DBPSK			0x100A000F
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE				0x100A0010
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_RETURN		0x100A0011
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_PI4QPSK		0x100A0012
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_PI4DQPSK	0x100A0013
#define KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_8PSK		0x100A0014
#define KEY_FUNC_FCTN_DIGITAL_TYPE_QAM					0x100A0015
#define KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_RETURN			0x100A0016
#define KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM16			0x100A0017
#define KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM32			0x100A0018
#define KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM64			0x100A0019
#define KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM128			0x100A001A

/***************************************************************************
 * KEY_FUNC_FCTN_DIGITAL_PARAMETER					0x100A1000 ~ 0x100A1FFF
 **************************************************************************/
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER						0x100A1000
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_RETURN				0x100A1001
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_ASKDEEP				0x100A1002
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_ASKDEEP_PERCENT		0x100A1003
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET			0x100A1004
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET_MHZ		0x100A1005
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET_KHZ		0x100A1006
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET_HZ		0x100A1007
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_PSKDEVI				0x100A1008
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_PSKDEVI_ANGLE		0x100A1009
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_RATE				0x100A100A
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_RATE_KHZ			0x100A100B
#define KEY_FUNC_FCTN_DIGITAL_PARAMETER_RATE_HZ				0x100A100C

#define KEY_FUNC_FCTN_DIGITAL_SOURCE						0x100A10F0
#define KEY_FUNC_FCTN_DIGITAL_SOURCE_RETURN					0x100A10F1
#define KEY_FUNC_FCTN_DIGITAL_SOURCE_INTERNAL				0x100A10F2
#define KEY_FUNC_FCTN_DIGITAL_SOURCE_EXTERNAL				0x100A10F3
#define KEY_FUNC_FCTN_DIGITAL_MORE							0x100A10F4
#define KEY_FUNC_FCTN_DIGITAL_MORE_RETURN					0x100A10F5
#define KEY_FUNC_FCTN_DIGITAL_MORE_LOAD						0x100A10F6
#define KEY_FUNC_FCTN_DIGITAL_MORE_LOAD_ENTER				0x100A10F7
/***************************************************************************
 * KEY_FUNC_FCTN_DIGITAL_DATASOURCE					0x100A2000 ~ 0x100A2FFF
 **************************************************************************/
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE				0x100A2000
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_RETURN			0x100A2001
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_ALL0			0x100A2002
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_ALL1			0x100A2003
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS			0x100A2004
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_RETURN	0x100A2005
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS7		0x100A2006
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS9		0x100A2007
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS11	0x100A2008
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS15	0x100A2009
#define KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PATTERN		0x100A200A
/***************************************************************************
 * KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE					0x100A3000 ~ 0x100A3FFF
 **************************************************************************/
#define KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE				0x100A3000
#define KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE_SYMLS			0x100A3001
#define KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE_KSYMLS			0x100A3002
#define KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE_MSYMLS			0x100A3003
/***************************************************************************
 * KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT			0x100A4002 ~ 0x100A4FFF
 **************************************************************************/
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT					0x100A4002
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_RETURN			0x100A4003
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_ROOTCOSINE		0x100A4004
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_COSINE			0x100A4005
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_GAUSSPURE		0x100A4006
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_GAUSSFSK		0x100A4007
/***************************************************************************
 * KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA			0x100A5000 ~ 0x100A5FFF
 **************************************************************************/
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA					0x100A5000
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA_RETURN			0x100A5001
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA_BT				0x100A5003
#define KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA_STOPFREQ			0x100A5004





/****************************************************************************
 * 功能码分配：PLUSE(调制-->脉冲)
 * KEY_FUNC_FCTN_PLUSE									0x100E0000 ~ 0x100EFFFF
 ***************************************************************************/
#define KEY_FUNC_FCTN_PLUSE						0x100E0000
#define KEY_FUNC_FCTN_PLUSE_RETURN				0x100E0001
#define KEY_FUNC_FCTN_PLUSE_STATE				0x100E0002
#define KEY_FUNC_FCTN_PLUSE_STATE_RETURN		0x100E0003
#define KEY_FUNC_FCTN_PLUSE_STATE_ON			0x100E0004
#define KEY_FUNC_FCTN_PLUSE_STATE_OFF			0x100E0005
#define KEY_FUNC_FCTN_PLUSE_METHOD				0x100E0006
#define KEY_FUNC_FCTN_PLUSE_METHOD_RETURN		0x100E0007
#define KEY_FUNC_FCTN_PLUSE_METHOD_AUTO			0x100E0008
#define KEY_FUNC_FCTN_PLUSE_METHOD_TRIG			0x100E0009
//#define KEY_FUNC_FCTN_PLUSE_METHOD_EXTER		0x100E000A
#define KEY_FUNC_FCTN_PLUSE_PERIOD				0x100E000B
#define KEY_FUNC_FCTN_PLUSE_PERIOD_S  			0x100E000C
#define KEY_FUNC_FCTN_PLUSE_PERIOD_MS			0x100E000D
#define KEY_FUNC_FCTN_PLUSE_PERIOD_US			0x100E000E
#define KEY_FUNC_FCTN_PLUSE_PERIOD_NS			0x100E000F
#define KEY_FUNC_FCTN_PLUSE_WIDTH				0x100E0010
#define KEY_FUNC_FCTN_PLUSE_WIDTH_S				0x100E0011
#define KEY_FUNC_FCTN_PLUSE_WIDTH_MS			0x100E0012
#define KEY_FUNC_FCTN_PLUSE_WIDTH_US			0x100E0013
#define KEY_FUNC_FCTN_PLUSE_WIDTH_NS			0x100E0014
#define KEY_FUNC_FCTN_PLUSE_SOURCE				0x100E0015
#define KEY_FUNC_FCTN_PLUSE_SOURCE_RETURN		0x100E0016
#define KEY_FUNC_FCTN_PLUSE_SOURCE_INTERNAL		0x100E0017
#define KEY_FUNC_FCTN_PLUSE_SOURCE_EXTERNAL		0x100E0018

/****************************************************************************
 * 功能码分配：EXTRF(调制-->上变频功能)
 * KEY_FUNC_FCTN_EXTRF								0x100D0000 ~ 0x100DFFFF
 ***************************************************************************/
#define KEY_FUNC_FCTN_EXTRF		     		0x100D0000
#define KEY_FUNC_FCTN_EXTRF_RETURN	    	0x100D0001
#define KEY_FUNC_FCTN_EXTRF_EXTRF		    0x100D0002
#define KEY_FUNC_FCTN_EXTRF_EXTRF_INT		0x100D0003
#define KEY_FUNC_FCTN_EXTRF_EXTRF_EXT		0x100D0004
#define KEY_FUNC_FCTN_EXTRF_EXTRF_RETURN  	0x100D0005
#define KEY_FUNC_FCTN_EXTRF_FREQ		    0x100D0006
#define KEY_FUNC_FCTN_EXTRF_FREQ_GHZ		0x100D0007
#define KEY_FUNC_FCTN_EXTRF_FREQ_MHZ		0x100D0008
#define KEY_FUNC_FCTN_EXTRF_FREQ_KHZ		0x100D0009
#define KEY_FUNC_FCTN_EXTRF_FREQ_HZ			0x100D000A


/****************************************************************************
 * 功能码分配：LF(调制-->低频输出)
 * KEY_FUNC_FCTN_LF								0x100C0000 ~ 0x100CFFFF
 ***************************************************************************/
#define KEY_FUNC_FCTN_LF						0x100C0061
#define KEY_FUNC_FCTN_LF_RETURN					0x100C0062

#define KEY_FUNC_FCTN_LF_STATE					0x100C0073
#define KEY_FUNC_FCTN_LF_STATE_RETURN			0x100C0074
#define KEY_FUNC_FCTN_LF_STATE_ON				0x100C0075
#define KEY_FUNC_FCTN_LF_STATE_OFF				0x100C0076

#define KEY_FUNC_FCTN_LF_SOURCE					0x100C0063

#define KEY_FUNC_FCTN_LF_SOURCE_RETURN			0x100C0072
//#define KEY_FUNC_FCTN_LF_WAVEFORM_RETURN		0x100C0064
#define KEY_FUNC_FCTN_LF_WAVEFORM_SINE			0x100C0065
#define KEY_FUNC_FCTN_LF_WAVEFORM_SQUARE		0x100C0066
#define KEY_FUNC_FCTN_LF_WAVEFORM_TRIANGULAR	0x100C0067
#define KEY_FUNC_FCTN_LF_WAVEFORM_SAWTOOTH		0x100C0068
#define KEY_FUNC_FCTN_LF_SOURCE_SINC			0x100C0077
#define KEY_FUNC_FCTN_LF_AMPL					0x100C0069
#define KEY_FUNC_FCTN_LF_AMPL_VPP				0x100C006A
#define KEY_FUNC_FCTN_LF_AMPL_MVPP				0x100C006B
#define KEY_FUNC_FCTN_LF_FREQ					0x100C006C
#define KEY_FUNC_FCTN_LF_FREQ_MHZ				0x100C006D
#define KEY_FUNC_FCTN_LF_FREQ_KHZ				0x100C006E
#define KEY_FUNC_FCTN_LF_FREQ_HZ				0x100C006F
//#define KEY_FUNC_FCTN_LF_SOURCE_INTERNAL		0x100C0070
//#define KEY_FUNC_FCTN_LF_SOURCE_EXTERNAL		0x100C0071


/****************************************************************************
 * 功能码分配：DRG(调制-->线性调频)
 * KEY_FUNC_FCTN_DRG								0x100F0000 ~ 0x100FFFFF
 ***************************************************************************/
#define KEY_FUNC_FCTN_DRG							0x100F0000
#define KEY_FUNC_FCTN_DRG_RETURN					0x100F0001
#define KEY_FUNC_FCTN_DRG_STATE						0x100F0002
#define KEY_FUNC_FCTN_DRG_STATE_RETURN				0x100F0003
#define KEY_FUNC_FCTN_DRG_STATE_ON					0x100F0004
#define KEY_FUNC_FCTN_DRG_STATE_OFF					0x100F0005
#define KEY_FUNC_FCTN_DRG_UPLIMIT					0x100F0006
#define KEY_FUNC_FCTN_DRG_UPLIMIT_GHZ				0x100F0007
#define KEY_FUNC_FCTN_DRG_UPLIMIT_MHZ				0x100F0008
#define KEY_FUNC_FCTN_DRG_UPLIMIT_KHZ				0x100F0009
#define KEY_FUNC_FCTN_DRG_UPLIMIT_HZ				0x100F000A
#define KEY_FUNC_FCTN_DRG_DOWNLIMIT					0x100F000B
#define KEY_FUNC_FCTN_DRG_DOWNLIMIT_GHZ				0x100F000C
#define KEY_FUNC_FCTN_DRG_DOWNLIMIT_MHZ				0x100F000D
#define KEY_FUNC_FCTN_DRG_DOWNLIMIT_KHZ				0x100F000E
#define KEY_FUNC_FCTN_DRG_DOWNLIMIT_HZ				0x100F000F
#define KEY_FUNC_FCTN_DRG_POINTS					0x100F0010
#define KEY_FUNC_FCTN_DRG_POINTS_ENTER				0x100F0011
#define KEY_FUNC_FCTN_DRG_MORE						0x100F0012
#define KEY_FUNC_FCTN_DRG_MORE_RETURN				0x100F0013
#define KEY_FUNC_FCTN_DRG_MORE_RATE					0x100F0014
#define KEY_FUNC_FCTN_DRG_MORE_RATE_MS			0x100F0015
#define KEY_FUNC_FCTN_DRG_MORE_RATE_US			0x100F0016
#define KEY_FUNC_FCTN_DRG_MORE_RATE_NS			0x100F0017
#define KEY_FUNC_FCTN_DRG_MORE_WORKMODE				0x100F0018
#define KEY_FUNC_FCTN_DRG_MORE_WORKMODE_RETURN		0x100F0019
#define KEY_FUNC_FCTN_DRG_MORE_WORKMODE_NORMAL		0x100F001A
#define KEY_FUNC_FCTN_DRG_MORE_WORKMODE_POSITIVE	0x100F001B
#define KEY_FUNC_FCTN_DRG_MORE_WORKMODE_NEGATIVE	0x100F001C

/****************************************************************************
 * 功能码分配：AUX(系统辅助)
 * KEY_FUNC_AUX								0x100B0000 ~ 0x100BFFFF
 ***************************************************************************/
#define KEY_FUNC_AUX_LAN						0x100B0000
#define KEY_FUNC_AUX_LAN_IP						0x100B0011
#define KEY_FUNC_AUX_LAN_IP_ENTER				0x100B0012
#define KEY_FUNC_AUX_LAN_MASK					0x100B0021
#define KEY_FUNC_AUX_LAN_MASK_ENTER				0x100B0022
#define KEY_FUNC_AUX_LAN_GATEWAY				0x100B0031
#define KEY_FUNC_AUX_LAN_GATEWAY_ENTER			0x100B0032
#define KEY_FUNC_AUX_LAN_RETURN					0x100B0040

#define KEY_FUNC_AUX_SCPI  				   		0x100B0041
#define KEY_FUNC_AUX_SCPI_RETURN				0x100B0042
#define KEY_FUNC_AUX_SCPI_ON  			    	0x100B0043
#define KEY_FUNC_AUX_SCPI_OFF					0x100B0044

#define KEY_FUNC_AUX_LANGUAGE               	0x100B0045
#define KEY_FUNC_AUX_LANGUAGE_RETURN            0x100B0046
#define KEY_FUNC_AUX_LANGUAGE_CHINESE           0x100B0047
#define KEY_FUNC_AUX_LANGUAGE_ENGLISH           0x100B0048

#define KEY_FUNC_AUX_SERVICE					0x100B0050
#define KEY_FUNC_AUX_SERVICE_RETURN				0x100B0051
#define KEY_FUNC_AUX_SERVICE_EVALUATE			0x100B0052
#define KEY_FUNC_AUX_SERVICE_EVALUATE_RETURN	0x100B0053
#define KEY_FUNC_AUX_SERVICE_EVALUATE_ON		0x100B0054
#define KEY_FUNC_AUX_SERVICE_EVALUATE_OFF		0x100B0055
#define KEY_FUNC_AUX_SERVICE_LANMACADDR			0x100B0056
#define KEY_FUNC_AUX_SERVICE_LANMACADDR_ENTER	0x100B0057

//impedance conversion

//****************************************
//* 系统对应关系定义
//****************************************
struct valueListDef
{
  const char* name;
  int value;
};

static struct valueListDef valueList[] =
{
  {"KEY_SUB_MENU1", KEY_SUB_MENU1},
  {"KEY_SUB_MENU2", KEY_SUB_MENU2},
  {"KEY_SUB_MENU3", KEY_SUB_MENU3},
  {"KEY_SUB_MENU4", KEY_SUB_MENU4},
  {"KEY_SUB_MENU5", KEY_SUB_MENU5},
  {"KEY_SUB_MENU6", KEY_SUB_MENU6},

  //-----------------------ADD BY STARX------------------------
  {"KEY_MAIN_FREQ",KEY_MAIN_FREQ},
  {"KEY_MAIN_AMPL",KEY_MAIN_AMPL},
  {"KEY_MAIN_SWEEP",KEY_MAIN_SWEEP},
  {"KEY_MAIN_FCTN",KEY_MAIN_FCTN},
  {"KEY_MAIN_AUX",KEY_MAIN_AUX},
  {"KEY_MAIN_MOD",KEY_MAIN_MOD},
  {"KEY_MAIN_LF",KEY_MAIN_LF},
  {"KEY_MAIN_RF",KEY_MAIN_RF},
  {"KEY_MAIN_PRESET",KEY_MAIN_PRESET},
};

//方向键集合
static int ARROWKEYLIST[] =
{
  KEY_ARROW_UP, KEY_ARROW_DOWN,\
};

//RPG键集合
static int RPGKEYLIST[] =
{
  KEY_ARROW_RPG,\
};


//主键集合
static int MAINKEYLIST[] =
{
  KEY_MAIN_FREQ, KEY_MAIN_AMPL, \
  KEY_MAIN_SWEEP, KEY_MAIN_PRESET,\
  KEY_MAIN_FCTN, KEY_MAIN_AUX,\
  KEY_MAIN_MOD, KEY_MAIN_LF, KEY_MAIN_RF,\
};

//通用键集合
static int COMMONKEYLIST[] =
{
  KEY_SUB_MENU1, KEY_SUB_MENU2, KEY_SUB_MENU3, KEY_SUB_MENU4, KEY_SUB_MENU5, KEY_SUB_MENU6,
};

//数字键集合
static int NUMBERKEYLIST[] =
{
  KEY_NUM_0, KEY_NUM_1, KEY_NUM_2, KEY_NUM_3, KEY_NUM_4, \
  KEY_NUM_5, KEY_NUM_6, KEY_NUM_7, KEY_NUM_8, KEY_NUM_9, \
  KEY_NUM_DOT, KEY_NUM_NEG, \
};


//功能码集合
static struct valueListDef codeList[] =
{
	{"KEY_FUNC_FREQ",KEY_FUNC_FREQ},
	{"KEY_FUNC_FREQ_GHZ",KEY_FUNC_FREQ_GHZ},
	{"KEY_FUNC_FREQ_MHZ",KEY_FUNC_FREQ_MHZ},
	{"KEY_FUNC_FREQ_KHZ",KEY_FUNC_FREQ_KHZ},
	{"KEY_FUNC_FREQ_HZ",KEY_FUNC_FREQ_HZ},
	{"KEY_FUNC_FREQREFSET",KEY_FUNC_FREQREFSET},
	{"KEY_FUNC_FREQREFSET_GHZ",KEY_FUNC_FREQREFSET_GHZ},
	{"KEY_FUNC_FREQREFSET_MHZ",KEY_FUNC_FREQREFSET_MHZ},
	{"KEY_FUNC_FREQREFSET_KHZ",KEY_FUNC_FREQREFSET_KHZ},
	{"KEY_FUNC_FREQREFSET_HZ",KEY_FUNC_FREQREFSET_HZ},
	{"KEY_FUNC_FREQREFSTATE",KEY_FUNC_FREQREFSTATE},
	{"KEY_FUNC_FREQREFSTATE_RETURN",KEY_FUNC_FREQREFSTATE_RETURN},
	{"KEY_FUNC_FREQREFSTATE_OFF",KEY_FUNC_FREQREFSTATE_OFF},
	{"KEY_FUNC_FREQREFSTATE_ON",KEY_FUNC_FREQREFSTATE_ON},
	{"KEY_FUNC_FREQOFFSET",KEY_FUNC_FREQOFFSET},
	{"KEY_FUNC_FREQOFFSET_GHZ",KEY_FUNC_FREQOFFSET_GHZ},
	{"KEY_FUNC_FREQOFFSET_MHZ",KEY_FUNC_FREQOFFSET_MHZ},
	{"KEY_FUNC_FREQOFFSET_KHZ",KEY_FUNC_FREQOFFSET_KHZ},
	{"KEY_FUNC_FREQOFFSET_HZ",KEY_FUNC_FREQOFFSET_HZ},
	{"KEY_FUNC_FREQMULTIPLIER",KEY_FUNC_FREQMULTIPLIER},
	{"KEY_FUNC_FREQMULTIPLIER_ENTER",KEY_FUNC_FREQMULTIPLIER_ENTER},
	{"KEY_FUNC_FREQREF10M",KEY_FUNC_FREQREF10M},
	{"KEY_FUNC_FREQREF10M_RETURN",KEY_FUNC_FREQREF10M_RETURN},
	{"KEY_FUNC_FREQREF10M_INTERRIOR",KEY_FUNC_FREQREF10M_INTERRIOR},
	{"KEY_FUNC_FREQREF10M_EXTERNAL",KEY_FUNC_FREQREF10M_EXTERNAL},

	{"KEY_FUNC_AMPL",KEY_FUNC_AMPL},
	{"KEY_FUNC_AMPL_DBM",KEY_FUNC_AMPL_DBM},
	{"KEY_FUNC_AMPL_DBUV",KEY_FUNC_AMPL_DBUV},
	{"KEY_FUNC_AMPL_MV",KEY_FUNC_AMPL_MV},
	{"KEY_FUNC_AMPLREFSET",KEY_FUNC_AMPLREFSET},
	{"KEY_FUNC_AMPLREFSET_DBM",KEY_FUNC_AMPLREFSET_DBM},
	{"KEY_FUNC_AMPLREFSTATE",KEY_FUNC_AMPLREFSTATE},
	{"KEY_FUNC_AMPLREFSTATE_RETURN",KEY_FUNC_AMPLREFSTATE_RETURN},
	{"KEY_FUNC_AMPLREFSTATE_OFF",KEY_FUNC_AMPLREFSTATE_OFF},
	{"KEY_FUNC_AMPLREFSTATE_ON",KEY_FUNC_AMPLREFSTATE_ON},
	{"KEY_FUNC_AMPLOFFSET",KEY_FUNC_AMPLOFFSET},
	{"KEY_FUNC_AMPLOFFSET_DBM",KEY_FUNC_AMPLOFFSET_DBM},

	{"KEY_FUNC_AMPLRESPONSE",KEY_FUNC_AMPLRESPONSE},
	{"KEY_FUNC_AMPLRESPONSE_RETURN",KEY_FUNC_AMPLRESPONSE_RETURN},
	{"KEY_FUNC_AMPLRESPONSE_FAST",KEY_FUNC_AMPLRESPONSE_FAST},
	{"KEY_FUNC_AMPLRESPONSE_SLOW",KEY_FUNC_AMPLRESPONSE_SLOW},

	{"KEY_FUNC_AMPL_ALC_STAT",KEY_FUNC_AMPL_ALC_STAT},
	{"KEY_FUNC__AMPL_ALC_RETURN",KEY_FUNC__AMPL_ALC_RETURN},
	{"KEY_FUNC__AMPL_ALC_OFF",KEY_FUNC__AMPL_ALC_OFF},
	{"KEY_FUNC__AMPL_ALC_ON",KEY_FUNC__AMPL_ALC_ON},

	{"KEY_FUNC_AMPL_CABLE",KEY_FUNC_AMPL_CABLE},
	{"KEY_FUNC_AMPL_CABLE_DB",KEY_FUNC_AMPL_CABLE_DB},

	{"KEY_FUNC_SWEEP_MODE",KEY_FUNC_SWEEP_MODE},
	{"KEY_FUNC_SWEEP_MODE_RETURN",KEY_FUNC_SWEEP_MODE_RETURN},
	{"KEY_FUNC_SWEEP_MODE_OFF",KEY_FUNC_SWEEP_MODE_OFF},
	{"KEY_FUNC_SWEEP_MODE_FREQ",KEY_FUNC_SWEEP_MODE_FREQ},
//	{"KEY_FUNC_SWEEP_MODE_FREQ_RETURN",KEY_FUNC_SWEEP_MODE_FREQ_RETURN},  
//	{"KEY_FUNC_SWEEP_MODE_FREQ_OFF",KEY_FUNC_SWEEP_MODE_FREQ_OFF},  
//	{"KEY_FUNC_SWEEP_MODE_FREQ_ON",KEY_FUNC_SWEEP_MODE_FREQ_ON},  
	{"KEY_FUNC_SWEEP_MODE_AMPL",KEY_FUNC_SWEEP_MODE_AMPL},
//	{"KEY_FUNC_SWEEP_MODE_AMPL_RETURN",KEY_FUNC_SWEEP_MODE_AMPL_RETURN},  
//	{"KEY_FUNC_SWEEP_MODE_AMPL_OFF",KEY_FUNC_SWEEP_MODE_AMPL_OFF},  
//	{"KEY_FUNC_SWEEP_MODE_AMPL_ON",KEY_FUNC_SWEEP_MODE_AMPL_ON},  
	{"KEY_FUNC_SWEEP_MODE_FREQAMPL",KEY_FUNC_SWEEP_MODE_FREQAMPL},
	{"KEY_FUNC_SWEEP_TYPE",KEY_FUNC_SWEEP_TYPE},
	{"KEY_FUNC_SWEEP_TYPE_RETURN",KEY_FUNC_SWEEP_TYPE_RETURN},
	{"KEY_FUNC_SWEEP_TYPE_LIST",KEY_FUNC_SWEEP_TYPE_LIST},
	{"KEY_FUNC_SWEEP_TYPE_STEP",KEY_FUNC_SWEEP_TYPE_STEP},
	{"KEY_FUNC_SWEEP_REPEAT",KEY_FUNC_SWEEP_REPEAT},
	{"KEY_FUNC_SWEEP_REPEAT_RETURN",KEY_FUNC_SWEEP_REPEAT_RETURN},
	{"KEY_FUNC_SWEEP_REPEAT_SINGLE",KEY_FUNC_SWEEP_REPEAT_SINGLE},
	{"KEY_FUNC_SWEEP_REPEAT_CONT",KEY_FUNC_SWEEP_REPEAT_CONT},
	{"KEY_FUNC_SWEEP_SINGLETRIGGER",KEY_FUNC_SWEEP_SINGLETRIGGER},
	{"KEY_FUNC_SWEEP_CONFIGSTEP",KEY_FUNC_SWEEP_CONFIGSTEP},
	{"KEY_FUNC_SWEEP_STEP_RETURN",KEY_FUNC_SWEEP_STEP_RETURN},
	{"KEY_FUNC_SWEEP_STEP_FREQSTART",KEY_FUNC_SWEEP_STEP_FREQSTART},
	{"KEY_FUNC_SWEEP_STEP_FREQSTART_GHZ",KEY_FUNC_SWEEP_STEP_FREQSTART_GHZ},
	{"KEY_FUNC_SWEEP_STEP_FREQSTART_MHZ",KEY_FUNC_SWEEP_STEP_FREQSTART_MHZ},
	{"KEY_FUNC_SWEEP_STEP_FREQSTART_KHZ",KEY_FUNC_SWEEP_STEP_FREQSTART_KHZ},
	{"KEY_FUNC_SWEEP_STEP_FREQSTART_HZ",KEY_FUNC_SWEEP_STEP_FREQSTART_HZ},
	{"KEY_FUNC_SWEEP_STEP_FREQSTOP",KEY_FUNC_SWEEP_STEP_FREQSTOP},
	{"KEY_FUNC_SWEEP_STEP_FREQSTOP_GHZ",KEY_FUNC_SWEEP_STEP_FREQSTOP_GHZ},
	{"KEY_FUNC_SWEEP_STEP_FREQSTOP_MHZ",KEY_FUNC_SWEEP_STEP_FREQSTOP_MHZ},
	{"KEY_FUNC_SWEEP_STEP_FREQSTOP_KHZ",KEY_FUNC_SWEEP_STEP_FREQSTOP_KHZ},
	{"KEY_FUNC_SWEEP_STEP_FREQSTOP_HZ",KEY_FUNC_SWEEP_STEP_FREQSTOP_HZ},
	{"KEY_FUNC_SWEEP_STEP_AMPLSTART",KEY_FUNC_SWEEP_STEP_AMPLSTART},
	{"KEY_FUNC_SWEEP_STEP_AMPLSTART_DBM",KEY_FUNC_SWEEP_STEP_AMPLSTART_DBM},
	{"KEY_FUNC_SWEEP_STEP_AMPLSTOP",KEY_FUNC_SWEEP_STEP_AMPLSTOP},
	{"KEY_FUNC_SWEEP_STEP_AMPLSTOP_DBM",KEY_FUNC_SWEEP_STEP_AMPLSTOP_DBM},
	{"KEY_FUNC_SWEEP_STEP_MORE",KEY_FUNC_SWEEP_STEP_MORE},
	{"KEY_FUNC_SWEEP_STEP_MORE_RETURN",KEY_FUNC_SWEEP_STEP_MORE_RETURN},
	{"KEY_FUNC_SWEEP_STEP_MORE_POINTS",KEY_FUNC_SWEEP_STEP_MORE_POINTS},
	{"KEY_FUNC_SWEEP_STEP_MORE_POINTS_ENTER",KEY_FUNC_SWEEP_STEP_MORE_POINTS_ENTER},
	{"KEY_FUNC_SWEEP_STEP_MORE_STEPDWELL",KEY_FUNC_SWEEP_STEP_MORE_STEPDWELL},
	{"KEY_FUNC_SWEEP_STEP_MORE_STEPDWELL_S",KEY_FUNC_SWEEP_STEP_MORE_STEPDWELL_S},
	{"KEY_FUNC_SWEEP_STEP_MORE_STEPDWELL_MS",KEY_FUNC_SWEEP_STEP_MORE_STEPDWELL_MS},
	{"KEY_FUNC_SWEEP_MORE",KEY_FUNC_SWEEP_MORE},
	{"KEY_FUNC_SWEEP_MORE_RETURN",KEY_FUNC_SWEEP_MORE_RETURN},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST",KEY_FUNC_SWEEP_MORE_CONFIGLIST},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_RETURN",KEY_FUNC_SWEEP_MORE_CONFIGLIST_RETURN},
	//{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_SELECTITEM",KEY_FUNC_SWEEP_MORE_CONFIGLIST_SELECTITEM},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM",KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_GHZS",KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_GHZS},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_MHZMS",KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_MHZMS},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_KHZNS",KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_KHZNS},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_HZDBM",KEY_FUNC_SWEEP_MORE_CONFIGLIST_EDITITEM_HZDBM},

	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DOWNLOAD",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DOWNLOAD},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DOWNLOAD_ENTER",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DOWNLOAD_ENTER},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_INSERTROW",KEY_FUNC_SWEEP_MORE_CONFIGLIST_INSERTROW},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_DELETEROW",KEY_FUNC_SWEEP_MORE_CONFIGLIST_DELETEROW},
	//{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_GOTOROW",KEY_FUNC_SWEEP_MORE_CONFIGLIST_GOTOROW},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_RETURN",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_RETURN},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_LOADSTORE",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_LOADSTORE},
	//{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_GOTOROW",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_GOTOROW},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_GOTOROW",KEY_FUNC_SWEEP_MORE_CONFIGLIST_GOTOROW},
	//{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_GOTOROW_ENTER",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_GOTOROW_ENTER},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_GOTOROW_ENTER",KEY_FUNC_SWEEP_MORE_CONFIGLIST_GOTOROW_ENTER},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_PRESETLIST",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_PRESETLIST},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_PRESETLIST_YES",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_PRESETLIST_YES},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_PRESETLIST_NO",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_PRESETLIST_NO},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_INSERTITEM",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_INSERTITEM},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DELETEITEM",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DELETEITEM},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE_RETURN",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE_RETURN},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE_LIST",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE_LIST},
	{"KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE_STEP",KEY_FUNC_SWEEP_MORE_CONFIGLIST_MORE_DWELLTYPE_STEP},

	{"KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION",KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION},
	{"KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION_RETURN",KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION_RETURN},
	{"KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION_DOWN",KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION_DOWN},
	{"KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION_UP",KEY_FUNC_SWEEP_MORE_SWEEPDIRECTION_UP},
	{"KEY_FUNC_SWEEP_MORE_SWEEPRETRACE",KEY_FUNC_SWEEP_MORE_SWEEPRETRACE},
	{"KEY_FUNC_SWEEP_MORE_SWEEPRETRACE_RETURN",KEY_FUNC_SWEEP_MORE_SWEEPRETRACE_RETURN},
	{"KEY_FUNC_SWEEP_MORE_SWEEPRETRACE_OFF",KEY_FUNC_SWEEP_MORE_SWEEPRETRACE_OFF},
	{"KEY_FUNC_SWEEP_MORE_SWEEPRETRACE_ON",KEY_FUNC_SWEEP_MORE_SWEEPRETRACE_ON},

	{"KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER",KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER},
	{"KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_RETURN",KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_RETURN},
	{"KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_FREERUN",KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_FREERUN},
	{"KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_TRIGGERKEY",KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_TRIGGERKEY},
	{"KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_BUS",KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_BUS},
	{"KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_EXT",KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_EXT},
	{"KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_TIMETRIGGER",KEY_FUNC_SWEEP_MORE_SWEEPTRIGGER_TIMETRIGGER},

	{"KEY_FUNC_FCTN_ANALOG",KEY_FUNC_FCTN_ANALOG},
	{"KEY_FUNC_FCTN_ANALOG_RETURN",KEY_FUNC_FCTN_ANALOG_RETURN},
	{"KEY_FUNC_FCTN_ANALOG_AM",KEY_FUNC_FCTN_ANALOG_AM},
	{"KEY_FUNC_FCTN_ANALOG_AM_STATE",KEY_FUNC_FCTN_ANALOG_AM_STATE},
	{"KEY_FUNC_FCTN_ANALOG_AM_STATE_RETURN",KEY_FUNC_FCTN_ANALOG_AM_STATE_RETURN},
	{"KEY_FUNC_FCTN_ANALOG_AM_STATE_ON",KEY_FUNC_FCTN_ANALOG_AM_STATE_ON},
	{"KEY_FUNC_FCTN_ANALOG_AM_STATE_OFF",KEY_FUNC_FCTN_ANALOG_AM_STATE_OFF},
	{"KEY_FUNC_FCTN_ANALOG_AM_DEPTH",KEY_FUNC_FCTN_ANALOG_AM_DEPTH},
	{"KEY_FUNC_FCTN_ANALOG_AM_DEPTH_PERCENT",KEY_FUNC_FCTN_ANALOG_AM_DEPTH_PERCENT},
	{"KEY_FUNC_FCTN_ANALOG_AM_RATE",KEY_FUNC_FCTN_ANALOG_AM_RATE},
	{"KEY_FUNC_FCTN_ANALOG_AM_RATE_KHZ",KEY_FUNC_FCTN_ANALOG_AM_RATE_KHZ},
	{"KEY_FUNC_FCTN_ANALOG_AM_RATE_HZ",KEY_FUNC_FCTN_ANALOG_AM_RATE_HZ},
	{"KEY_FUNC_FCTN_ANALOG_AM_RETURN",KEY_FUNC_FCTN_ANALOG_AM_RETURN},
	{"KEY_FUNC_FCTN_ANALOG_FM",KEY_FUNC_FCTN_ANALOG_FM},
	{"KEY_FUNC_FCTN_ANALOG_FM_STATE",KEY_FUNC_FCTN_ANALOG_FM_STATE},
	{"KEY_FUNC_FCTN_ANALOG_FM_STATE_RETURN",KEY_FUNC_FCTN_ANALOG_FM_STATE_RETURN},
	{"KEY_FUNC_FCTN_ANALOG_FM_STATE_ON",KEY_FUNC_FCTN_ANALOG_FM_STATE_ON},
	{"KEY_FUNC_FCTN_ANALOG_FM_STATE_OFF",KEY_FUNC_FCTN_ANALOG_FM_STATE_OFF},
	{"KEY_FUNC_FCTN_ANALOG_FM_DEVIATION",KEY_FUNC_FCTN_ANALOG_FM_DEVIATION},
	{"KEY_FUNC_FCTN_ANALOG_FM_DEVIATION_MHZ",KEY_FUNC_FCTN_ANALOG_FM_DEVIATION_MHZ},
	{"KEY_FUNC_FCTN_ANALOG_FM_DEVIATION_KHZ",KEY_FUNC_FCTN_ANALOG_FM_DEVIATION_KHZ},
	{"KEY_FUNC_FCTN_ANALOG_FM_DEVIATION_HZ",KEY_FUNC_FCTN_ANALOG_FM_DEVIATION_HZ},
	{"KEY_FUNC_FCTN_ANALOG_FM_RATE",KEY_FUNC_FCTN_ANALOG_FM_RATE},
	{"KEY_FUNC_FCTN_ANALOG_FM_RATE_KHZ",KEY_FUNC_FCTN_ANALOG_FM_RATE_KHZ},
	{"KEY_FUNC_FCTN_ANALOG_FM_RATE_HZ",KEY_FUNC_FCTN_ANALOG_FM_RATE_HZ},
	{"KEY_FUNC_FCTN_ANALOG_FM_RETURN",KEY_FUNC_FCTN_ANALOG_FM_RETURN},
	{"KEY_FUNC_FCTN_ANALOG_PM",KEY_FUNC_FCTN_ANALOG_PM},
	{"KEY_FUNC_FCTN_ANALOG_PM_STATE",KEY_FUNC_FCTN_ANALOG_PM_STATE},
	{"KEY_FUNC_FCTN_ANALOG_PM_STATE_RETURN",KEY_FUNC_FCTN_ANALOG_PM_STATE_RETURN},
	{"KEY_FUNC_FCTN_ANALOG_PM_STATE_ON",KEY_FUNC_FCTN_ANALOG_PM_STATE_ON},
	{"KEY_FUNC_FCTN_ANALOG_PM_STATE_OFF",KEY_FUNC_FCTN_ANALOG_PM_STATE_OFF},
	{"KEY_FUNC_FCTN_ANALOG_PM_PHASE",KEY_FUNC_FCTN_ANALOG_PM_PHASE},
	{"KEY_FUNC_FCTN_ANALOG_PM_PHASE_ANGLE",KEY_FUNC_FCTN_ANALOG_PM_PHASE_ANGLE},
	{"KEY_FUNC_FCTN_ANALOG_PM_RATE",KEY_FUNC_FCTN_ANALOG_PM_RATE},
	{"KEY_FUNC_FCTN_ANALOG_PM_RATE_KHZ",KEY_FUNC_FCTN_ANALOG_PM_RATE_KHZ},
	{"KEY_FUNC_FCTN_ANALOG_PM_RATE_HZ",KEY_FUNC_FCTN_ANALOG_PM_RATE_HZ},
	{"KEY_FUNC_FCTN_ANALOG_PM_RETURN",KEY_FUNC_FCTN_ANALOG_PM_RETURN},
	{"KEY_FUNC_FCTN_ANALOG_SOURCE",KEY_FUNC_FCTN_ANALOG_SOURCE},
	{"KEY_FUNC_FCTN_ANALOG_SOURCE_RETURN",KEY_FUNC_FCTN_ANALOG_SOURCE_RETURN},
	{"KEY_FUNC_FCTN_ANALOG_SOURCE_INTERNAL",KEY_FUNC_FCTN_ANALOG_SOURCE_INTERNAL},
	{"KEY_FUNC_FCTN_ANALOG_SOURCE_EXTERNAL",KEY_FUNC_FCTN_ANALOG_SOURCE_EXTERNAL},

	{"KEY_FUNC_FCTN_PLUSE",KEY_FUNC_FCTN_PLUSE},
	{"KEY_FUNC_FCTN_PLUSE_RETURN",KEY_FUNC_FCTN_PLUSE_RETURN},
	{"KEY_FUNC_FCTN_PLUSE_STATE",KEY_FUNC_FCTN_PLUSE_STATE},
	{"KEY_FUNC_FCTN_PLUSE_STATE_RETURN",KEY_FUNC_FCTN_PLUSE_STATE_RETURN},
	{"KEY_FUNC_FCTN_PLUSE_STATE_ON",KEY_FUNC_FCTN_PLUSE_STATE_ON},
	{"KEY_FUNC_FCTN_PLUSE_STATE_OFF",KEY_FUNC_FCTN_PLUSE_STATE_OFF},
	{"KEY_FUNC_FCTN_PLUSE_METHOD",KEY_FUNC_FCTN_PLUSE_METHOD},
	{"KEY_FUNC_FCTN_PLUSE_METHOD_RETURN",KEY_FUNC_FCTN_PLUSE_METHOD_RETURN},
	{"KEY_FUNC_FCTN_PLUSE_METHOD_AUTO",KEY_FUNC_FCTN_PLUSE_METHOD_AUTO},
	{"KEY_FUNC_FCTN_PLUSE_METHOD_TRIG",KEY_FUNC_FCTN_PLUSE_METHOD_TRIG},
//	{"KEY_FUNC_FCTN_PLUSE_METHOD_EXTER",KEY_FUNC_FCTN_PLUSE_METHOD_EXTER},
	{"KEY_FUNC_FCTN_PLUSE_PERIOD",KEY_FUNC_FCTN_PLUSE_PERIOD},
	{"KEY_FUNC_FCTN_PLUSE_PERIOD_S",KEY_FUNC_FCTN_PLUSE_PERIOD_S},
	{"KEY_FUNC_FCTN_PLUSE_PERIOD_MS",KEY_FUNC_FCTN_PLUSE_PERIOD_MS},
	{"KEY_FUNC_FCTN_PLUSE_PERIOD_US",KEY_FUNC_FCTN_PLUSE_PERIOD_US},
	{"KEY_FUNC_FCTN_PLUSE_PERIOD_NS",KEY_FUNC_FCTN_PLUSE_PERIOD_NS},
	{"KEY_FUNC_FCTN_PLUSE_WIDTH",KEY_FUNC_FCTN_PLUSE_WIDTH},
	{"KEY_FUNC_FCTN_PLUSE_WIDTH_S",KEY_FUNC_FCTN_PLUSE_WIDTH_S},
	{"KEY_FUNC_FCTN_PLUSE_WIDTH_MS",KEY_FUNC_FCTN_PLUSE_WIDTH_MS},
	{"KEY_FUNC_FCTN_PLUSE_WIDTH_US",KEY_FUNC_FCTN_PLUSE_WIDTH_US},
	{"KEY_FUNC_FCTN_PLUSE_WIDTH_NS",KEY_FUNC_FCTN_PLUSE_WIDTH_NS},
	{"KEY_FUNC_FCTN_PLUSE_SOURCE",KEY_FUNC_FCTN_PLUSE_SOURCE},
	{"KEY_FUNC_FCTN_PLUSE_SOURCE_RETURN",KEY_FUNC_FCTN_PLUSE_SOURCE_RETURN},
	{"KEY_FUNC_FCTN_PLUSE_SOURCE_INTERNAL",KEY_FUNC_FCTN_PLUSE_SOURCE_INTERNAL},
	{"KEY_FUNC_FCTN_PLUSE_SOURCE_EXTERNAL",KEY_FUNC_FCTN_PLUSE_SOURCE_EXTERNAL},


	{"KEY_FUNC_FCTN_DIGITAL",KEY_FUNC_FCTN_DIGITAL},
	{"KEY_FUNC_FCTN_DIGITAL_RETURN",KEY_FUNC_FCTN_DIGITAL_RETURN},

	{"KEY_FUNC_FCTN_DIGITAL_STATE",KEY_FUNC_FCTN_DIGITAL_STATE},
	{"KEY_FUNC_FCTN_DIGITAL_STATE_RETURN",KEY_FUNC_FCTN_DIGITAL_STATE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_STATE_ON",KEY_FUNC_FCTN_DIGITAL_STATE_ON},
	{"KEY_FUNC_FCTN_DIGITAL_STATE_OFF",KEY_FUNC_FCTN_DIGITAL_STATE_OFF},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE",KEY_FUNC_FCTN_DIGITAL_TYPE},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_RETURN",KEY_FUNC_FCTN_DIGITAL_TYPE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_ASK",KEY_FUNC_FCTN_DIGITAL_TYPE_ASK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_RETURN",KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_2ASK",KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_2ASK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_4ASK",KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_4ASK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_8ASK",KEY_FUNC_FCTN_DIGITAL_TYPE_ASK_8ASK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_FSK",KEY_FUNC_FCTN_DIGITAL_TYPE_FSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_RETURN",KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_MSK",KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_MSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_2FSK",KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_2FSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_4FSK",KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_4FSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_8FSK",KEY_FUNC_FCTN_DIGITAL_TYPE_FSK_8FSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_RETURN",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_2PSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_2PSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_4PSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_4PSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_8PSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_8PSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_BPSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_BPSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_QPSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_QPSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_OQPSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_OQPSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_PI2DBPSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_PI2DBPSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_RETURN",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_PI4QPSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_PI4QPSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_PI4DQPSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_PI4DQPSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_8PSK",KEY_FUNC_FCTN_DIGITAL_TYPE_PSK_MORE_8PSK},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_QAM",KEY_FUNC_FCTN_DIGITAL_TYPE_QAM},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_RETURN",KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM16",KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM16},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM32",KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM32},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM64",KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM64},
	{"KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM128",KEY_FUNC_FCTN_DIGITAL_TYPE_QAM_QAM128},

	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER",KEY_FUNC_FCTN_DIGITAL_PARAMETER},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_RETURN",KEY_FUNC_FCTN_DIGITAL_PARAMETER_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_ASKDEEP",KEY_FUNC_FCTN_DIGITAL_PARAMETER_ASKDEEP},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_ASKDEEP_PERCENT",KEY_FUNC_FCTN_DIGITAL_PARAMETER_ASKDEEP_PERCENT},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET",KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET_MHZ",KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET_MHZ},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET_KHZ",KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET_KHZ},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET_HZ",KEY_FUNC_FCTN_DIGITAL_PARAMETER_FSKOFFSET_HZ},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_PSKDEVI",KEY_FUNC_FCTN_DIGITAL_PARAMETER_PSKDEVI},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_PSKDEVI_ANGLE",KEY_FUNC_FCTN_DIGITAL_PARAMETER_PSKDEVI_ANGLE},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_RATE",KEY_FUNC_FCTN_DIGITAL_PARAMETER_RATE},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_RATE_KHZ",KEY_FUNC_FCTN_DIGITAL_PARAMETER_RATE_KHZ},
	{"KEY_FUNC_FCTN_DIGITAL_PARAMETER_RATE_HZ",KEY_FUNC_FCTN_DIGITAL_PARAMETER_RATE_HZ},

	{"KEY_FUNC_FCTN_DIGITAL_SOURCE",KEY_FUNC_FCTN_DIGITAL_SOURCE},
	{"KEY_FUNC_FCTN_DIGITAL_SOURCE_RETURN",KEY_FUNC_FCTN_DIGITAL_SOURCE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_SOURCE_INTERNAL",KEY_FUNC_FCTN_DIGITAL_SOURCE_INTERNAL},
	{"KEY_FUNC_FCTN_DIGITAL_SOURCE_EXTERNAL",KEY_FUNC_FCTN_DIGITAL_SOURCE_EXTERNAL},
	{"KEY_FUNC_FCTN_DIGITAL_MORE",KEY_FUNC_FCTN_DIGITAL_MORE},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_RETURN",KEY_FUNC_FCTN_DIGITAL_MORE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_LOAD",KEY_FUNC_FCTN_DIGITAL_MORE_LOAD},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_LOAD_ENTER",KEY_FUNC_FCTN_DIGITAL_MORE_LOAD_ENTER},

	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE",KEY_FUNC_FCTN_DIGITAL_DATASOURCE},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_RETURN",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_ALL0",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_ALL0},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_ALL1",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_ALL1},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_RETURN",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS7",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS7},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS9",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS9},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS11",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS11},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS15",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PRBS_PRBS15},
	{"KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PATTERN",KEY_FUNC_FCTN_DIGITAL_DATASOURCE_PATTERN},

	{"KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE",KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE_SYMLS",KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE_SYMLS},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE_KSYMLS",KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE_KSYMLS},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE_MSYMLS",KEY_FUNC_FCTN_DIGITAL_MORE_SYMBOLRATE_MSYMLS},

	{"KEY_FUNC_FCTN_DIGITAL_MORE",KEY_FUNC_FCTN_DIGITAL_MORE},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_RETURN",KEY_FUNC_FCTN_DIGITAL_MORE_RETURN},

	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_RETURN",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_ROOTCOSINE",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_ROOTCOSINE},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_COSINE",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_COSINE},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_GAUSSPURE",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_GAUSSPURE},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_GAUSSFSK",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERSELECT_GAUSSFSK},

	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA_RETURN",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA_BT",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA_BT},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA_STOPFREQ",KEY_FUNC_FCTN_DIGITAL_MORE_FILTERPARA_STOPFREQ},

/*
	{"KEY_FUNC_FCTN_DIGITAL",KEY_FUNC_FCTN_DIGITAL},
	{"KEY_FUNC_FCTN_DIGITAL_ASK",KEY_FUNC_FCTN_DIGITAL_ASK},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_STATE",KEY_FUNC_FCTN_DIGITAL_ASK_STATE},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_STATE_RETURN",KEY_FUNC_FCTN_DIGITAL_ASK_STATE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_STATE_ON",KEY_FUNC_FCTN_DIGITAL_ASK_STATE_ON},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_STATE_OFF",KEY_FUNC_FCTN_DIGITAL_ASK_STATE_OFF},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_MODE",KEY_FUNC_FCTN_DIGITAL_ASK_MODE},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_MODE_RETURN",KEY_FUNC_FCTN_DIGITAL_ASK_MODE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_MODE_ASK2",KEY_FUNC_FCTN_DIGITAL_ASK_MODE_ASK2},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_MODE_ASK4",KEY_FUNC_FCTN_DIGITAL_ASK_MODE_ASK4},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_MODE_ASK8",KEY_FUNC_FCTN_DIGITAL_ASK_MODE_ASK8},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_RATE",KEY_FUNC_FCTN_DIGITAL_ASK_RATE},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_RATE_KHZ",KEY_FUNC_FCTN_DIGITAL_ASK_RATE_KHZ},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_RATE_HZ",KEY_FUNC_FCTN_DIGITAL_ASK_RATE_HZ},
	{"KEY_FUNC_FCTN_DIGITAL_ASK_RETURN",KEY_FUNC_FCTN_DIGITAL_ASK_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_FSK",KEY_FUNC_FCTN_DIGITAL_FSK},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_STATE",KEY_FUNC_FCTN_DIGITAL_FSK_STATE},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_STATE_RETURN",KEY_FUNC_FCTN_DIGITAL_FSK_STATE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_STATE_ON",KEY_FUNC_FCTN_DIGITAL_FSK_STATE_ON},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_STATE_OFF",KEY_FUNC_FCTN_DIGITAL_FSK_STATE_OFF},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_MODE",KEY_FUNC_FCTN_DIGITAL_FSK_MODE},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_MODE_RETURN",KEY_FUNC_FCTN_DIGITAL_FSK_MODE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_MODE_FSK2",KEY_FUNC_FCTN_DIGITAL_FSK_MODE_FSK2},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_MODE_FSK4",KEY_FUNC_FCTN_DIGITAL_FSK_MODE_FSK4},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_MODE_FSK8",KEY_FUNC_FCTN_DIGITAL_FSK_MODE_FSK8},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_RATE",KEY_FUNC_FCTN_DIGITAL_FSK_RATE},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_RATE_MHZ",KEY_FUNC_FCTN_DIGITAL_FSK_RATE_MHZ},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_RATE_KHZ",KEY_FUNC_FCTN_DIGITAL_FSK_RATE_KHZ},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_RATE_HZ",KEY_FUNC_FCTN_DIGITAL_FSK_RATE_HZ},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_STEP",KEY_FUNC_FCTN_DIGITAL_FSK_STEP},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_STEP_MHZ",KEY_FUNC_FCTN_DIGITAL_FSK_STEP_MHZ},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_STEP_KHZ",KEY_FUNC_FCTN_DIGITAL_FSK_STEP_KHZ},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_STEP_HZ",KEY_FUNC_FCTN_DIGITAL_FSK_STEP_HZ},
	{"KEY_FUNC_FCTN_DIGITAL_FSK_RETURN",KEY_FUNC_FCTN_DIGITAL_FSK_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_PSK",KEY_FUNC_FCTN_DIGITAL_PSK},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_STATE",KEY_FUNC_FCTN_DIGITAL_PSK_STATE},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_STATE_RETURN",KEY_FUNC_FCTN_DIGITAL_PSK_STATE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_STATE_ON",KEY_FUNC_FCTN_DIGITAL_PSK_STATE_ON},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_STATE_OFF",KEY_FUNC_FCTN_DIGITAL_PSK_STATE_OFF},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_MODE",KEY_FUNC_FCTN_DIGITAL_PSK_MODE},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_MODE_RETURN",KEY_FUNC_FCTN_DIGITAL_PSK_MODE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_MODE_BPSK",KEY_FUNC_FCTN_DIGITAL_PSK_MODE_BPSK},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_MODE_QPSK",KEY_FUNC_FCTN_DIGITAL_PSK_MODE_QPSK},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_MODE_PI4PSK",KEY_FUNC_FCTN_DIGITAL_PSK_MODE_PI4PSK},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_MODE_PSK8",KEY_FUNC_FCTN_DIGITAL_PSK_MODE_PSK8},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_RATE",KEY_FUNC_FCTN_DIGITAL_PSK_RATE},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_RATE_KHZ",KEY_FUNC_FCTN_DIGITAL_PSK_RATE_KHZ},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_RATE_HZ",KEY_FUNC_FCTN_DIGITAL_PSK_RATE_HZ},
	{"KEY_FUNC_FCTN_DIGITAL_PSK_RETURN",KEY_FUNC_FCTN_DIGITAL_PSK_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_MODWAVE",KEY_FUNC_FCTN_DIGITAL_MODWAVE},
	{"KEY_FUNC_FCTN_DIGITAL_MODWAVE_RETURN",KEY_FUNC_FCTN_DIGITAL_MODWAVE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_MODWAVE_MARRAY",KEY_FUNC_FCTN_DIGITAL_MODWAVE_MARRAY},
	{"KEY_FUNC_FCTN_DIGITAL_MORE",KEY_FUNC_FCTN_DIGITAL_MORE},
	{"KEY_FUNC_FCTN_DIGITAL_MORE_RETURN",KEY_FUNC_FCTN_DIGITAL_MORE_RETURN},
	{"KEY_FUNC_FCTN_DIGITAL_RETURN",KEY_FUNC_FCTN_DIGITAL_RETURN},
*/

	{"KEY_FUNC_FCTN_LF",KEY_FUNC_FCTN_LF},
	{"KEY_FUNC_FCTN_LF_RETURN",KEY_FUNC_FCTN_LF_RETURN},
	{"KEY_FUNC_FCTN_LF_STATE",KEY_FUNC_FCTN_LF_STATE},
	{"KEY_FUNC_FCTN_LF_STATE_RETURN",KEY_FUNC_FCTN_LF_STATE_RETURN},
	{"KEY_FUNC_FCTN_LF_STATE_ON",KEY_FUNC_FCTN_LF_STATE_ON},
	{"KEY_FUNC_FCTN_LF_STATE_OFF",KEY_FUNC_FCTN_LF_STATE_OFF},
	{"KEY_FUNC_FCTN_LF_SOURCE",KEY_FUNC_FCTN_LF_SOURCE},
	{"KEY_FUNC_FCTN_LF_SOURCE_RETURN",KEY_FUNC_FCTN_LF_SOURCE_RETURN},
//	{"KEY_FUNC_FCTN_LF_SOURCE_INTERNAL",KEY_FUNC_FCTN_LF_SOURCE_INTERNAL},
//	{"KEY_FUNC_FCTN_LF_SOURCE_EXTERNAL",KEY_FUNC_FCTN_LF_SOURCE_EXTERNAL},
//	{"KEY_FUNC_FCTN_LF_WAVEFORM_RETURN",KEY_FUNC_FCTN_LF_WAVEFORM_RETURN},
	{"KEY_FUNC_FCTN_LF_WAVEFORM_SINE",KEY_FUNC_FCTN_LF_WAVEFORM_SINE},
	{"KEY_FUNC_FCTN_LF_WAVEFORM_SQUARE",KEY_FUNC_FCTN_LF_WAVEFORM_SQUARE},
	{"KEY_FUNC_FCTN_LF_WAVEFORM_TRIANGULAR",KEY_FUNC_FCTN_LF_WAVEFORM_TRIANGULAR},
	{"KEY_FUNC_FCTN_LF_WAVEFORM_SAWTOOTH",KEY_FUNC_FCTN_LF_WAVEFORM_SAWTOOTH},
	{"KEY_FUNC_FCTN_LF_SOURCE_SINC",KEY_FUNC_FCTN_LF_SOURCE_SINC},
	{"KEY_FUNC_FCTN_LF_AMPL",KEY_FUNC_FCTN_LF_AMPL},
	{"KEY_FUNC_FCTN_LF_AMPL_VPP",KEY_FUNC_FCTN_LF_AMPL_VPP},
	{"KEY_FUNC_FCTN_LF_AMPL_MVPP",KEY_FUNC_FCTN_LF_AMPL_MVPP},
	{"KEY_FUNC_FCTN_LF_FREQ",KEY_FUNC_FCTN_LF_FREQ},
	{"KEY_FUNC_FCTN_LF_FREQ_MHZ",KEY_FUNC_FCTN_LF_FREQ_MHZ},
	{"KEY_FUNC_FCTN_LF_FREQ_KHZ",KEY_FUNC_FCTN_LF_FREQ_KHZ},
	{"KEY_FUNC_FCTN_LF_FREQ_HZ",KEY_FUNC_FCTN_LF_FREQ_HZ},

	{"KEY_FUNC_FCTN_EXTRF",KEY_FUNC_FCTN_EXTRF},
	{"KEY_FUNC_FCTN_EXTRF_RETURN",KEY_FUNC_FCTN_EXTRF_RETURN},
	{"KEY_FUNC_FCTN_EXTRF_EXTRF",KEY_FUNC_FCTN_EXTRF_EXTRF},
	{"KEY_FUNC_FCTN_EXTRF_EXTRF_INT",KEY_FUNC_FCTN_EXTRF_EXTRF_INT},
	{"KEY_FUNC_FCTN_EXTRF_EXTRF_EXT",KEY_FUNC_FCTN_EXTRF_EXTRF_EXT},
	{"KEY_FUNC_FCTN_EXTRF_EXTRF_RETURN",KEY_FUNC_FCTN_EXTRF_EXTRF_RETURN},
	{"KEY_FUNC_FCTN_EXTRF_FREQ",KEY_FUNC_FCTN_EXTRF_FREQ},
	{"KEY_FUNC_FCTN_EXTRF_FREQ_GHZ",KEY_FUNC_FCTN_EXTRF_FREQ_GHZ},
	{"KEY_FUNC_FCTN_EXTRF_FREQ_MHZ",KEY_FUNC_FCTN_EXTRF_FREQ_MHZ},
	{"KEY_FUNC_FCTN_EXTRF_FREQ_KHZ",KEY_FUNC_FCTN_EXTRF_FREQ_KHZ},
	{"KEY_FUNC_FCTN_EXTRF_FREQ_HZ",KEY_FUNC_FCTN_EXTRF_FREQ_HZ},

	{"KEY_FUNC_FCTN_DRG",KEY_FUNC_FCTN_DRG},
	{"KEY_FUNC_FCTN_DRG_RETURN",KEY_FUNC_FCTN_DRG_RETURN},
	{"KEY_FUNC_FCTN_DRG_STATE",KEY_FUNC_FCTN_DRG_STATE},
	{"KEY_FUNC_FCTN_DRG_STATE_RETURN",KEY_FUNC_FCTN_DRG_STATE_RETURN},
	{"KEY_FUNC_FCTN_DRG_STATE_ON",KEY_FUNC_FCTN_DRG_STATE_ON},
	{"KEY_FUNC_FCTN_DRG_STATE_OFF",KEY_FUNC_FCTN_DRG_STATE_OFF},
	{"KEY_FUNC_FCTN_DRG_UPLIMIT",KEY_FUNC_FCTN_DRG_UPLIMIT},
	{"KEY_FUNC_FCTN_DRG_UPLIMIT_GHZ",KEY_FUNC_FCTN_DRG_UPLIMIT_GHZ},
	{"KEY_FUNC_FCTN_DRG_UPLIMIT_MHZ",KEY_FUNC_FCTN_DRG_UPLIMIT_MHZ},
	{"KEY_FUNC_FCTN_DRG_UPLIMIT_KHZ",KEY_FUNC_FCTN_DRG_UPLIMIT_KHZ},
	{"KEY_FUNC_FCTN_DRG_UPLIMIT_HZ",KEY_FUNC_FCTN_DRG_UPLIMIT_HZ},
	{"KEY_FUNC_FCTN_DRG_DOWNLIMIT",KEY_FUNC_FCTN_DRG_DOWNLIMIT},
	{"KEY_FUNC_FCTN_DRG_DOWNLIMIT_GHZ",KEY_FUNC_FCTN_DRG_DOWNLIMIT_GHZ},
	{"KEY_FUNC_FCTN_DRG_DOWNLIMIT_MHZ",KEY_FUNC_FCTN_DRG_DOWNLIMIT_MHZ},
	{"KEY_FUNC_FCTN_DRG_DOWNLIMIT_KHZ",KEY_FUNC_FCTN_DRG_DOWNLIMIT_KHZ},
	{"KEY_FUNC_FCTN_DRG_DOWNLIMIT_HZ",KEY_FUNC_FCTN_DRG_DOWNLIMIT_HZ},
	{"KEY_FUNC_FCTN_DRG_POINTS",KEY_FUNC_FCTN_DRG_POINTS},
	{"KEY_FUNC_FCTN_DRG_POINTS_ENTER",KEY_FUNC_FCTN_DRG_POINTS_ENTER},
	{"KEY_FUNC_FCTN_DRG_MORE",KEY_FUNC_FCTN_DRG_MORE},
	{"KEY_FUNC_FCTN_DRG_MORE_RETURN",KEY_FUNC_FCTN_DRG_MORE_RETURN},
	{"KEY_FUNC_FCTN_DRG_MORE_RATE",KEY_FUNC_FCTN_DRG_MORE_RATE},
	{"KEY_FUNC_FCTN_DRG_MORE_RATE_MS",KEY_FUNC_FCTN_DRG_MORE_RATE_MS},
	{"KEY_FUNC_FCTN_DRG_MORE_RATE_US",KEY_FUNC_FCTN_DRG_MORE_RATE_US},
	{"KEY_FUNC_FCTN_DRG_MORE_RATE_NS",KEY_FUNC_FCTN_DRG_MORE_RATE_NS},
	{"KEY_FUNC_FCTN_DRG_MORE_WORKMODE",KEY_FUNC_FCTN_DRG_MORE_WORKMODE},
	{"KEY_FUNC_FCTN_DRG_MORE_WORKMODE_RETURN",KEY_FUNC_FCTN_DRG_MORE_WORKMODE_RETURN},
	{"KEY_FUNC_FCTN_DRG_MORE_WORKMODE_NORMAL",KEY_FUNC_FCTN_DRG_MORE_WORKMODE_NORMAL},
	{"KEY_FUNC_FCTN_DRG_MORE_WORKMODE_POSITIVE",KEY_FUNC_FCTN_DRG_MORE_WORKMODE_POSITIVE},
	{"KEY_FUNC_FCTN_DRG_MORE_WORKMODE_NEGATIVE",KEY_FUNC_FCTN_DRG_MORE_WORKMODE_NEGATIVE},


	{"KEY_FUNC_AUX_LAN",KEY_FUNC_AUX_LAN},
	{"KEY_FUNC_AUX_LAN_IP",KEY_FUNC_AUX_LAN_IP},
	{"KEY_FUNC_AUX_LAN_IP_ENTER",KEY_FUNC_AUX_LAN_IP_ENTER},
	{"KEY_FUNC_AUX_LAN_MASK",KEY_FUNC_AUX_LAN_MASK},
	{"KEY_FUNC_AUX_LAN_MASK_ENTER",KEY_FUNC_AUX_LAN_MASK_ENTER},
	{"KEY_FUNC_AUX_LAN_GATEWAY",KEY_FUNC_AUX_LAN_GATEWAY},
	{"KEY_FUNC_AUX_LAN_GATEWAY_ENTER",KEY_FUNC_AUX_LAN_GATEWAY_ENTER},
	{"KEY_FUNC_AUX_LAN_RETURN",KEY_FUNC_AUX_LAN_RETURN},

	{"KEY_FUNC_AUX_SCPI",KEY_FUNC_AUX_SCPI},
	{"KEY_FUNC_AUX_SCPI_RETURN",KEY_FUNC_AUX_SCPI_RETURN},
	{"KEY_FUNC_AUX_SCPI_ON",KEY_FUNC_AUX_SCPI_ON},
	{"KEY_FUNC_AUX_SCPI_OFF",KEY_FUNC_AUX_SCPI_OFF},
//ZPC
	{"KEY_FUNC_AUX_LANGUAGE",KEY_FUNC_AUX_LANGUAGE},
	{"KEY_FUNC_AUX_LANGUAGE_RETURN",KEY_FUNC_AUX_LANGUAGE_RETURN},
	{"KEY_FUNC_AUX_LANGUAGE_CHINESE",KEY_FUNC_AUX_LANGUAGE_CHINESE},
	{"KEY_FUNC_AUX_LANGUAGE_ENGLISH",KEY_FUNC_AUX_LANGUAGE_ENGLISH},
//系统服务
	{"KEY_FUNC_AUX_SERVICE",KEY_FUNC_AUX_SERVICE},
	{"KEY_FUNC_AUX_SERVICE_RETURN",KEY_FUNC_AUX_SERVICE_RETURN},
	{"KEY_FUNC_AUX_SERVICE_EVALUATE",KEY_FUNC_AUX_SERVICE_EVALUATE},
	{"KEY_FUNC_AUX_SERVICE_EVALUATE_RETURN",KEY_FUNC_AUX_SERVICE_EVALUATE_RETURN},
	{"KEY_FUNC_AUX_SERVICE_EVALUATE_ON",KEY_FUNC_AUX_SERVICE_EVALUATE_ON},
	{"KEY_FUNC_AUX_SERVICE_EVALUATE_OFF",KEY_FUNC_AUX_SERVICE_EVALUATE_OFF},
	{"KEY_FUNC_AUX_SERVICE_LANMACADDR", KEY_FUNC_AUX_SERVICE_LANMACADDR},
	{"KEY_FUNC_AUX_SERVICE_LANMACADDR_ENTER",KEY_FUNC_AUX_SERVICE_LANMACADDR_ENTER},

	{"",},
};

//****************************************
//* 菜单类(继承自tBaseMenu)
//****************************************
class tSysMenu : public tBaseMenu
{
  Q_OBJECT
  public:
    tSysMenu(QString xmlFileName);                 //构造
    ~tSysMenu();                                   //析构

    mainKeyDef* mainKeyTemp;                       //主键临时变量指针
    subKeyDef* subKeyTemp;                         //子键临时变量指针

    bool isUpArrow(int value);                     //上方向键
    bool isRightRpg(int value);                    //右脉冲旋钮
    int getRpgPulse(int value, int value2);        //获取脉冲数
    bool pressedIsEnterKey(int value);             //按下的是确认键
    bool pressedIsArrowKey(int value);             //按下的是方向键
    bool pressedIsRpgKey(int value);               //按下的是脉冲旋钮键
    bool pressedIsMainKey(int value);              //按下的是主键
    bool pressedIsCommonKey(int value);            //按下的是通用键
    bool pressedIsNumberKey(int value);            //按下的是数字键
    bool pressedIsBkspaceKey(int value);           //按下的是回滚键
    bool pressedIsEscKey(int value);               //按下的是取消键
    bool pressedIsUnitKey(int value);              //按下的是单位键

    void getMainKeyPointer(int value);             //获取主键指针
    bool getSubKeyPointer(int value);              //获取子键指针

    void gotoUpLevel(void);                        //返回上级
    void gotoDownLevel(void);                      //进入下级

    int getButtonIndex(int value);                 //获取按键索引
  private:
    void getSystemKeyAndFuncValue(void);           //获取系统键码值
    void getSubSubKey(subKeyDef* key);             //递归获取子键

    int getKeyValue(QString keyValueString);       //获取键值
    int getFuncCode(QString funcCodeString);       //获取功能码
};

#endif
